// Code generated by ent, DO NOT EDIT.

package merchant

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the merchant type in the database.
	Label = "merchant"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPid holds the string denoting the pid field in the database.
	FieldPid = "pid"
	// FieldPkey holds the string denoting the pkey field in the database.
	FieldPkey = "pkey"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldFeeRate holds the string denoting the fee_rate field in the database.
	FieldFeeRate = "fee_rate"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldNotifyURL holds the string denoting the notify_url field in the database.
	FieldNotifyURL = "notify_url"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeOrders holds the string denoting the orders edge name in mutations.
	EdgeOrders = "orders"
	// EdgeSettlements holds the string denoting the settlements edge name in mutations.
	EdgeSettlements = "settlements"
	// EdgeWithdraws holds the string denoting the withdraws edge name in mutations.
	EdgeWithdraws = "withdraws"
	// Table holds the table name of the merchant in the database.
	Table = "merchants"
	// OrdersTable is the table that holds the orders relation/edge.
	OrdersTable = "orders"
	// OrdersInverseTable is the table name for the Order entity.
	// It exists in this package in order to avoid circular dependency with the "order" package.
	OrdersInverseTable = "orders"
	// OrdersColumn is the table column denoting the orders relation/edge.
	OrdersColumn = "merchant_id"
	// SettlementsTable is the table that holds the settlements relation/edge.
	SettlementsTable = "settlements"
	// SettlementsInverseTable is the table name for the Settlement entity.
	// It exists in this package in order to avoid circular dependency with the "settlement" package.
	SettlementsInverseTable = "settlements"
	// SettlementsColumn is the table column denoting the settlements relation/edge.
	SettlementsColumn = "merchant_id"
	// WithdrawsTable is the table that holds the withdraws relation/edge.
	WithdrawsTable = "withdraws"
	// WithdrawsInverseTable is the table name for the Withdraw entity.
	// It exists in this package in order to avoid circular dependency with the "withdraw" package.
	WithdrawsInverseTable = "withdraws"
	// WithdrawsColumn is the table column denoting the withdraws relation/edge.
	WithdrawsColumn = "merchant_id"
)

// Columns holds all SQL columns for merchant fields.
var Columns = []string{
	FieldID,
	FieldPid,
	FieldPkey,
	FieldName,
	FieldFeeRate,
	FieldStatus,
	FieldNotifyURL,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PkeyValidator is a validator for the "pkey" field. It is called by the builders before save.
	PkeyValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultFeeRate holds the default value on creation for the "fee_rate" field.
	DefaultFeeRate float64
	// DefaultNotifyURL holds the default value on creation for the "notify_url" field.
	DefaultNotifyURL string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive   Status = "active"
	StatusDisabled Status = "disabled"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusDisabled:
		return nil
	default:
		return fmt.Errorf("merchant: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Merchant queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPid orders the results by the pid field.
func ByPid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPid, opts...).ToFunc()
}

// ByPkey orders the results by the pkey field.
func ByPkey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPkey, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByFeeRate orders the results by the fee_rate field.
func ByFeeRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeeRate, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByNotifyURL orders the results by the notify_url field.
func ByNotifyURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotifyURL, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByOrdersCount orders the results by orders count.
func ByOrdersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOrdersStep(), opts...)
	}
}

// ByOrders orders the results by orders terms.
func ByOrders(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrdersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySettlementsCount orders the results by settlements count.
func BySettlementsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSettlementsStep(), opts...)
	}
}

// BySettlements orders the results by settlements terms.
func BySettlements(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSettlementsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByWithdrawsCount orders the results by withdraws count.
func ByWithdrawsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newWithdrawsStep(), opts...)
	}
}

// ByWithdraws orders the results by withdraws terms.
func ByWithdraws(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWithdrawsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newOrdersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrdersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OrdersTable, OrdersColumn),
	)
}
func newSettlementsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SettlementsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SettlementsTable, SettlementsColumn),
	)
}
func newWithdrawsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WithdrawsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, WithdrawsTable, WithdrawsColumn),
	)
}
