// Code generated by ent, DO NOT EDIT.

package merchant

import (
	"epay/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Merchant {
	return predicate.Merchant(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Merchant {
	return predicate.Merchant(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Merchant {
	return predicate.Merchant(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Merchant {
	return predicate.Merchant(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Merchant {
	return predicate.Merchant(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Merchant {
	return predicate.Merchant(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Merchant {
	return predicate.Merchant(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Merchant {
	return predicate.Merchant(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Merchant {
	return predicate.Merchant(sql.FieldLTE(FieldID, id))
}

// Pid applies equality check predicate on the "pid" field. It's identical to PidEQ.
func Pid(v int) predicate.Merchant {
	return predicate.Merchant(sql.FieldEQ(FieldPid, v))
}

// Pkey applies equality check predicate on the "pkey" field. It's identical to PkeyEQ.
func Pkey(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldEQ(FieldPkey, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldEQ(FieldName, v))
}

// FeeRate applies equality check predicate on the "fee_rate" field. It's identical to FeeRateEQ.
func FeeRate(v float64) predicate.Merchant {
	return predicate.Merchant(sql.FieldEQ(FieldFeeRate, v))
}

// NotifyURL applies equality check predicate on the "notify_url" field. It's identical to NotifyURLEQ.
func NotifyURL(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldEQ(FieldNotifyURL, v))
}

// Keytype applies equality check predicate on the "keytype" field. It's identical to KeytypeEQ.
func Keytype(v int) predicate.Merchant {
	return predicate.Merchant(sql.FieldEQ(FieldKeytype, v))
}

// PublicKey applies equality check predicate on the "public_key" field. It's identical to PublicKeyEQ.
func PublicKey(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldEQ(FieldPublicKey, v))
}

// RefundEnabled applies equality check predicate on the "refund_enabled" field. It's identical to RefundEnabledEQ.
func RefundEnabled(v bool) predicate.Merchant {
	return predicate.Merchant(sql.FieldEQ(FieldRefundEnabled, v))
}

// TransferEnabled applies equality check predicate on the "transfer_enabled" field. It's identical to TransferEnabledEQ.
func TransferEnabled(v bool) predicate.Merchant {
	return predicate.Merchant(sql.FieldEQ(FieldTransferEnabled, v))
}

// Mode applies equality check predicate on the "mode" field. It's identical to ModeEQ.
func Mode(v int) predicate.Merchant {
	return predicate.Merchant(sql.FieldEQ(FieldMode, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Merchant {
	return predicate.Merchant(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Merchant {
	return predicate.Merchant(sql.FieldEQ(FieldUpdatedAt, v))
}

// PidEQ applies the EQ predicate on the "pid" field.
func PidEQ(v int) predicate.Merchant {
	return predicate.Merchant(sql.FieldEQ(FieldPid, v))
}

// PidNEQ applies the NEQ predicate on the "pid" field.
func PidNEQ(v int) predicate.Merchant {
	return predicate.Merchant(sql.FieldNEQ(FieldPid, v))
}

// PidIn applies the In predicate on the "pid" field.
func PidIn(vs ...int) predicate.Merchant {
	return predicate.Merchant(sql.FieldIn(FieldPid, vs...))
}

// PidNotIn applies the NotIn predicate on the "pid" field.
func PidNotIn(vs ...int) predicate.Merchant {
	return predicate.Merchant(sql.FieldNotIn(FieldPid, vs...))
}

// PidGT applies the GT predicate on the "pid" field.
func PidGT(v int) predicate.Merchant {
	return predicate.Merchant(sql.FieldGT(FieldPid, v))
}

// PidGTE applies the GTE predicate on the "pid" field.
func PidGTE(v int) predicate.Merchant {
	return predicate.Merchant(sql.FieldGTE(FieldPid, v))
}

// PidLT applies the LT predicate on the "pid" field.
func PidLT(v int) predicate.Merchant {
	return predicate.Merchant(sql.FieldLT(FieldPid, v))
}

// PidLTE applies the LTE predicate on the "pid" field.
func PidLTE(v int) predicate.Merchant {
	return predicate.Merchant(sql.FieldLTE(FieldPid, v))
}

// PkeyEQ applies the EQ predicate on the "pkey" field.
func PkeyEQ(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldEQ(FieldPkey, v))
}

// PkeyNEQ applies the NEQ predicate on the "pkey" field.
func PkeyNEQ(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldNEQ(FieldPkey, v))
}

// PkeyIn applies the In predicate on the "pkey" field.
func PkeyIn(vs ...string) predicate.Merchant {
	return predicate.Merchant(sql.FieldIn(FieldPkey, vs...))
}

// PkeyNotIn applies the NotIn predicate on the "pkey" field.
func PkeyNotIn(vs ...string) predicate.Merchant {
	return predicate.Merchant(sql.FieldNotIn(FieldPkey, vs...))
}

// PkeyGT applies the GT predicate on the "pkey" field.
func PkeyGT(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldGT(FieldPkey, v))
}

// PkeyGTE applies the GTE predicate on the "pkey" field.
func PkeyGTE(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldGTE(FieldPkey, v))
}

// PkeyLT applies the LT predicate on the "pkey" field.
func PkeyLT(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldLT(FieldPkey, v))
}

// PkeyLTE applies the LTE predicate on the "pkey" field.
func PkeyLTE(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldLTE(FieldPkey, v))
}

// PkeyContains applies the Contains predicate on the "pkey" field.
func PkeyContains(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldContains(FieldPkey, v))
}

// PkeyHasPrefix applies the HasPrefix predicate on the "pkey" field.
func PkeyHasPrefix(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldHasPrefix(FieldPkey, v))
}

// PkeyHasSuffix applies the HasSuffix predicate on the "pkey" field.
func PkeyHasSuffix(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldHasSuffix(FieldPkey, v))
}

// PkeyEqualFold applies the EqualFold predicate on the "pkey" field.
func PkeyEqualFold(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldEqualFold(FieldPkey, v))
}

// PkeyContainsFold applies the ContainsFold predicate on the "pkey" field.
func PkeyContainsFold(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldContainsFold(FieldPkey, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Merchant {
	return predicate.Merchant(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Merchant {
	return predicate.Merchant(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldContainsFold(FieldName, v))
}

// FeeRateEQ applies the EQ predicate on the "fee_rate" field.
func FeeRateEQ(v float64) predicate.Merchant {
	return predicate.Merchant(sql.FieldEQ(FieldFeeRate, v))
}

// FeeRateNEQ applies the NEQ predicate on the "fee_rate" field.
func FeeRateNEQ(v float64) predicate.Merchant {
	return predicate.Merchant(sql.FieldNEQ(FieldFeeRate, v))
}

// FeeRateIn applies the In predicate on the "fee_rate" field.
func FeeRateIn(vs ...float64) predicate.Merchant {
	return predicate.Merchant(sql.FieldIn(FieldFeeRate, vs...))
}

// FeeRateNotIn applies the NotIn predicate on the "fee_rate" field.
func FeeRateNotIn(vs ...float64) predicate.Merchant {
	return predicate.Merchant(sql.FieldNotIn(FieldFeeRate, vs...))
}

// FeeRateGT applies the GT predicate on the "fee_rate" field.
func FeeRateGT(v float64) predicate.Merchant {
	return predicate.Merchant(sql.FieldGT(FieldFeeRate, v))
}

// FeeRateGTE applies the GTE predicate on the "fee_rate" field.
func FeeRateGTE(v float64) predicate.Merchant {
	return predicate.Merchant(sql.FieldGTE(FieldFeeRate, v))
}

// FeeRateLT applies the LT predicate on the "fee_rate" field.
func FeeRateLT(v float64) predicate.Merchant {
	return predicate.Merchant(sql.FieldLT(FieldFeeRate, v))
}

// FeeRateLTE applies the LTE predicate on the "fee_rate" field.
func FeeRateLTE(v float64) predicate.Merchant {
	return predicate.Merchant(sql.FieldLTE(FieldFeeRate, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Merchant {
	return predicate.Merchant(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Merchant {
	return predicate.Merchant(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Merchant {
	return predicate.Merchant(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Merchant {
	return predicate.Merchant(sql.FieldNotIn(FieldStatus, vs...))
}

// NotifyURLEQ applies the EQ predicate on the "notify_url" field.
func NotifyURLEQ(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldEQ(FieldNotifyURL, v))
}

// NotifyURLNEQ applies the NEQ predicate on the "notify_url" field.
func NotifyURLNEQ(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldNEQ(FieldNotifyURL, v))
}

// NotifyURLIn applies the In predicate on the "notify_url" field.
func NotifyURLIn(vs ...string) predicate.Merchant {
	return predicate.Merchant(sql.FieldIn(FieldNotifyURL, vs...))
}

// NotifyURLNotIn applies the NotIn predicate on the "notify_url" field.
func NotifyURLNotIn(vs ...string) predicate.Merchant {
	return predicate.Merchant(sql.FieldNotIn(FieldNotifyURL, vs...))
}

// NotifyURLGT applies the GT predicate on the "notify_url" field.
func NotifyURLGT(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldGT(FieldNotifyURL, v))
}

// NotifyURLGTE applies the GTE predicate on the "notify_url" field.
func NotifyURLGTE(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldGTE(FieldNotifyURL, v))
}

// NotifyURLLT applies the LT predicate on the "notify_url" field.
func NotifyURLLT(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldLT(FieldNotifyURL, v))
}

// NotifyURLLTE applies the LTE predicate on the "notify_url" field.
func NotifyURLLTE(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldLTE(FieldNotifyURL, v))
}

// NotifyURLContains applies the Contains predicate on the "notify_url" field.
func NotifyURLContains(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldContains(FieldNotifyURL, v))
}

// NotifyURLHasPrefix applies the HasPrefix predicate on the "notify_url" field.
func NotifyURLHasPrefix(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldHasPrefix(FieldNotifyURL, v))
}

// NotifyURLHasSuffix applies the HasSuffix predicate on the "notify_url" field.
func NotifyURLHasSuffix(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldHasSuffix(FieldNotifyURL, v))
}

// NotifyURLIsNil applies the IsNil predicate on the "notify_url" field.
func NotifyURLIsNil() predicate.Merchant {
	return predicate.Merchant(sql.FieldIsNull(FieldNotifyURL))
}

// NotifyURLNotNil applies the NotNil predicate on the "notify_url" field.
func NotifyURLNotNil() predicate.Merchant {
	return predicate.Merchant(sql.FieldNotNull(FieldNotifyURL))
}

// NotifyURLEqualFold applies the EqualFold predicate on the "notify_url" field.
func NotifyURLEqualFold(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldEqualFold(FieldNotifyURL, v))
}

// NotifyURLContainsFold applies the ContainsFold predicate on the "notify_url" field.
func NotifyURLContainsFold(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldContainsFold(FieldNotifyURL, v))
}

// KeytypeEQ applies the EQ predicate on the "keytype" field.
func KeytypeEQ(v int) predicate.Merchant {
	return predicate.Merchant(sql.FieldEQ(FieldKeytype, v))
}

// KeytypeNEQ applies the NEQ predicate on the "keytype" field.
func KeytypeNEQ(v int) predicate.Merchant {
	return predicate.Merchant(sql.FieldNEQ(FieldKeytype, v))
}

// KeytypeIn applies the In predicate on the "keytype" field.
func KeytypeIn(vs ...int) predicate.Merchant {
	return predicate.Merchant(sql.FieldIn(FieldKeytype, vs...))
}

// KeytypeNotIn applies the NotIn predicate on the "keytype" field.
func KeytypeNotIn(vs ...int) predicate.Merchant {
	return predicate.Merchant(sql.FieldNotIn(FieldKeytype, vs...))
}

// KeytypeGT applies the GT predicate on the "keytype" field.
func KeytypeGT(v int) predicate.Merchant {
	return predicate.Merchant(sql.FieldGT(FieldKeytype, v))
}

// KeytypeGTE applies the GTE predicate on the "keytype" field.
func KeytypeGTE(v int) predicate.Merchant {
	return predicate.Merchant(sql.FieldGTE(FieldKeytype, v))
}

// KeytypeLT applies the LT predicate on the "keytype" field.
func KeytypeLT(v int) predicate.Merchant {
	return predicate.Merchant(sql.FieldLT(FieldKeytype, v))
}

// KeytypeLTE applies the LTE predicate on the "keytype" field.
func KeytypeLTE(v int) predicate.Merchant {
	return predicate.Merchant(sql.FieldLTE(FieldKeytype, v))
}

// PublicKeyEQ applies the EQ predicate on the "public_key" field.
func PublicKeyEQ(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldEQ(FieldPublicKey, v))
}

// PublicKeyNEQ applies the NEQ predicate on the "public_key" field.
func PublicKeyNEQ(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldNEQ(FieldPublicKey, v))
}

// PublicKeyIn applies the In predicate on the "public_key" field.
func PublicKeyIn(vs ...string) predicate.Merchant {
	return predicate.Merchant(sql.FieldIn(FieldPublicKey, vs...))
}

// PublicKeyNotIn applies the NotIn predicate on the "public_key" field.
func PublicKeyNotIn(vs ...string) predicate.Merchant {
	return predicate.Merchant(sql.FieldNotIn(FieldPublicKey, vs...))
}

// PublicKeyGT applies the GT predicate on the "public_key" field.
func PublicKeyGT(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldGT(FieldPublicKey, v))
}

// PublicKeyGTE applies the GTE predicate on the "public_key" field.
func PublicKeyGTE(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldGTE(FieldPublicKey, v))
}

// PublicKeyLT applies the LT predicate on the "public_key" field.
func PublicKeyLT(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldLT(FieldPublicKey, v))
}

// PublicKeyLTE applies the LTE predicate on the "public_key" field.
func PublicKeyLTE(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldLTE(FieldPublicKey, v))
}

// PublicKeyContains applies the Contains predicate on the "public_key" field.
func PublicKeyContains(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldContains(FieldPublicKey, v))
}

// PublicKeyHasPrefix applies the HasPrefix predicate on the "public_key" field.
func PublicKeyHasPrefix(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldHasPrefix(FieldPublicKey, v))
}

// PublicKeyHasSuffix applies the HasSuffix predicate on the "public_key" field.
func PublicKeyHasSuffix(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldHasSuffix(FieldPublicKey, v))
}

// PublicKeyIsNil applies the IsNil predicate on the "public_key" field.
func PublicKeyIsNil() predicate.Merchant {
	return predicate.Merchant(sql.FieldIsNull(FieldPublicKey))
}

// PublicKeyNotNil applies the NotNil predicate on the "public_key" field.
func PublicKeyNotNil() predicate.Merchant {
	return predicate.Merchant(sql.FieldNotNull(FieldPublicKey))
}

// PublicKeyEqualFold applies the EqualFold predicate on the "public_key" field.
func PublicKeyEqualFold(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldEqualFold(FieldPublicKey, v))
}

// PublicKeyContainsFold applies the ContainsFold predicate on the "public_key" field.
func PublicKeyContainsFold(v string) predicate.Merchant {
	return predicate.Merchant(sql.FieldContainsFold(FieldPublicKey, v))
}

// RefundEnabledEQ applies the EQ predicate on the "refund_enabled" field.
func RefundEnabledEQ(v bool) predicate.Merchant {
	return predicate.Merchant(sql.FieldEQ(FieldRefundEnabled, v))
}

// RefundEnabledNEQ applies the NEQ predicate on the "refund_enabled" field.
func RefundEnabledNEQ(v bool) predicate.Merchant {
	return predicate.Merchant(sql.FieldNEQ(FieldRefundEnabled, v))
}

// TransferEnabledEQ applies the EQ predicate on the "transfer_enabled" field.
func TransferEnabledEQ(v bool) predicate.Merchant {
	return predicate.Merchant(sql.FieldEQ(FieldTransferEnabled, v))
}

// TransferEnabledNEQ applies the NEQ predicate on the "transfer_enabled" field.
func TransferEnabledNEQ(v bool) predicate.Merchant {
	return predicate.Merchant(sql.FieldNEQ(FieldTransferEnabled, v))
}

// ModeEQ applies the EQ predicate on the "mode" field.
func ModeEQ(v int) predicate.Merchant {
	return predicate.Merchant(sql.FieldEQ(FieldMode, v))
}

// ModeNEQ applies the NEQ predicate on the "mode" field.
func ModeNEQ(v int) predicate.Merchant {
	return predicate.Merchant(sql.FieldNEQ(FieldMode, v))
}

// ModeIn applies the In predicate on the "mode" field.
func ModeIn(vs ...int) predicate.Merchant {
	return predicate.Merchant(sql.FieldIn(FieldMode, vs...))
}

// ModeNotIn applies the NotIn predicate on the "mode" field.
func ModeNotIn(vs ...int) predicate.Merchant {
	return predicate.Merchant(sql.FieldNotIn(FieldMode, vs...))
}

// ModeGT applies the GT predicate on the "mode" field.
func ModeGT(v int) predicate.Merchant {
	return predicate.Merchant(sql.FieldGT(FieldMode, v))
}

// ModeGTE applies the GTE predicate on the "mode" field.
func ModeGTE(v int) predicate.Merchant {
	return predicate.Merchant(sql.FieldGTE(FieldMode, v))
}

// ModeLT applies the LT predicate on the "mode" field.
func ModeLT(v int) predicate.Merchant {
	return predicate.Merchant(sql.FieldLT(FieldMode, v))
}

// ModeLTE applies the LTE predicate on the "mode" field.
func ModeLTE(v int) predicate.Merchant {
	return predicate.Merchant(sql.FieldLTE(FieldMode, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Merchant {
	return predicate.Merchant(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Merchant {
	return predicate.Merchant(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Merchant {
	return predicate.Merchant(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Merchant {
	return predicate.Merchant(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Merchant {
	return predicate.Merchant(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Merchant {
	return predicate.Merchant(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Merchant {
	return predicate.Merchant(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Merchant {
	return predicate.Merchant(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Merchant {
	return predicate.Merchant(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Merchant {
	return predicate.Merchant(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Merchant {
	return predicate.Merchant(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Merchant {
	return predicate.Merchant(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Merchant {
	return predicate.Merchant(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Merchant {
	return predicate.Merchant(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Merchant {
	return predicate.Merchant(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Merchant {
	return predicate.Merchant(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasOrders applies the HasEdge predicate on the "orders" edge.
func HasOrders() predicate.Merchant {
	return predicate.Merchant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OrdersTable, OrdersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrdersWith applies the HasEdge predicate on the "orders" edge with a given conditions (other predicates).
func HasOrdersWith(preds ...predicate.Order) predicate.Merchant {
	return predicate.Merchant(func(s *sql.Selector) {
		step := newOrdersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSettlements applies the HasEdge predicate on the "settlements" edge.
func HasSettlements() predicate.Merchant {
	return predicate.Merchant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SettlementsTable, SettlementsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSettlementsWith applies the HasEdge predicate on the "settlements" edge with a given conditions (other predicates).
func HasSettlementsWith(preds ...predicate.Settlement) predicate.Merchant {
	return predicate.Merchant(func(s *sql.Selector) {
		step := newSettlementsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasWithdraws applies the HasEdge predicate on the "withdraws" edge.
func HasWithdraws() predicate.Merchant {
	return predicate.Merchant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, WithdrawsTable, WithdrawsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWithdrawsWith applies the HasEdge predicate on the "withdraws" edge with a given conditions (other predicates).
func HasWithdrawsWith(preds ...predicate.Withdraw) predicate.Merchant {
	return predicate.Merchant(func(s *sql.Selector) {
		step := newWithdrawsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRefunds applies the HasEdge predicate on the "refunds" edge.
func HasRefunds() predicate.Merchant {
	return predicate.Merchant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RefundsTable, RefundsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRefundsWith applies the HasEdge predicate on the "refunds" edge with a given conditions (other predicates).
func HasRefundsWith(preds ...predicate.Refund) predicate.Merchant {
	return predicate.Merchant(func(s *sql.Selector) {
		step := newRefundsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Merchant) predicate.Merchant {
	return predicate.Merchant(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Merchant) predicate.Merchant {
	return predicate.Merchant(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Merchant) predicate.Merchant {
	return predicate.Merchant(sql.NotPredicates(p))
}
