// Code generated by ent, DO NOT EDIT.

package order

import (
	"epay/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldID, id))
}

// OrderNo applies equality check predicate on the "order_no" field. It's identical to OrderNoEQ.
func OrderNo(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldOrderNo, v))
}

// ProductID applies equality check predicate on the "product_id" field. It's identical to ProductIDEQ.
func ProductID(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldProductID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldUserID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldAmount, v))
}

// FeeOfficial applies equality check predicate on the "fee_official" field. It's identical to FeeOfficialEQ.
func FeeOfficial(v float64) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldFeeOfficial, v))
}

// FeePlatform applies equality check predicate on the "fee_platform" field. It's identical to FeePlatformEQ.
func FeePlatform(v float64) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldFeePlatform, v))
}

// NetAmount applies equality check predicate on the "net_amount" field. It's identical to NetAmountEQ.
func NetAmount(v float64) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldNetAmount, v))
}

// TradeNo applies equality check predicate on the "trade_no" field. It's identical to TradeNoEQ.
func TradeNo(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldTradeNo, v))
}

// NotifyURL applies equality check predicate on the "notify_url" field. It's identical to NotifyURLEQ.
func NotifyURL(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldNotifyURL, v))
}

// ProviderSnapshot applies equality check predicate on the "provider_snapshot" field. It's identical to ProviderSnapshotEQ.
func ProviderSnapshot(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldProviderSnapshot, v))
}

// PaidAt applies equality check predicate on the "paid_at" field. It's identical to PaidAtEQ.
func PaidAt(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldPaidAt, v))
}

// APITradeNo applies equality check predicate on the "api_trade_no" field. It's identical to APITradeNoEQ.
func APITradeNo(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldAPITradeNo, v))
}

// Buyer applies equality check predicate on the "buyer" field. It's identical to BuyerEQ.
func Buyer(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldBuyer, v))
}

// Param applies equality check predicate on the "param" field. It's identical to ParamEQ.
func Param(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldParam, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldName, v))
}

// Clientip applies equality check predicate on the "clientip" field. It's identical to ClientipEQ.
func Clientip(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldClientip, v))
}

// ReturnURL applies equality check predicate on the "return_url" field. It's identical to ReturnURLEQ.
func ReturnURL(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldReturnURL, v))
}

// Device applies equality check predicate on the "device" field. It's identical to DeviceEQ.
func Device(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldDevice, v))
}

// Method applies equality check predicate on the "method" field. It's identical to MethodEQ.
func Method(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldMethod, v))
}

// SubOpenid applies equality check predicate on the "sub_openid" field. It's identical to SubOpenidEQ.
func SubOpenid(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldSubOpenid, v))
}

// SubAppid applies equality check predicate on the "sub_appid" field. It's identical to SubAppidEQ.
func SubAppid(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldSubAppid, v))
}

// AuthCode applies equality check predicate on the "auth_code" field. It's identical to AuthCodeEQ.
func AuthCode(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldAuthCode, v))
}

// RefundMoney applies equality check predicate on the "refund_money" field. It's identical to RefundMoneyEQ.
func RefundMoney(v float64) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldRefundMoney, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldVersion, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrderNoEQ applies the EQ predicate on the "order_no" field.
func OrderNoEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldOrderNo, v))
}

// OrderNoNEQ applies the NEQ predicate on the "order_no" field.
func OrderNoNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldOrderNo, v))
}

// OrderNoIn applies the In predicate on the "order_no" field.
func OrderNoIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldOrderNo, vs...))
}

// OrderNoNotIn applies the NotIn predicate on the "order_no" field.
func OrderNoNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldOrderNo, vs...))
}

// OrderNoGT applies the GT predicate on the "order_no" field.
func OrderNoGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldOrderNo, v))
}

// OrderNoGTE applies the GTE predicate on the "order_no" field.
func OrderNoGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldOrderNo, v))
}

// OrderNoLT applies the LT predicate on the "order_no" field.
func OrderNoLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldOrderNo, v))
}

// OrderNoLTE applies the LTE predicate on the "order_no" field.
func OrderNoLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldOrderNo, v))
}

// OrderNoContains applies the Contains predicate on the "order_no" field.
func OrderNoContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldOrderNo, v))
}

// OrderNoHasPrefix applies the HasPrefix predicate on the "order_no" field.
func OrderNoHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldOrderNo, v))
}

// OrderNoHasSuffix applies the HasSuffix predicate on the "order_no" field.
func OrderNoHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldOrderNo, v))
}

// OrderNoEqualFold applies the EqualFold predicate on the "order_no" field.
func OrderNoEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldOrderNo, v))
}

// OrderNoContainsFold applies the ContainsFold predicate on the "order_no" field.
func OrderNoContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldOrderNo, v))
}

// ProductIDEQ applies the EQ predicate on the "product_id" field.
func ProductIDEQ(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldProductID, v))
}

// ProductIDNEQ applies the NEQ predicate on the "product_id" field.
func ProductIDNEQ(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldProductID, v))
}

// ProductIDIn applies the In predicate on the "product_id" field.
func ProductIDIn(vs ...uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldProductID, vs...))
}

// ProductIDNotIn applies the NotIn predicate on the "product_id" field.
func ProductIDNotIn(vs ...uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldProductID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldUserID, vs...))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldType, vs...))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldAmount, v))
}

// FeeOfficialEQ applies the EQ predicate on the "fee_official" field.
func FeeOfficialEQ(v float64) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldFeeOfficial, v))
}

// FeeOfficialNEQ applies the NEQ predicate on the "fee_official" field.
func FeeOfficialNEQ(v float64) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldFeeOfficial, v))
}

// FeeOfficialIn applies the In predicate on the "fee_official" field.
func FeeOfficialIn(vs ...float64) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldFeeOfficial, vs...))
}

// FeeOfficialNotIn applies the NotIn predicate on the "fee_official" field.
func FeeOfficialNotIn(vs ...float64) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldFeeOfficial, vs...))
}

// FeeOfficialGT applies the GT predicate on the "fee_official" field.
func FeeOfficialGT(v float64) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldFeeOfficial, v))
}

// FeeOfficialGTE applies the GTE predicate on the "fee_official" field.
func FeeOfficialGTE(v float64) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldFeeOfficial, v))
}

// FeeOfficialLT applies the LT predicate on the "fee_official" field.
func FeeOfficialLT(v float64) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldFeeOfficial, v))
}

// FeeOfficialLTE applies the LTE predicate on the "fee_official" field.
func FeeOfficialLTE(v float64) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldFeeOfficial, v))
}

// FeePlatformEQ applies the EQ predicate on the "fee_platform" field.
func FeePlatformEQ(v float64) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldFeePlatform, v))
}

// FeePlatformNEQ applies the NEQ predicate on the "fee_platform" field.
func FeePlatformNEQ(v float64) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldFeePlatform, v))
}

// FeePlatformIn applies the In predicate on the "fee_platform" field.
func FeePlatformIn(vs ...float64) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldFeePlatform, vs...))
}

// FeePlatformNotIn applies the NotIn predicate on the "fee_platform" field.
func FeePlatformNotIn(vs ...float64) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldFeePlatform, vs...))
}

// FeePlatformGT applies the GT predicate on the "fee_platform" field.
func FeePlatformGT(v float64) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldFeePlatform, v))
}

// FeePlatformGTE applies the GTE predicate on the "fee_platform" field.
func FeePlatformGTE(v float64) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldFeePlatform, v))
}

// FeePlatformLT applies the LT predicate on the "fee_platform" field.
func FeePlatformLT(v float64) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldFeePlatform, v))
}

// FeePlatformLTE applies the LTE predicate on the "fee_platform" field.
func FeePlatformLTE(v float64) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldFeePlatform, v))
}

// NetAmountEQ applies the EQ predicate on the "net_amount" field.
func NetAmountEQ(v float64) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldNetAmount, v))
}

// NetAmountNEQ applies the NEQ predicate on the "net_amount" field.
func NetAmountNEQ(v float64) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldNetAmount, v))
}

// NetAmountIn applies the In predicate on the "net_amount" field.
func NetAmountIn(vs ...float64) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldNetAmount, vs...))
}

// NetAmountNotIn applies the NotIn predicate on the "net_amount" field.
func NetAmountNotIn(vs ...float64) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldNetAmount, vs...))
}

// NetAmountGT applies the GT predicate on the "net_amount" field.
func NetAmountGT(v float64) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldNetAmount, v))
}

// NetAmountGTE applies the GTE predicate on the "net_amount" field.
func NetAmountGTE(v float64) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldNetAmount, v))
}

// NetAmountLT applies the LT predicate on the "net_amount" field.
func NetAmountLT(v float64) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldNetAmount, v))
}

// NetAmountLTE applies the LTE predicate on the "net_amount" field.
func NetAmountLTE(v float64) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldNetAmount, v))
}

// TradeNoEQ applies the EQ predicate on the "trade_no" field.
func TradeNoEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldTradeNo, v))
}

// TradeNoNEQ applies the NEQ predicate on the "trade_no" field.
func TradeNoNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldTradeNo, v))
}

// TradeNoIn applies the In predicate on the "trade_no" field.
func TradeNoIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldTradeNo, vs...))
}

// TradeNoNotIn applies the NotIn predicate on the "trade_no" field.
func TradeNoNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldTradeNo, vs...))
}

// TradeNoGT applies the GT predicate on the "trade_no" field.
func TradeNoGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldTradeNo, v))
}

// TradeNoGTE applies the GTE predicate on the "trade_no" field.
func TradeNoGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldTradeNo, v))
}

// TradeNoLT applies the LT predicate on the "trade_no" field.
func TradeNoLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldTradeNo, v))
}

// TradeNoLTE applies the LTE predicate on the "trade_no" field.
func TradeNoLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldTradeNo, v))
}

// TradeNoContains applies the Contains predicate on the "trade_no" field.
func TradeNoContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldTradeNo, v))
}

// TradeNoHasPrefix applies the HasPrefix predicate on the "trade_no" field.
func TradeNoHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldTradeNo, v))
}

// TradeNoHasSuffix applies the HasSuffix predicate on the "trade_no" field.
func TradeNoHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldTradeNo, v))
}

// TradeNoIsNil applies the IsNil predicate on the "trade_no" field.
func TradeNoIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldTradeNo))
}

// TradeNoNotNil applies the NotNil predicate on the "trade_no" field.
func TradeNoNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldTradeNo))
}

// TradeNoEqualFold applies the EqualFold predicate on the "trade_no" field.
func TradeNoEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldTradeNo, v))
}

// TradeNoContainsFold applies the ContainsFold predicate on the "trade_no" field.
func TradeNoContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldTradeNo, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldStatus, vs...))
}

// NotifyURLEQ applies the EQ predicate on the "notify_url" field.
func NotifyURLEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldNotifyURL, v))
}

// NotifyURLNEQ applies the NEQ predicate on the "notify_url" field.
func NotifyURLNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldNotifyURL, v))
}

// NotifyURLIn applies the In predicate on the "notify_url" field.
func NotifyURLIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldNotifyURL, vs...))
}

// NotifyURLNotIn applies the NotIn predicate on the "notify_url" field.
func NotifyURLNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldNotifyURL, vs...))
}

// NotifyURLGT applies the GT predicate on the "notify_url" field.
func NotifyURLGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldNotifyURL, v))
}

// NotifyURLGTE applies the GTE predicate on the "notify_url" field.
func NotifyURLGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldNotifyURL, v))
}

// NotifyURLLT applies the LT predicate on the "notify_url" field.
func NotifyURLLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldNotifyURL, v))
}

// NotifyURLLTE applies the LTE predicate on the "notify_url" field.
func NotifyURLLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldNotifyURL, v))
}

// NotifyURLContains applies the Contains predicate on the "notify_url" field.
func NotifyURLContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldNotifyURL, v))
}

// NotifyURLHasPrefix applies the HasPrefix predicate on the "notify_url" field.
func NotifyURLHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldNotifyURL, v))
}

// NotifyURLHasSuffix applies the HasSuffix predicate on the "notify_url" field.
func NotifyURLHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldNotifyURL, v))
}

// NotifyURLEqualFold applies the EqualFold predicate on the "notify_url" field.
func NotifyURLEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldNotifyURL, v))
}

// NotifyURLContainsFold applies the ContainsFold predicate on the "notify_url" field.
func NotifyURLContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldNotifyURL, v))
}

// ProviderSnapshotEQ applies the EQ predicate on the "provider_snapshot" field.
func ProviderSnapshotEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldProviderSnapshot, v))
}

// ProviderSnapshotNEQ applies the NEQ predicate on the "provider_snapshot" field.
func ProviderSnapshotNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldProviderSnapshot, v))
}

// ProviderSnapshotIn applies the In predicate on the "provider_snapshot" field.
func ProviderSnapshotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldProviderSnapshot, vs...))
}

// ProviderSnapshotNotIn applies the NotIn predicate on the "provider_snapshot" field.
func ProviderSnapshotNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldProviderSnapshot, vs...))
}

// ProviderSnapshotGT applies the GT predicate on the "provider_snapshot" field.
func ProviderSnapshotGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldProviderSnapshot, v))
}

// ProviderSnapshotGTE applies the GTE predicate on the "provider_snapshot" field.
func ProviderSnapshotGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldProviderSnapshot, v))
}

// ProviderSnapshotLT applies the LT predicate on the "provider_snapshot" field.
func ProviderSnapshotLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldProviderSnapshot, v))
}

// ProviderSnapshotLTE applies the LTE predicate on the "provider_snapshot" field.
func ProviderSnapshotLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldProviderSnapshot, v))
}

// ProviderSnapshotContains applies the Contains predicate on the "provider_snapshot" field.
func ProviderSnapshotContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldProviderSnapshot, v))
}

// ProviderSnapshotHasPrefix applies the HasPrefix predicate on the "provider_snapshot" field.
func ProviderSnapshotHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldProviderSnapshot, v))
}

// ProviderSnapshotHasSuffix applies the HasSuffix predicate on the "provider_snapshot" field.
func ProviderSnapshotHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldProviderSnapshot, v))
}

// ProviderSnapshotIsNil applies the IsNil predicate on the "provider_snapshot" field.
func ProviderSnapshotIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldProviderSnapshot))
}

// ProviderSnapshotNotNil applies the NotNil predicate on the "provider_snapshot" field.
func ProviderSnapshotNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldProviderSnapshot))
}

// ProviderSnapshotEqualFold applies the EqualFold predicate on the "provider_snapshot" field.
func ProviderSnapshotEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldProviderSnapshot, v))
}

// ProviderSnapshotContainsFold applies the ContainsFold predicate on the "provider_snapshot" field.
func ProviderSnapshotContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldProviderSnapshot, v))
}

// PaidAtEQ applies the EQ predicate on the "paid_at" field.
func PaidAtEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldPaidAt, v))
}

// PaidAtNEQ applies the NEQ predicate on the "paid_at" field.
func PaidAtNEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldPaidAt, v))
}

// PaidAtIn applies the In predicate on the "paid_at" field.
func PaidAtIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldPaidAt, vs...))
}

// PaidAtNotIn applies the NotIn predicate on the "paid_at" field.
func PaidAtNotIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldPaidAt, vs...))
}

// PaidAtGT applies the GT predicate on the "paid_at" field.
func PaidAtGT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldPaidAt, v))
}

// PaidAtGTE applies the GTE predicate on the "paid_at" field.
func PaidAtGTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldPaidAt, v))
}

// PaidAtLT applies the LT predicate on the "paid_at" field.
func PaidAtLT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldPaidAt, v))
}

// PaidAtLTE applies the LTE predicate on the "paid_at" field.
func PaidAtLTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldPaidAt, v))
}

// PaidAtIsNil applies the IsNil predicate on the "paid_at" field.
func PaidAtIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldPaidAt))
}

// PaidAtNotNil applies the NotNil predicate on the "paid_at" field.
func PaidAtNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldPaidAt))
}

// APITradeNoEQ applies the EQ predicate on the "api_trade_no" field.
func APITradeNoEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldAPITradeNo, v))
}

// APITradeNoNEQ applies the NEQ predicate on the "api_trade_no" field.
func APITradeNoNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldAPITradeNo, v))
}

// APITradeNoIn applies the In predicate on the "api_trade_no" field.
func APITradeNoIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldAPITradeNo, vs...))
}

// APITradeNoNotIn applies the NotIn predicate on the "api_trade_no" field.
func APITradeNoNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldAPITradeNo, vs...))
}

// APITradeNoGT applies the GT predicate on the "api_trade_no" field.
func APITradeNoGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldAPITradeNo, v))
}

// APITradeNoGTE applies the GTE predicate on the "api_trade_no" field.
func APITradeNoGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldAPITradeNo, v))
}

// APITradeNoLT applies the LT predicate on the "api_trade_no" field.
func APITradeNoLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldAPITradeNo, v))
}

// APITradeNoLTE applies the LTE predicate on the "api_trade_no" field.
func APITradeNoLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldAPITradeNo, v))
}

// APITradeNoContains applies the Contains predicate on the "api_trade_no" field.
func APITradeNoContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldAPITradeNo, v))
}

// APITradeNoHasPrefix applies the HasPrefix predicate on the "api_trade_no" field.
func APITradeNoHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldAPITradeNo, v))
}

// APITradeNoHasSuffix applies the HasSuffix predicate on the "api_trade_no" field.
func APITradeNoHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldAPITradeNo, v))
}

// APITradeNoIsNil applies the IsNil predicate on the "api_trade_no" field.
func APITradeNoIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldAPITradeNo))
}

// APITradeNoNotNil applies the NotNil predicate on the "api_trade_no" field.
func APITradeNoNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldAPITradeNo))
}

// APITradeNoEqualFold applies the EqualFold predicate on the "api_trade_no" field.
func APITradeNoEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldAPITradeNo, v))
}

// APITradeNoContainsFold applies the ContainsFold predicate on the "api_trade_no" field.
func APITradeNoContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldAPITradeNo, v))
}

// BuyerEQ applies the EQ predicate on the "buyer" field.
func BuyerEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldBuyer, v))
}

// BuyerNEQ applies the NEQ predicate on the "buyer" field.
func BuyerNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldBuyer, v))
}

// BuyerIn applies the In predicate on the "buyer" field.
func BuyerIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldBuyer, vs...))
}

// BuyerNotIn applies the NotIn predicate on the "buyer" field.
func BuyerNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldBuyer, vs...))
}

// BuyerGT applies the GT predicate on the "buyer" field.
func BuyerGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldBuyer, v))
}

// BuyerGTE applies the GTE predicate on the "buyer" field.
func BuyerGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldBuyer, v))
}

// BuyerLT applies the LT predicate on the "buyer" field.
func BuyerLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldBuyer, v))
}

// BuyerLTE applies the LTE predicate on the "buyer" field.
func BuyerLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldBuyer, v))
}

// BuyerContains applies the Contains predicate on the "buyer" field.
func BuyerContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldBuyer, v))
}

// BuyerHasPrefix applies the HasPrefix predicate on the "buyer" field.
func BuyerHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldBuyer, v))
}

// BuyerHasSuffix applies the HasSuffix predicate on the "buyer" field.
func BuyerHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldBuyer, v))
}

// BuyerIsNil applies the IsNil predicate on the "buyer" field.
func BuyerIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldBuyer))
}

// BuyerNotNil applies the NotNil predicate on the "buyer" field.
func BuyerNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldBuyer))
}

// BuyerEqualFold applies the EqualFold predicate on the "buyer" field.
func BuyerEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldBuyer, v))
}

// BuyerContainsFold applies the ContainsFold predicate on the "buyer" field.
func BuyerContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldBuyer, v))
}

// ParamEQ applies the EQ predicate on the "param" field.
func ParamEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldParam, v))
}

// ParamNEQ applies the NEQ predicate on the "param" field.
func ParamNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldParam, v))
}

// ParamIn applies the In predicate on the "param" field.
func ParamIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldParam, vs...))
}

// ParamNotIn applies the NotIn predicate on the "param" field.
func ParamNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldParam, vs...))
}

// ParamGT applies the GT predicate on the "param" field.
func ParamGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldParam, v))
}

// ParamGTE applies the GTE predicate on the "param" field.
func ParamGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldParam, v))
}

// ParamLT applies the LT predicate on the "param" field.
func ParamLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldParam, v))
}

// ParamLTE applies the LTE predicate on the "param" field.
func ParamLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldParam, v))
}

// ParamContains applies the Contains predicate on the "param" field.
func ParamContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldParam, v))
}

// ParamHasPrefix applies the HasPrefix predicate on the "param" field.
func ParamHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldParam, v))
}

// ParamHasSuffix applies the HasSuffix predicate on the "param" field.
func ParamHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldParam, v))
}

// ParamIsNil applies the IsNil predicate on the "param" field.
func ParamIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldParam))
}

// ParamNotNil applies the NotNil predicate on the "param" field.
func ParamNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldParam))
}

// ParamEqualFold applies the EqualFold predicate on the "param" field.
func ParamEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldParam, v))
}

// ParamContainsFold applies the ContainsFold predicate on the "param" field.
func ParamContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldParam, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldName, v))
}

// ClientipEQ applies the EQ predicate on the "clientip" field.
func ClientipEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldClientip, v))
}

// ClientipNEQ applies the NEQ predicate on the "clientip" field.
func ClientipNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldClientip, v))
}

// ClientipIn applies the In predicate on the "clientip" field.
func ClientipIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldClientip, vs...))
}

// ClientipNotIn applies the NotIn predicate on the "clientip" field.
func ClientipNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldClientip, vs...))
}

// ClientipGT applies the GT predicate on the "clientip" field.
func ClientipGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldClientip, v))
}

// ClientipGTE applies the GTE predicate on the "clientip" field.
func ClientipGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldClientip, v))
}

// ClientipLT applies the LT predicate on the "clientip" field.
func ClientipLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldClientip, v))
}

// ClientipLTE applies the LTE predicate on the "clientip" field.
func ClientipLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldClientip, v))
}

// ClientipContains applies the Contains predicate on the "clientip" field.
func ClientipContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldClientip, v))
}

// ClientipHasPrefix applies the HasPrefix predicate on the "clientip" field.
func ClientipHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldClientip, v))
}

// ClientipHasSuffix applies the HasSuffix predicate on the "clientip" field.
func ClientipHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldClientip, v))
}

// ClientipIsNil applies the IsNil predicate on the "clientip" field.
func ClientipIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldClientip))
}

// ClientipNotNil applies the NotNil predicate on the "clientip" field.
func ClientipNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldClientip))
}

// ClientipEqualFold applies the EqualFold predicate on the "clientip" field.
func ClientipEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldClientip, v))
}

// ClientipContainsFold applies the ContainsFold predicate on the "clientip" field.
func ClientipContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldClientip, v))
}

// ReturnURLEQ applies the EQ predicate on the "return_url" field.
func ReturnURLEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldReturnURL, v))
}

// ReturnURLNEQ applies the NEQ predicate on the "return_url" field.
func ReturnURLNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldReturnURL, v))
}

// ReturnURLIn applies the In predicate on the "return_url" field.
func ReturnURLIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldReturnURL, vs...))
}

// ReturnURLNotIn applies the NotIn predicate on the "return_url" field.
func ReturnURLNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldReturnURL, vs...))
}

// ReturnURLGT applies the GT predicate on the "return_url" field.
func ReturnURLGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldReturnURL, v))
}

// ReturnURLGTE applies the GTE predicate on the "return_url" field.
func ReturnURLGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldReturnURL, v))
}

// ReturnURLLT applies the LT predicate on the "return_url" field.
func ReturnURLLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldReturnURL, v))
}

// ReturnURLLTE applies the LTE predicate on the "return_url" field.
func ReturnURLLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldReturnURL, v))
}

// ReturnURLContains applies the Contains predicate on the "return_url" field.
func ReturnURLContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldReturnURL, v))
}

// ReturnURLHasPrefix applies the HasPrefix predicate on the "return_url" field.
func ReturnURLHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldReturnURL, v))
}

// ReturnURLHasSuffix applies the HasSuffix predicate on the "return_url" field.
func ReturnURLHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldReturnURL, v))
}

// ReturnURLIsNil applies the IsNil predicate on the "return_url" field.
func ReturnURLIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldReturnURL))
}

// ReturnURLNotNil applies the NotNil predicate on the "return_url" field.
func ReturnURLNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldReturnURL))
}

// ReturnURLEqualFold applies the EqualFold predicate on the "return_url" field.
func ReturnURLEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldReturnURL, v))
}

// ReturnURLContainsFold applies the ContainsFold predicate on the "return_url" field.
func ReturnURLContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldReturnURL, v))
}

// DeviceEQ applies the EQ predicate on the "device" field.
func DeviceEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldDevice, v))
}

// DeviceNEQ applies the NEQ predicate on the "device" field.
func DeviceNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldDevice, v))
}

// DeviceIn applies the In predicate on the "device" field.
func DeviceIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldDevice, vs...))
}

// DeviceNotIn applies the NotIn predicate on the "device" field.
func DeviceNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldDevice, vs...))
}

// DeviceGT applies the GT predicate on the "device" field.
func DeviceGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldDevice, v))
}

// DeviceGTE applies the GTE predicate on the "device" field.
func DeviceGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldDevice, v))
}

// DeviceLT applies the LT predicate on the "device" field.
func DeviceLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldDevice, v))
}

// DeviceLTE applies the LTE predicate on the "device" field.
func DeviceLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldDevice, v))
}

// DeviceContains applies the Contains predicate on the "device" field.
func DeviceContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldDevice, v))
}

// DeviceHasPrefix applies the HasPrefix predicate on the "device" field.
func DeviceHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldDevice, v))
}

// DeviceHasSuffix applies the HasSuffix predicate on the "device" field.
func DeviceHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldDevice, v))
}

// DeviceIsNil applies the IsNil predicate on the "device" field.
func DeviceIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldDevice))
}

// DeviceNotNil applies the NotNil predicate on the "device" field.
func DeviceNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldDevice))
}

// DeviceEqualFold applies the EqualFold predicate on the "device" field.
func DeviceEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldDevice, v))
}

// DeviceContainsFold applies the ContainsFold predicate on the "device" field.
func DeviceContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldDevice, v))
}

// MethodEQ applies the EQ predicate on the "method" field.
func MethodEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldMethod, v))
}

// MethodNEQ applies the NEQ predicate on the "method" field.
func MethodNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldMethod, v))
}

// MethodIn applies the In predicate on the "method" field.
func MethodIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldMethod, vs...))
}

// MethodNotIn applies the NotIn predicate on the "method" field.
func MethodNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldMethod, vs...))
}

// MethodGT applies the GT predicate on the "method" field.
func MethodGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldMethod, v))
}

// MethodGTE applies the GTE predicate on the "method" field.
func MethodGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldMethod, v))
}

// MethodLT applies the LT predicate on the "method" field.
func MethodLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldMethod, v))
}

// MethodLTE applies the LTE predicate on the "method" field.
func MethodLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldMethod, v))
}

// MethodContains applies the Contains predicate on the "method" field.
func MethodContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldMethod, v))
}

// MethodHasPrefix applies the HasPrefix predicate on the "method" field.
func MethodHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldMethod, v))
}

// MethodHasSuffix applies the HasSuffix predicate on the "method" field.
func MethodHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldMethod, v))
}

// MethodIsNil applies the IsNil predicate on the "method" field.
func MethodIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldMethod))
}

// MethodNotNil applies the NotNil predicate on the "method" field.
func MethodNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldMethod))
}

// MethodEqualFold applies the EqualFold predicate on the "method" field.
func MethodEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldMethod, v))
}

// MethodContainsFold applies the ContainsFold predicate on the "method" field.
func MethodContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldMethod, v))
}

// SubOpenidEQ applies the EQ predicate on the "sub_openid" field.
func SubOpenidEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldSubOpenid, v))
}

// SubOpenidNEQ applies the NEQ predicate on the "sub_openid" field.
func SubOpenidNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldSubOpenid, v))
}

// SubOpenidIn applies the In predicate on the "sub_openid" field.
func SubOpenidIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldSubOpenid, vs...))
}

// SubOpenidNotIn applies the NotIn predicate on the "sub_openid" field.
func SubOpenidNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldSubOpenid, vs...))
}

// SubOpenidGT applies the GT predicate on the "sub_openid" field.
func SubOpenidGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldSubOpenid, v))
}

// SubOpenidGTE applies the GTE predicate on the "sub_openid" field.
func SubOpenidGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldSubOpenid, v))
}

// SubOpenidLT applies the LT predicate on the "sub_openid" field.
func SubOpenidLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldSubOpenid, v))
}

// SubOpenidLTE applies the LTE predicate on the "sub_openid" field.
func SubOpenidLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldSubOpenid, v))
}

// SubOpenidContains applies the Contains predicate on the "sub_openid" field.
func SubOpenidContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldSubOpenid, v))
}

// SubOpenidHasPrefix applies the HasPrefix predicate on the "sub_openid" field.
func SubOpenidHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldSubOpenid, v))
}

// SubOpenidHasSuffix applies the HasSuffix predicate on the "sub_openid" field.
func SubOpenidHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldSubOpenid, v))
}

// SubOpenidIsNil applies the IsNil predicate on the "sub_openid" field.
func SubOpenidIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldSubOpenid))
}

// SubOpenidNotNil applies the NotNil predicate on the "sub_openid" field.
func SubOpenidNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldSubOpenid))
}

// SubOpenidEqualFold applies the EqualFold predicate on the "sub_openid" field.
func SubOpenidEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldSubOpenid, v))
}

// SubOpenidContainsFold applies the ContainsFold predicate on the "sub_openid" field.
func SubOpenidContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldSubOpenid, v))
}

// SubAppidEQ applies the EQ predicate on the "sub_appid" field.
func SubAppidEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldSubAppid, v))
}

// SubAppidNEQ applies the NEQ predicate on the "sub_appid" field.
func SubAppidNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldSubAppid, v))
}

// SubAppidIn applies the In predicate on the "sub_appid" field.
func SubAppidIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldSubAppid, vs...))
}

// SubAppidNotIn applies the NotIn predicate on the "sub_appid" field.
func SubAppidNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldSubAppid, vs...))
}

// SubAppidGT applies the GT predicate on the "sub_appid" field.
func SubAppidGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldSubAppid, v))
}

// SubAppidGTE applies the GTE predicate on the "sub_appid" field.
func SubAppidGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldSubAppid, v))
}

// SubAppidLT applies the LT predicate on the "sub_appid" field.
func SubAppidLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldSubAppid, v))
}

// SubAppidLTE applies the LTE predicate on the "sub_appid" field.
func SubAppidLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldSubAppid, v))
}

// SubAppidContains applies the Contains predicate on the "sub_appid" field.
func SubAppidContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldSubAppid, v))
}

// SubAppidHasPrefix applies the HasPrefix predicate on the "sub_appid" field.
func SubAppidHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldSubAppid, v))
}

// SubAppidHasSuffix applies the HasSuffix predicate on the "sub_appid" field.
func SubAppidHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldSubAppid, v))
}

// SubAppidIsNil applies the IsNil predicate on the "sub_appid" field.
func SubAppidIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldSubAppid))
}

// SubAppidNotNil applies the NotNil predicate on the "sub_appid" field.
func SubAppidNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldSubAppid))
}

// SubAppidEqualFold applies the EqualFold predicate on the "sub_appid" field.
func SubAppidEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldSubAppid, v))
}

// SubAppidContainsFold applies the ContainsFold predicate on the "sub_appid" field.
func SubAppidContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldSubAppid, v))
}

// AuthCodeEQ applies the EQ predicate on the "auth_code" field.
func AuthCodeEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldAuthCode, v))
}

// AuthCodeNEQ applies the NEQ predicate on the "auth_code" field.
func AuthCodeNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldAuthCode, v))
}

// AuthCodeIn applies the In predicate on the "auth_code" field.
func AuthCodeIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldAuthCode, vs...))
}

// AuthCodeNotIn applies the NotIn predicate on the "auth_code" field.
func AuthCodeNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldAuthCode, vs...))
}

// AuthCodeGT applies the GT predicate on the "auth_code" field.
func AuthCodeGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldAuthCode, v))
}

// AuthCodeGTE applies the GTE predicate on the "auth_code" field.
func AuthCodeGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldAuthCode, v))
}

// AuthCodeLT applies the LT predicate on the "auth_code" field.
func AuthCodeLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldAuthCode, v))
}

// AuthCodeLTE applies the LTE predicate on the "auth_code" field.
func AuthCodeLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldAuthCode, v))
}

// AuthCodeContains applies the Contains predicate on the "auth_code" field.
func AuthCodeContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldAuthCode, v))
}

// AuthCodeHasPrefix applies the HasPrefix predicate on the "auth_code" field.
func AuthCodeHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldAuthCode, v))
}

// AuthCodeHasSuffix applies the HasSuffix predicate on the "auth_code" field.
func AuthCodeHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldAuthCode, v))
}

// AuthCodeIsNil applies the IsNil predicate on the "auth_code" field.
func AuthCodeIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldAuthCode))
}

// AuthCodeNotNil applies the NotNil predicate on the "auth_code" field.
func AuthCodeNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldAuthCode))
}

// AuthCodeEqualFold applies the EqualFold predicate on the "auth_code" field.
func AuthCodeEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldAuthCode, v))
}

// AuthCodeContainsFold applies the ContainsFold predicate on the "auth_code" field.
func AuthCodeContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldAuthCode, v))
}

// RefundMoneyEQ applies the EQ predicate on the "refund_money" field.
func RefundMoneyEQ(v float64) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldRefundMoney, v))
}

// RefundMoneyNEQ applies the NEQ predicate on the "refund_money" field.
func RefundMoneyNEQ(v float64) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldRefundMoney, v))
}

// RefundMoneyIn applies the In predicate on the "refund_money" field.
func RefundMoneyIn(vs ...float64) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldRefundMoney, vs...))
}

// RefundMoneyNotIn applies the NotIn predicate on the "refund_money" field.
func RefundMoneyNotIn(vs ...float64) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldRefundMoney, vs...))
}

// RefundMoneyGT applies the GT predicate on the "refund_money" field.
func RefundMoneyGT(v float64) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldRefundMoney, v))
}

// RefundMoneyGTE applies the GTE predicate on the "refund_money" field.
func RefundMoneyGTE(v float64) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldRefundMoney, v))
}

// RefundMoneyLT applies the LT predicate on the "refund_money" field.
func RefundMoneyLT(v float64) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldRefundMoney, v))
}

// RefundMoneyLTE applies the LTE predicate on the "refund_money" field.
func RefundMoneyLTE(v float64) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldRefundMoney, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldVersion, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasProduct applies the HasEdge predicate on the "product" edge.
func HasProduct() predicate.Order {
	return predicate.Order(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProductTable, ProductColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProductWith applies the HasEdge predicate on the "product" edge with a given conditions (other predicates).
func HasProductWith(preds ...predicate.Product) predicate.Order {
	return predicate.Order(func(s *sql.Selector) {
		step := newProductStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Order {
	return predicate.Order(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Order {
	return predicate.Order(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Order) predicate.Order {
	return predicate.Order(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Order) predicate.Order {
	return predicate.Order(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Order) predicate.Order {
	return predicate.Order(sql.NotPredicates(p))
}
