// Code generated by ent, DO NOT EDIT.

package order

import (
	"epay/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldID, id))
}

// OrderNo applies equality check predicate on the "order_no" field. It's identical to OrderNoEQ.
func OrderNo(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldOrderNo, v))
}

// MerchantID applies equality check predicate on the "merchant_id" field. It's identical to MerchantIDEQ.
func MerchantID(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldMerchantID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldAmount, v))
}

// FeeOfficial applies equality check predicate on the "fee_official" field. It's identical to FeeOfficialEQ.
func FeeOfficial(v float64) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldFeeOfficial, v))
}

// FeePlatform applies equality check predicate on the "fee_platform" field. It's identical to FeePlatformEQ.
func FeePlatform(v float64) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldFeePlatform, v))
}

// NetAmount applies equality check predicate on the "net_amount" field. It's identical to NetAmountEQ.
func NetAmount(v float64) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldNetAmount, v))
}

// TradeNo applies equality check predicate on the "trade_no" field. It's identical to TradeNoEQ.
func TradeNo(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldTradeNo, v))
}

// NotifyURL applies equality check predicate on the "notify_url" field. It's identical to NotifyURLEQ.
func NotifyURL(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldNotifyURL, v))
}

// ProviderSnapshot applies equality check predicate on the "provider_snapshot" field. It's identical to ProviderSnapshotEQ.
func ProviderSnapshot(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldProviderSnapshot, v))
}

// PaidAt applies equality check predicate on the "paid_at" field. It's identical to PaidAtEQ.
func PaidAt(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldPaidAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrderNoEQ applies the EQ predicate on the "order_no" field.
func OrderNoEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldOrderNo, v))
}

// OrderNoNEQ applies the NEQ predicate on the "order_no" field.
func OrderNoNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldOrderNo, v))
}

// OrderNoIn applies the In predicate on the "order_no" field.
func OrderNoIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldOrderNo, vs...))
}

// OrderNoNotIn applies the NotIn predicate on the "order_no" field.
func OrderNoNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldOrderNo, vs...))
}

// OrderNoGT applies the GT predicate on the "order_no" field.
func OrderNoGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldOrderNo, v))
}

// OrderNoGTE applies the GTE predicate on the "order_no" field.
func OrderNoGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldOrderNo, v))
}

// OrderNoLT applies the LT predicate on the "order_no" field.
func OrderNoLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldOrderNo, v))
}

// OrderNoLTE applies the LTE predicate on the "order_no" field.
func OrderNoLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldOrderNo, v))
}

// OrderNoContains applies the Contains predicate on the "order_no" field.
func OrderNoContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldOrderNo, v))
}

// OrderNoHasPrefix applies the HasPrefix predicate on the "order_no" field.
func OrderNoHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldOrderNo, v))
}

// OrderNoHasSuffix applies the HasSuffix predicate on the "order_no" field.
func OrderNoHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldOrderNo, v))
}

// OrderNoEqualFold applies the EqualFold predicate on the "order_no" field.
func OrderNoEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldOrderNo, v))
}

// OrderNoContainsFold applies the ContainsFold predicate on the "order_no" field.
func OrderNoContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldOrderNo, v))
}

// MerchantIDEQ applies the EQ predicate on the "merchant_id" field.
func MerchantIDEQ(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldMerchantID, v))
}

// MerchantIDNEQ applies the NEQ predicate on the "merchant_id" field.
func MerchantIDNEQ(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldMerchantID, v))
}

// MerchantIDIn applies the In predicate on the "merchant_id" field.
func MerchantIDIn(vs ...uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldMerchantID, vs...))
}

// MerchantIDNotIn applies the NotIn predicate on the "merchant_id" field.
func MerchantIDNotIn(vs ...uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldMerchantID, vs...))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldType, vs...))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldAmount, v))
}

// FeeOfficialEQ applies the EQ predicate on the "fee_official" field.
func FeeOfficialEQ(v float64) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldFeeOfficial, v))
}

// FeeOfficialNEQ applies the NEQ predicate on the "fee_official" field.
func FeeOfficialNEQ(v float64) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldFeeOfficial, v))
}

// FeeOfficialIn applies the In predicate on the "fee_official" field.
func FeeOfficialIn(vs ...float64) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldFeeOfficial, vs...))
}

// FeeOfficialNotIn applies the NotIn predicate on the "fee_official" field.
func FeeOfficialNotIn(vs ...float64) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldFeeOfficial, vs...))
}

// FeeOfficialGT applies the GT predicate on the "fee_official" field.
func FeeOfficialGT(v float64) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldFeeOfficial, v))
}

// FeeOfficialGTE applies the GTE predicate on the "fee_official" field.
func FeeOfficialGTE(v float64) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldFeeOfficial, v))
}

// FeeOfficialLT applies the LT predicate on the "fee_official" field.
func FeeOfficialLT(v float64) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldFeeOfficial, v))
}

// FeeOfficialLTE applies the LTE predicate on the "fee_official" field.
func FeeOfficialLTE(v float64) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldFeeOfficial, v))
}

// FeePlatformEQ applies the EQ predicate on the "fee_platform" field.
func FeePlatformEQ(v float64) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldFeePlatform, v))
}

// FeePlatformNEQ applies the NEQ predicate on the "fee_platform" field.
func FeePlatformNEQ(v float64) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldFeePlatform, v))
}

// FeePlatformIn applies the In predicate on the "fee_platform" field.
func FeePlatformIn(vs ...float64) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldFeePlatform, vs...))
}

// FeePlatformNotIn applies the NotIn predicate on the "fee_platform" field.
func FeePlatformNotIn(vs ...float64) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldFeePlatform, vs...))
}

// FeePlatformGT applies the GT predicate on the "fee_platform" field.
func FeePlatformGT(v float64) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldFeePlatform, v))
}

// FeePlatformGTE applies the GTE predicate on the "fee_platform" field.
func FeePlatformGTE(v float64) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldFeePlatform, v))
}

// FeePlatformLT applies the LT predicate on the "fee_platform" field.
func FeePlatformLT(v float64) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldFeePlatform, v))
}

// FeePlatformLTE applies the LTE predicate on the "fee_platform" field.
func FeePlatformLTE(v float64) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldFeePlatform, v))
}

// NetAmountEQ applies the EQ predicate on the "net_amount" field.
func NetAmountEQ(v float64) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldNetAmount, v))
}

// NetAmountNEQ applies the NEQ predicate on the "net_amount" field.
func NetAmountNEQ(v float64) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldNetAmount, v))
}

// NetAmountIn applies the In predicate on the "net_amount" field.
func NetAmountIn(vs ...float64) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldNetAmount, vs...))
}

// NetAmountNotIn applies the NotIn predicate on the "net_amount" field.
func NetAmountNotIn(vs ...float64) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldNetAmount, vs...))
}

// NetAmountGT applies the GT predicate on the "net_amount" field.
func NetAmountGT(v float64) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldNetAmount, v))
}

// NetAmountGTE applies the GTE predicate on the "net_amount" field.
func NetAmountGTE(v float64) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldNetAmount, v))
}

// NetAmountLT applies the LT predicate on the "net_amount" field.
func NetAmountLT(v float64) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldNetAmount, v))
}

// NetAmountLTE applies the LTE predicate on the "net_amount" field.
func NetAmountLTE(v float64) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldNetAmount, v))
}

// TradeNoEQ applies the EQ predicate on the "trade_no" field.
func TradeNoEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldTradeNo, v))
}

// TradeNoNEQ applies the NEQ predicate on the "trade_no" field.
func TradeNoNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldTradeNo, v))
}

// TradeNoIn applies the In predicate on the "trade_no" field.
func TradeNoIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldTradeNo, vs...))
}

// TradeNoNotIn applies the NotIn predicate on the "trade_no" field.
func TradeNoNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldTradeNo, vs...))
}

// TradeNoGT applies the GT predicate on the "trade_no" field.
func TradeNoGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldTradeNo, v))
}

// TradeNoGTE applies the GTE predicate on the "trade_no" field.
func TradeNoGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldTradeNo, v))
}

// TradeNoLT applies the LT predicate on the "trade_no" field.
func TradeNoLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldTradeNo, v))
}

// TradeNoLTE applies the LTE predicate on the "trade_no" field.
func TradeNoLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldTradeNo, v))
}

// TradeNoContains applies the Contains predicate on the "trade_no" field.
func TradeNoContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldTradeNo, v))
}

// TradeNoHasPrefix applies the HasPrefix predicate on the "trade_no" field.
func TradeNoHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldTradeNo, v))
}

// TradeNoHasSuffix applies the HasSuffix predicate on the "trade_no" field.
func TradeNoHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldTradeNo, v))
}

// TradeNoIsNil applies the IsNil predicate on the "trade_no" field.
func TradeNoIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldTradeNo))
}

// TradeNoNotNil applies the NotNil predicate on the "trade_no" field.
func TradeNoNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldTradeNo))
}

// TradeNoEqualFold applies the EqualFold predicate on the "trade_no" field.
func TradeNoEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldTradeNo, v))
}

// TradeNoContainsFold applies the ContainsFold predicate on the "trade_no" field.
func TradeNoContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldTradeNo, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldStatus, vs...))
}

// NotifyURLEQ applies the EQ predicate on the "notify_url" field.
func NotifyURLEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldNotifyURL, v))
}

// NotifyURLNEQ applies the NEQ predicate on the "notify_url" field.
func NotifyURLNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldNotifyURL, v))
}

// NotifyURLIn applies the In predicate on the "notify_url" field.
func NotifyURLIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldNotifyURL, vs...))
}

// NotifyURLNotIn applies the NotIn predicate on the "notify_url" field.
func NotifyURLNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldNotifyURL, vs...))
}

// NotifyURLGT applies the GT predicate on the "notify_url" field.
func NotifyURLGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldNotifyURL, v))
}

// NotifyURLGTE applies the GTE predicate on the "notify_url" field.
func NotifyURLGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldNotifyURL, v))
}

// NotifyURLLT applies the LT predicate on the "notify_url" field.
func NotifyURLLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldNotifyURL, v))
}

// NotifyURLLTE applies the LTE predicate on the "notify_url" field.
func NotifyURLLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldNotifyURL, v))
}

// NotifyURLContains applies the Contains predicate on the "notify_url" field.
func NotifyURLContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldNotifyURL, v))
}

// NotifyURLHasPrefix applies the HasPrefix predicate on the "notify_url" field.
func NotifyURLHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldNotifyURL, v))
}

// NotifyURLHasSuffix applies the HasSuffix predicate on the "notify_url" field.
func NotifyURLHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldNotifyURL, v))
}

// NotifyURLEqualFold applies the EqualFold predicate on the "notify_url" field.
func NotifyURLEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldNotifyURL, v))
}

// NotifyURLContainsFold applies the ContainsFold predicate on the "notify_url" field.
func NotifyURLContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldNotifyURL, v))
}

// ProviderSnapshotEQ applies the EQ predicate on the "provider_snapshot" field.
func ProviderSnapshotEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldProviderSnapshot, v))
}

// ProviderSnapshotNEQ applies the NEQ predicate on the "provider_snapshot" field.
func ProviderSnapshotNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldProviderSnapshot, v))
}

// ProviderSnapshotIn applies the In predicate on the "provider_snapshot" field.
func ProviderSnapshotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldProviderSnapshot, vs...))
}

// ProviderSnapshotNotIn applies the NotIn predicate on the "provider_snapshot" field.
func ProviderSnapshotNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldProviderSnapshot, vs...))
}

// ProviderSnapshotGT applies the GT predicate on the "provider_snapshot" field.
func ProviderSnapshotGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldProviderSnapshot, v))
}

// ProviderSnapshotGTE applies the GTE predicate on the "provider_snapshot" field.
func ProviderSnapshotGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldProviderSnapshot, v))
}

// ProviderSnapshotLT applies the LT predicate on the "provider_snapshot" field.
func ProviderSnapshotLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldProviderSnapshot, v))
}

// ProviderSnapshotLTE applies the LTE predicate on the "provider_snapshot" field.
func ProviderSnapshotLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldProviderSnapshot, v))
}

// ProviderSnapshotContains applies the Contains predicate on the "provider_snapshot" field.
func ProviderSnapshotContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldProviderSnapshot, v))
}

// ProviderSnapshotHasPrefix applies the HasPrefix predicate on the "provider_snapshot" field.
func ProviderSnapshotHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldProviderSnapshot, v))
}

// ProviderSnapshotHasSuffix applies the HasSuffix predicate on the "provider_snapshot" field.
func ProviderSnapshotHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldProviderSnapshot, v))
}

// ProviderSnapshotIsNil applies the IsNil predicate on the "provider_snapshot" field.
func ProviderSnapshotIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldProviderSnapshot))
}

// ProviderSnapshotNotNil applies the NotNil predicate on the "provider_snapshot" field.
func ProviderSnapshotNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldProviderSnapshot))
}

// ProviderSnapshotEqualFold applies the EqualFold predicate on the "provider_snapshot" field.
func ProviderSnapshotEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldProviderSnapshot, v))
}

// ProviderSnapshotContainsFold applies the ContainsFold predicate on the "provider_snapshot" field.
func ProviderSnapshotContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldProviderSnapshot, v))
}

// PaidAtEQ applies the EQ predicate on the "paid_at" field.
func PaidAtEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldPaidAt, v))
}

// PaidAtNEQ applies the NEQ predicate on the "paid_at" field.
func PaidAtNEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldPaidAt, v))
}

// PaidAtIn applies the In predicate on the "paid_at" field.
func PaidAtIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldPaidAt, vs...))
}

// PaidAtNotIn applies the NotIn predicate on the "paid_at" field.
func PaidAtNotIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldPaidAt, vs...))
}

// PaidAtGT applies the GT predicate on the "paid_at" field.
func PaidAtGT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldPaidAt, v))
}

// PaidAtGTE applies the GTE predicate on the "paid_at" field.
func PaidAtGTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldPaidAt, v))
}

// PaidAtLT applies the LT predicate on the "paid_at" field.
func PaidAtLT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldPaidAt, v))
}

// PaidAtLTE applies the LTE predicate on the "paid_at" field.
func PaidAtLTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldPaidAt, v))
}

// PaidAtIsNil applies the IsNil predicate on the "paid_at" field.
func PaidAtIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldPaidAt))
}

// PaidAtNotNil applies the NotNil predicate on the "paid_at" field.
func PaidAtNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldPaidAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasMerchant applies the HasEdge predicate on the "merchant" edge.
func HasMerchant() predicate.Order {
	return predicate.Order(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MerchantTable, MerchantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMerchantWith applies the HasEdge predicate on the "merchant" edge with a given conditions (other predicates).
func HasMerchantWith(preds ...predicate.Merchant) predicate.Order {
	return predicate.Order(func(s *sql.Selector) {
		step := newMerchantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Order) predicate.Order {
	return predicate.Order(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Order) predicate.Order {
	return predicate.Order(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Order) predicate.Order {
	return predicate.Order(sql.NotPredicates(p))
}
