// Code generated by ent, DO NOT EDIT.

package product

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the product type in the database.
	Label = "product"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldPid holds the string denoting the pid field in the database.
	FieldPid = "pid"
	// FieldPkey holds the string denoting the pkey field in the database.
	FieldPkey = "pkey"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldNotifyURL holds the string denoting the notify_url field in the database.
	FieldNotifyURL = "notify_url"
	// FieldReturnURL holds the string denoting the return_url field in the database.
	FieldReturnURL = "return_url"
	// FieldFeeRate holds the string denoting the fee_rate field in the database.
	FieldFeeRate = "fee_rate"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldKeytype holds the string denoting the keytype field in the database.
	FieldKeytype = "keytype"
	// FieldPublicKey holds the string denoting the public_key field in the database.
	FieldPublicKey = "public_key"
	// FieldRefundEnabled holds the string denoting the refund_enabled field in the database.
	FieldRefundEnabled = "refund_enabled"
	// FieldTransferEnabled holds the string denoting the transfer_enabled field in the database.
	FieldTransferEnabled = "transfer_enabled"
	// FieldMode holds the string denoting the mode field in the database.
	FieldMode = "mode"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeOrders holds the string denoting the orders edge name in mutations.
	EdgeOrders = "orders"
	// Table holds the table name of the product in the database.
	Table = "products"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "products"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// OrdersTable is the table that holds the orders relation/edge.
	OrdersTable = "orders"
	// OrdersInverseTable is the table name for the Order entity.
	// It exists in this package in order to avoid circular dependency with the "order" package.
	OrdersInverseTable = "orders"
	// OrdersColumn is the table column denoting the orders relation/edge.
	OrdersColumn = "product_id"
)

// Columns holds all SQL columns for product fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldPid,
	FieldPkey,
	FieldName,
	FieldDescription,
	FieldNotifyURL,
	FieldReturnURL,
	FieldFeeRate,
	FieldStatus,
	FieldKeytype,
	FieldPublicKey,
	FieldRefundEnabled,
	FieldTransferEnabled,
	FieldMode,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PkeyValidator is a validator for the "pkey" field. It is called by the builders before save.
	PkeyValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultNotifyURL holds the default value on creation for the "notify_url" field.
	DefaultNotifyURL string
	// DefaultReturnURL holds the default value on creation for the "return_url" field.
	DefaultReturnURL string
	// DefaultKeytype holds the default value on creation for the "keytype" field.
	DefaultKeytype int
	// DefaultPublicKey holds the default value on creation for the "public_key" field.
	DefaultPublicKey string
	// DefaultRefundEnabled holds the default value on creation for the "refund_enabled" field.
	DefaultRefundEnabled bool
	// DefaultTransferEnabled holds the default value on creation for the "transfer_enabled" field.
	DefaultTransferEnabled bool
	// DefaultMode holds the default value on creation for the "mode" field.
	DefaultMode int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive   Status = "active"
	StatusDisabled Status = "disabled"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusDisabled:
		return nil
	default:
		return fmt.Errorf("product: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Product queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByPid orders the results by the pid field.
func ByPid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPid, opts...).ToFunc()
}

// ByPkey orders the results by the pkey field.
func ByPkey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPkey, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByNotifyURL orders the results by the notify_url field.
func ByNotifyURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotifyURL, opts...).ToFunc()
}

// ByReturnURL orders the results by the return_url field.
func ByReturnURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReturnURL, opts...).ToFunc()
}

// ByFeeRate orders the results by the fee_rate field.
func ByFeeRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeeRate, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByKeytype orders the results by the keytype field.
func ByKeytype(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeytype, opts...).ToFunc()
}

// ByPublicKey orders the results by the public_key field.
func ByPublicKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicKey, opts...).ToFunc()
}

// ByRefundEnabled orders the results by the refund_enabled field.
func ByRefundEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundEnabled, opts...).ToFunc()
}

// ByTransferEnabled orders the results by the transfer_enabled field.
func ByTransferEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTransferEnabled, opts...).ToFunc()
}

// ByMode orders the results by the mode field.
func ByMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMode, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByOrdersCount orders the results by orders count.
func ByOrdersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOrdersStep(), opts...)
	}
}

// ByOrders orders the results by orders terms.
func ByOrders(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrdersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newOrdersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrdersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OrdersTable, OrdersColumn),
	)
}
