// Code generated by ent, DO NOT EDIT.

package refund

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the refund type in the database.
	Label = "refund"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRefundNo holds the string denoting the refund_no field in the database.
	FieldRefundNo = "refund_no"
	// FieldOutRefundNo holds the string denoting the out_refund_no field in the database.
	FieldOutRefundNo = "out_refund_no"
	// FieldTradeNo holds the string denoting the trade_no field in the database.
	FieldTradeNo = "trade_no"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldMoney holds the string denoting the money field in the database.
	FieldMoney = "money"
	// FieldReduceMoney holds the string denoting the reduce_money field in the database.
	FieldReduceMoney = "reduce_money"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the refund in the database.
	Table = "refunds"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "refunds"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for refund fields.
var Columns = []string{
	FieldID,
	FieldRefundNo,
	FieldOutRefundNo,
	FieldTradeNo,
	FieldUserID,
	FieldMoney,
	FieldReduceMoney,
	FieldStatus,
	FieldMessage,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldFinishedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RefundNoValidator is a validator for the "refund_no" field. It is called by the builders before save.
	RefundNoValidator func(string) error
	// DefaultOutRefundNo holds the default value on creation for the "out_refund_no" field.
	DefaultOutRefundNo string
	// TradeNoValidator is a validator for the "trade_no" field. It is called by the builders before save.
	TradeNoValidator func(string) error
	// DefaultReduceMoney holds the default value on creation for the "reduce_money" field.
	DefaultReduceMoney float64
	// DefaultMessage holds the default value on creation for the "message" field.
	DefaultMessage string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPENDING is the default value of the Status enum.
const DefaultStatus = StatusPENDING

// Status values.
const (
	StatusPENDING Status = "PENDING"
	StatusSUCCESS Status = "SUCCESS"
	StatusFAILED  Status = "FAILED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPENDING, StatusSUCCESS, StatusFAILED:
		return nil
	default:
		return fmt.Errorf("refund: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Refund queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRefundNo orders the results by the refund_no field.
func ByRefundNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundNo, opts...).ToFunc()
}

// ByOutRefundNo orders the results by the out_refund_no field.
func ByOutRefundNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutRefundNo, opts...).ToFunc()
}

// ByTradeNo orders the results by the trade_no field.
func ByTradeNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTradeNo, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByMoney orders the results by the money field.
func ByMoney(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMoney, opts...).ToFunc()
}

// ByReduceMoney orders the results by the reduce_money field.
func ByReduceMoney(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReduceMoney, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByMessage orders the results by the message field.
func ByMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessage, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
