// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AdminsColumns holds the columns for the "admins" table.
	AdminsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AdminsTable holds the schema information for the "admins" table.
	AdminsTable = &schema.Table{
		Name:       "admins",
		Columns:    AdminsColumns,
		PrimaryKey: []*schema.Column{AdminsColumns[0]},
	}
	// OrdersColumns holds the columns for the "orders" table.
	OrdersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "order_no", Type: field.TypeString, Unique: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"alipay", "wxpay"}},
		{Name: "amount", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "decimal(20,2)"}},
		{Name: "fee_official", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,2)"}},
		{Name: "fee_platform", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,2)"}},
		{Name: "net_amount", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,2)"}},
		{Name: "trade_no", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"PENDING", "PAID", "SETTLED", "EXPIRED", "CANCELLED"}, Default: "PENDING"},
		{Name: "notify_url", Type: field.TypeString},
		{Name: "provider_snapshot", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "paid_at", Type: field.TypeTime, Nullable: true},
		{Name: "api_trade_no", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "buyer", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "param", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "name", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "clientip", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "return_url", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "device", Type: field.TypeString, Nullable: true, Default: "pc"},
		{Name: "method", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "sub_openid", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "sub_appid", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "auth_code", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "refund_money", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,2)"}},
		{Name: "version", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "product_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// OrdersTable holds the schema information for the "orders" table.
	OrdersTable = &schema.Table{
		Name:       "orders",
		Columns:    OrdersColumns,
		PrimaryKey: []*schema.Column{OrdersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "orders_products_orders",
				Columns:    []*schema.Column{OrdersColumns[27]},
				RefColumns: []*schema.Column{ProductsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "orders_users_orders",
				Columns:    []*schema.Column{OrdersColumns[28]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "order_trade_no",
				Unique:  true,
				Columns: []*schema.Column{OrdersColumns[7]},
				Annotation: &entsql.IndexAnnotation{
					Where: "trade_no <> ''",
				},
			},
		},
	}
	// ConfigsColumns holds the columns for the "configs" table.
	ConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "value", Type: field.TypeString, Nullable: true, Default: "", SchemaType: map[string]string{"postgres": "text"}},
		{Name: "description", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ConfigsTable holds the schema information for the "configs" table.
	ConfigsTable = &schema.Table{
		Name:       "configs",
		Columns:    ConfigsColumns,
		PrimaryKey: []*schema.Column{ConfigsColumns[0]},
	}
	// ProductsColumns holds the columns for the "products" table.
	ProductsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "pid", Type: field.TypeInt, Unique: true},
		{Name: "pkey", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "notify_url", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "return_url", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "fee_rate", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(10,4)"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "disabled"}, Default: "active"},
		{Name: "keytype", Type: field.TypeInt, Default: 0},
		{Name: "public_key", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "refund_enabled", Type: field.TypeBool, Default: false},
		{Name: "transfer_enabled", Type: field.TypeBool, Default: false},
		{Name: "mode", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// ProductsTable holds the schema information for the "products" table.
	ProductsTable = &schema.Table{
		Name:       "products",
		Columns:    ProductsColumns,
		PrimaryKey: []*schema.Column{ProductsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "products_users_products",
				Columns:    []*schema.Column{ProductsColumns[16]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// RefundsColumns holds the columns for the "refunds" table.
	RefundsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "refund_no", Type: field.TypeString, Unique: true},
		{Name: "out_refund_no", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "trade_no", Type: field.TypeString},
		{Name: "money", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "decimal(20,2)"}},
		{Name: "reduce_money", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,2)"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"PENDING", "SUCCESS", "FAILED"}, Default: "PENDING"},
		{Name: "message", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// RefundsTable holds the schema information for the "refunds" table.
	RefundsTable = &schema.Table{
		Name:       "refunds",
		Columns:    RefundsColumns,
		PrimaryKey: []*schema.Column{RefundsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "refunds_users_refunds",
				Columns:    []*schema.Column{RefundsColumns[11]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "refund_user_id_out_refund_no",
				Unique:  true,
				Columns: []*schema.Column{RefundsColumns[11], RefundsColumns[2]},
				Annotation: &entsql.IndexAnnotation{
					Where: "out_refund_no <> ''",
				},
			},
		},
	}
	// SettlementsColumns holds the columns for the "settlements" table.
	SettlementsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "balance", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,2)"}},
		{Name: "frozen", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,2)"}},
		{Name: "total_income", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,2)"}},
		{Name: "total_withdrawn", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,2)"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// SettlementsTable holds the schema information for the "settlements" table.
	SettlementsTable = &schema.Table{
		Name:       "settlements",
		Columns:    SettlementsColumns,
		PrimaryKey: []*schema.Column{SettlementsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "settlements_users_settlements",
				Columns:    []*schema.Column{SettlementsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "fee_rate", Type: field.TypeFloat64, Default: 0.006, SchemaType: map[string]string{"postgres": "decimal(10,4)"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "disabled"}, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_email",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[1]},
			},
		},
	}
	// WithdrawsColumns holds the columns for the "withdraws" table.
	WithdrawsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "amount", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "decimal(20,2)"}},
		{Name: "account_info", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"PENDING", "APPROVED", "PAID", "REJECTED"}, Default: "PENDING"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// WithdrawsTable holds the schema information for the "withdraws" table.
	WithdrawsTable = &schema.Table{
		Name:       "withdraws",
		Columns:    WithdrawsColumns,
		PrimaryKey: []*schema.Column{WithdrawsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "withdraws_users_withdraws",
				Columns:    []*schema.Column{WithdrawsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AdminsTable,
		OrdersTable,
		ConfigsTable,
		ProductsTable,
		RefundsTable,
		SettlementsTable,
		UsersTable,
		WithdrawsTable,
	}
)

func init() {
	OrdersTable.ForeignKeys[0].RefTable = ProductsTable
	OrdersTable.ForeignKeys[1].RefTable = UsersTable
	ConfigsTable.Annotation = &entsql.Annotation{
		Table: "configs",
	}
	ProductsTable.ForeignKeys[0].RefTable = UsersTable
	RefundsTable.ForeignKeys[0].RefTable = UsersTable
	SettlementsTable.ForeignKeys[0].RefTable = UsersTable
	WithdrawsTable.ForeignKeys[0].RefTable = UsersTable
}
