// Code generated by ent, DO NOT EDIT.

package settlement

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the settlement type in the database.
	Label = "settlement"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMerchantID holds the string denoting the merchant_id field in the database.
	FieldMerchantID = "merchant_id"
	// FieldBalance holds the string denoting the balance field in the database.
	FieldBalance = "balance"
	// FieldFrozen holds the string denoting the frozen field in the database.
	FieldFrozen = "frozen"
	// FieldTotalIncome holds the string denoting the total_income field in the database.
	FieldTotalIncome = "total_income"
	// FieldTotalWithdrawn holds the string denoting the total_withdrawn field in the database.
	FieldTotalWithdrawn = "total_withdrawn"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeMerchant holds the string denoting the merchant edge name in mutations.
	EdgeMerchant = "merchant"
	// Table holds the table name of the settlement in the database.
	Table = "settlements"
	// MerchantTable is the table that holds the merchant relation/edge.
	MerchantTable = "settlements"
	// MerchantInverseTable is the table name for the Merchant entity.
	// It exists in this package in order to avoid circular dependency with the "merchant" package.
	MerchantInverseTable = "merchants"
	// MerchantColumn is the table column denoting the merchant relation/edge.
	MerchantColumn = "merchant_id"
)

// Columns holds all SQL columns for settlement fields.
var Columns = []string{
	FieldID,
	FieldMerchantID,
	FieldBalance,
	FieldFrozen,
	FieldTotalIncome,
	FieldTotalWithdrawn,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultBalance holds the default value on creation for the "balance" field.
	DefaultBalance float64
	// DefaultFrozen holds the default value on creation for the "frozen" field.
	DefaultFrozen float64
	// DefaultTotalIncome holds the default value on creation for the "total_income" field.
	DefaultTotalIncome float64
	// DefaultTotalWithdrawn holds the default value on creation for the "total_withdrawn" field.
	DefaultTotalWithdrawn float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Settlement queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMerchantID orders the results by the merchant_id field.
func ByMerchantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMerchantID, opts...).ToFunc()
}

// ByBalance orders the results by the balance field.
func ByBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalance, opts...).ToFunc()
}

// ByFrozen orders the results by the frozen field.
func ByFrozen(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFrozen, opts...).ToFunc()
}

// ByTotalIncome orders the results by the total_income field.
func ByTotalIncome(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalIncome, opts...).ToFunc()
}

// ByTotalWithdrawn orders the results by the total_withdrawn field.
func ByTotalWithdrawn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalWithdrawn, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByMerchantField orders the results by merchant field.
func ByMerchantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMerchantStep(), sql.OrderByField(field, opts...))
	}
}
func newMerchantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MerchantInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, MerchantTable, MerchantColumn),
	)
}
