// Code generated by ent, DO NOT EDIT.

package settlement

import (
	"epay/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Settlement {
	return predicate.Settlement(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Settlement {
	return predicate.Settlement(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Settlement {
	return predicate.Settlement(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Settlement {
	return predicate.Settlement(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Settlement {
	return predicate.Settlement(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Settlement {
	return predicate.Settlement(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Settlement {
	return predicate.Settlement(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldUserID, v))
}

// Balance applies equality check predicate on the "balance" field. It's identical to BalanceEQ.
func Balance(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldBalance, v))
}

// Frozen applies equality check predicate on the "frozen" field. It's identical to FrozenEQ.
func Frozen(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldFrozen, v))
}

// TotalIncome applies equality check predicate on the "total_income" field. It's identical to TotalIncomeEQ.
func TotalIncome(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldTotalIncome, v))
}

// TotalWithdrawn applies equality check predicate on the "total_withdrawn" field. It's identical to TotalWithdrawnEQ.
func TotalWithdrawn(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldTotalWithdrawn, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.Settlement {
	return predicate.Settlement(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.Settlement {
	return predicate.Settlement(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.Settlement {
	return predicate.Settlement(sql.FieldNotIn(FieldUserID, vs...))
}

// BalanceEQ applies the EQ predicate on the "balance" field.
func BalanceEQ(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldBalance, v))
}

// BalanceNEQ applies the NEQ predicate on the "balance" field.
func BalanceNEQ(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldNEQ(FieldBalance, v))
}

// BalanceIn applies the In predicate on the "balance" field.
func BalanceIn(vs ...float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldIn(FieldBalance, vs...))
}

// BalanceNotIn applies the NotIn predicate on the "balance" field.
func BalanceNotIn(vs ...float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldNotIn(FieldBalance, vs...))
}

// BalanceGT applies the GT predicate on the "balance" field.
func BalanceGT(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldGT(FieldBalance, v))
}

// BalanceGTE applies the GTE predicate on the "balance" field.
func BalanceGTE(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldGTE(FieldBalance, v))
}

// BalanceLT applies the LT predicate on the "balance" field.
func BalanceLT(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldLT(FieldBalance, v))
}

// BalanceLTE applies the LTE predicate on the "balance" field.
func BalanceLTE(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldLTE(FieldBalance, v))
}

// FrozenEQ applies the EQ predicate on the "frozen" field.
func FrozenEQ(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldFrozen, v))
}

// FrozenNEQ applies the NEQ predicate on the "frozen" field.
func FrozenNEQ(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldNEQ(FieldFrozen, v))
}

// FrozenIn applies the In predicate on the "frozen" field.
func FrozenIn(vs ...float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldIn(FieldFrozen, vs...))
}

// FrozenNotIn applies the NotIn predicate on the "frozen" field.
func FrozenNotIn(vs ...float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldNotIn(FieldFrozen, vs...))
}

// FrozenGT applies the GT predicate on the "frozen" field.
func FrozenGT(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldGT(FieldFrozen, v))
}

// FrozenGTE applies the GTE predicate on the "frozen" field.
func FrozenGTE(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldGTE(FieldFrozen, v))
}

// FrozenLT applies the LT predicate on the "frozen" field.
func FrozenLT(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldLT(FieldFrozen, v))
}

// FrozenLTE applies the LTE predicate on the "frozen" field.
func FrozenLTE(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldLTE(FieldFrozen, v))
}

// TotalIncomeEQ applies the EQ predicate on the "total_income" field.
func TotalIncomeEQ(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldTotalIncome, v))
}

// TotalIncomeNEQ applies the NEQ predicate on the "total_income" field.
func TotalIncomeNEQ(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldNEQ(FieldTotalIncome, v))
}

// TotalIncomeIn applies the In predicate on the "total_income" field.
func TotalIncomeIn(vs ...float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldIn(FieldTotalIncome, vs...))
}

// TotalIncomeNotIn applies the NotIn predicate on the "total_income" field.
func TotalIncomeNotIn(vs ...float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldNotIn(FieldTotalIncome, vs...))
}

// TotalIncomeGT applies the GT predicate on the "total_income" field.
func TotalIncomeGT(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldGT(FieldTotalIncome, v))
}

// TotalIncomeGTE applies the GTE predicate on the "total_income" field.
func TotalIncomeGTE(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldGTE(FieldTotalIncome, v))
}

// TotalIncomeLT applies the LT predicate on the "total_income" field.
func TotalIncomeLT(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldLT(FieldTotalIncome, v))
}

// TotalIncomeLTE applies the LTE predicate on the "total_income" field.
func TotalIncomeLTE(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldLTE(FieldTotalIncome, v))
}

// TotalWithdrawnEQ applies the EQ predicate on the "total_withdrawn" field.
func TotalWithdrawnEQ(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldTotalWithdrawn, v))
}

// TotalWithdrawnNEQ applies the NEQ predicate on the "total_withdrawn" field.
func TotalWithdrawnNEQ(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldNEQ(FieldTotalWithdrawn, v))
}

// TotalWithdrawnIn applies the In predicate on the "total_withdrawn" field.
func TotalWithdrawnIn(vs ...float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldIn(FieldTotalWithdrawn, vs...))
}

// TotalWithdrawnNotIn applies the NotIn predicate on the "total_withdrawn" field.
func TotalWithdrawnNotIn(vs ...float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldNotIn(FieldTotalWithdrawn, vs...))
}

// TotalWithdrawnGT applies the GT predicate on the "total_withdrawn" field.
func TotalWithdrawnGT(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldGT(FieldTotalWithdrawn, v))
}

// TotalWithdrawnGTE applies the GTE predicate on the "total_withdrawn" field.
func TotalWithdrawnGTE(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldGTE(FieldTotalWithdrawn, v))
}

// TotalWithdrawnLT applies the LT predicate on the "total_withdrawn" field.
func TotalWithdrawnLT(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldLT(FieldTotalWithdrawn, v))
}

// TotalWithdrawnLTE applies the LTE predicate on the "total_withdrawn" field.
func TotalWithdrawnLTE(v float64) predicate.Settlement {
	return predicate.Settlement(sql.FieldLTE(FieldTotalWithdrawn, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Settlement {
	return predicate.Settlement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Settlement {
	return predicate.Settlement(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Settlement) predicate.Settlement {
	return predicate.Settlement(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Settlement) predicate.Settlement {
	return predicate.Settlement(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Settlement) predicate.Settlement {
	return predicate.Settlement(sql.NotPredicates(p))
}
