// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"epay/ent/order"
	"epay/ent/product"
	"epay/ent/user"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// OrderCreate is the builder for creating a Order entity.
type OrderCreate struct {
	config
	mutation *OrderMutation
	hooks    []Hook
}

// SetOrderNo sets the "order_no" field.
func (_c *OrderCreate) SetOrderNo(v string) *OrderCreate {
	_c.mutation.SetOrderNo(v)
	return _c
}

// SetProductID sets the "product_id" field.
func (_c *OrderCreate) SetProductID(v uuid.UUID) *OrderCreate {
	_c.mutation.SetProductID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *OrderCreate) SetUserID(v uuid.UUID) *OrderCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetType sets the "type" field.
func (_c *OrderCreate) SetType(v order.Type) *OrderCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *OrderCreate) SetAmount(v float64) *OrderCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetFeeOfficial sets the "fee_official" field.
func (_c *OrderCreate) SetFeeOfficial(v float64) *OrderCreate {
	_c.mutation.SetFeeOfficial(v)
	return _c
}

// SetNillableFeeOfficial sets the "fee_official" field if the given value is not nil.
func (_c *OrderCreate) SetNillableFeeOfficial(v *float64) *OrderCreate {
	if v != nil {
		_c.SetFeeOfficial(*v)
	}
	return _c
}

// SetFeePlatform sets the "fee_platform" field.
func (_c *OrderCreate) SetFeePlatform(v float64) *OrderCreate {
	_c.mutation.SetFeePlatform(v)
	return _c
}

// SetNillableFeePlatform sets the "fee_platform" field if the given value is not nil.
func (_c *OrderCreate) SetNillableFeePlatform(v *float64) *OrderCreate {
	if v != nil {
		_c.SetFeePlatform(*v)
	}
	return _c
}

// SetNetAmount sets the "net_amount" field.
func (_c *OrderCreate) SetNetAmount(v float64) *OrderCreate {
	_c.mutation.SetNetAmount(v)
	return _c
}

// SetNillableNetAmount sets the "net_amount" field if the given value is not nil.
func (_c *OrderCreate) SetNillableNetAmount(v *float64) *OrderCreate {
	if v != nil {
		_c.SetNetAmount(*v)
	}
	return _c
}

// SetTradeNo sets the "trade_no" field.
func (_c *OrderCreate) SetTradeNo(v string) *OrderCreate {
	_c.mutation.SetTradeNo(v)
	return _c
}

// SetNillableTradeNo sets the "trade_no" field if the given value is not nil.
func (_c *OrderCreate) SetNillableTradeNo(v *string) *OrderCreate {
	if v != nil {
		_c.SetTradeNo(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *OrderCreate) SetStatus(v order.Status) *OrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OrderCreate) SetNillableStatus(v *order.Status) *OrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetNotifyURL sets the "notify_url" field.
func (_c *OrderCreate) SetNotifyURL(v string) *OrderCreate {
	_c.mutation.SetNotifyURL(v)
	return _c
}

// SetProviderSnapshot sets the "provider_snapshot" field.
func (_c *OrderCreate) SetProviderSnapshot(v string) *OrderCreate {
	_c.mutation.SetProviderSnapshot(v)
	return _c
}

// SetNillableProviderSnapshot sets the "provider_snapshot" field if the given value is not nil.
func (_c *OrderCreate) SetNillableProviderSnapshot(v *string) *OrderCreate {
	if v != nil {
		_c.SetProviderSnapshot(*v)
	}
	return _c
}

// SetPaidAt sets the "paid_at" field.
func (_c *OrderCreate) SetPaidAt(v time.Time) *OrderCreate {
	_c.mutation.SetPaidAt(v)
	return _c
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_c *OrderCreate) SetNillablePaidAt(v *time.Time) *OrderCreate {
	if v != nil {
		_c.SetPaidAt(*v)
	}
	return _c
}

// SetAPITradeNo sets the "api_trade_no" field.
func (_c *OrderCreate) SetAPITradeNo(v string) *OrderCreate {
	_c.mutation.SetAPITradeNo(v)
	return _c
}

// SetNillableAPITradeNo sets the "api_trade_no" field if the given value is not nil.
func (_c *OrderCreate) SetNillableAPITradeNo(v *string) *OrderCreate {
	if v != nil {
		_c.SetAPITradeNo(*v)
	}
	return _c
}

// SetBuyer sets the "buyer" field.
func (_c *OrderCreate) SetBuyer(v string) *OrderCreate {
	_c.mutation.SetBuyer(v)
	return _c
}

// SetNillableBuyer sets the "buyer" field if the given value is not nil.
func (_c *OrderCreate) SetNillableBuyer(v *string) *OrderCreate {
	if v != nil {
		_c.SetBuyer(*v)
	}
	return _c
}

// SetParam sets the "param" field.
func (_c *OrderCreate) SetParam(v string) *OrderCreate {
	_c.mutation.SetParam(v)
	return _c
}

// SetNillableParam sets the "param" field if the given value is not nil.
func (_c *OrderCreate) SetNillableParam(v *string) *OrderCreate {
	if v != nil {
		_c.SetParam(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *OrderCreate) SetName(v string) *OrderCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *OrderCreate) SetNillableName(v *string) *OrderCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetClientip sets the "clientip" field.
func (_c *OrderCreate) SetClientip(v string) *OrderCreate {
	_c.mutation.SetClientip(v)
	return _c
}

// SetNillableClientip sets the "clientip" field if the given value is not nil.
func (_c *OrderCreate) SetNillableClientip(v *string) *OrderCreate {
	if v != nil {
		_c.SetClientip(*v)
	}
	return _c
}

// SetReturnURL sets the "return_url" field.
func (_c *OrderCreate) SetReturnURL(v string) *OrderCreate {
	_c.mutation.SetReturnURL(v)
	return _c
}

// SetNillableReturnURL sets the "return_url" field if the given value is not nil.
func (_c *OrderCreate) SetNillableReturnURL(v *string) *OrderCreate {
	if v != nil {
		_c.SetReturnURL(*v)
	}
	return _c
}

// SetDevice sets the "device" field.
func (_c *OrderCreate) SetDevice(v string) *OrderCreate {
	_c.mutation.SetDevice(v)
	return _c
}

// SetNillableDevice sets the "device" field if the given value is not nil.
func (_c *OrderCreate) SetNillableDevice(v *string) *OrderCreate {
	if v != nil {
		_c.SetDevice(*v)
	}
	return _c
}

// SetMethod sets the "method" field.
func (_c *OrderCreate) SetMethod(v string) *OrderCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_c *OrderCreate) SetNillableMethod(v *string) *OrderCreate {
	if v != nil {
		_c.SetMethod(*v)
	}
	return _c
}

// SetSubOpenid sets the "sub_openid" field.
func (_c *OrderCreate) SetSubOpenid(v string) *OrderCreate {
	_c.mutation.SetSubOpenid(v)
	return _c
}

// SetNillableSubOpenid sets the "sub_openid" field if the given value is not nil.
func (_c *OrderCreate) SetNillableSubOpenid(v *string) *OrderCreate {
	if v != nil {
		_c.SetSubOpenid(*v)
	}
	return _c
}

// SetSubAppid sets the "sub_appid" field.
func (_c *OrderCreate) SetSubAppid(v string) *OrderCreate {
	_c.mutation.SetSubAppid(v)
	return _c
}

// SetNillableSubAppid sets the "sub_appid" field if the given value is not nil.
func (_c *OrderCreate) SetNillableSubAppid(v *string) *OrderCreate {
	if v != nil {
		_c.SetSubAppid(*v)
	}
	return _c
}

// SetAuthCode sets the "auth_code" field.
func (_c *OrderCreate) SetAuthCode(v string) *OrderCreate {
	_c.mutation.SetAuthCode(v)
	return _c
}

// SetNillableAuthCode sets the "auth_code" field if the given value is not nil.
func (_c *OrderCreate) SetNillableAuthCode(v *string) *OrderCreate {
	if v != nil {
		_c.SetAuthCode(*v)
	}
	return _c
}

// SetRefundMoney sets the "refund_money" field.
func (_c *OrderCreate) SetRefundMoney(v float64) *OrderCreate {
	_c.mutation.SetRefundMoney(v)
	return _c
}

// SetNillableRefundMoney sets the "refund_money" field if the given value is not nil.
func (_c *OrderCreate) SetNillableRefundMoney(v *float64) *OrderCreate {
	if v != nil {
		_c.SetRefundMoney(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *OrderCreate) SetVersion(v int) *OrderCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *OrderCreate) SetNillableVersion(v *int) *OrderCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OrderCreate) SetCreatedAt(v time.Time) *OrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OrderCreate) SetNillableCreatedAt(v *time.Time) *OrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OrderCreate) SetUpdatedAt(v time.Time) *OrderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OrderCreate) SetNillableUpdatedAt(v *time.Time) *OrderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OrderCreate) SetID(v uuid.UUID) *OrderCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OrderCreate) SetNillableID(v *uuid.UUID) *OrderCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetProduct sets the "product" edge to the Product entity.
func (_c *OrderCreate) SetProduct(v *Product) *OrderCreate {
	return _c.SetProductID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *OrderCreate) SetUser(v *User) *OrderCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the OrderMutation object of the builder.
func (_c *OrderCreate) Mutation() *OrderMutation {
	return _c.mutation
}

// Save creates the Order in the database.
func (_c *OrderCreate) Save(ctx context.Context) (*Order, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrderCreate) SaveX(ctx context.Context) *Order {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OrderCreate) defaults() {
	if _, ok := _c.mutation.FeeOfficial(); !ok {
		v := order.DefaultFeeOfficial
		_c.mutation.SetFeeOfficial(v)
	}
	if _, ok := _c.mutation.FeePlatform(); !ok {
		v := order.DefaultFeePlatform
		_c.mutation.SetFeePlatform(v)
	}
	if _, ok := _c.mutation.NetAmount(); !ok {
		v := order.DefaultNetAmount
		_c.mutation.SetNetAmount(v)
	}
	if _, ok := _c.mutation.TradeNo(); !ok {
		v := order.DefaultTradeNo
		_c.mutation.SetTradeNo(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := order.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ProviderSnapshot(); !ok {
		v := order.DefaultProviderSnapshot
		_c.mutation.SetProviderSnapshot(v)
	}
	if _, ok := _c.mutation.APITradeNo(); !ok {
		v := order.DefaultAPITradeNo
		_c.mutation.SetAPITradeNo(v)
	}
	if _, ok := _c.mutation.Buyer(); !ok {
		v := order.DefaultBuyer
		_c.mutation.SetBuyer(v)
	}
	if _, ok := _c.mutation.Param(); !ok {
		v := order.DefaultParam
		_c.mutation.SetParam(v)
	}
	if _, ok := _c.mutation.Name(); !ok {
		v := order.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.Clientip(); !ok {
		v := order.DefaultClientip
		_c.mutation.SetClientip(v)
	}
	if _, ok := _c.mutation.ReturnURL(); !ok {
		v := order.DefaultReturnURL
		_c.mutation.SetReturnURL(v)
	}
	if _, ok := _c.mutation.Device(); !ok {
		v := order.DefaultDevice
		_c.mutation.SetDevice(v)
	}
	if _, ok := _c.mutation.Method(); !ok {
		v := order.DefaultMethod
		_c.mutation.SetMethod(v)
	}
	if _, ok := _c.mutation.SubOpenid(); !ok {
		v := order.DefaultSubOpenid
		_c.mutation.SetSubOpenid(v)
	}
	if _, ok := _c.mutation.SubAppid(); !ok {
		v := order.DefaultSubAppid
		_c.mutation.SetSubAppid(v)
	}
	if _, ok := _c.mutation.AuthCode(); !ok {
		v := order.DefaultAuthCode
		_c.mutation.SetAuthCode(v)
	}
	if _, ok := _c.mutation.RefundMoney(); !ok {
		v := order.DefaultRefundMoney
		_c.mutation.SetRefundMoney(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := order.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := order.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := order.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := order.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrderCreate) check() error {
	if _, ok := _c.mutation.OrderNo(); !ok {
		return &ValidationError{Name: "order_no", err: errors.New(`ent: missing required field "Order.order_no"`)}
	}
	if v, ok := _c.mutation.OrderNo(); ok {
		if err := order.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "Order.order_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProductID(); !ok {
		return &ValidationError{Name: "product_id", err: errors.New(`ent: missing required field "Order.product_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Order.user_id"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Order.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := order.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Order.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "Order.amount"`)}
	}
	if _, ok := _c.mutation.FeeOfficial(); !ok {
		return &ValidationError{Name: "fee_official", err: errors.New(`ent: missing required field "Order.fee_official"`)}
	}
	if _, ok := _c.mutation.FeePlatform(); !ok {
		return &ValidationError{Name: "fee_platform", err: errors.New(`ent: missing required field "Order.fee_platform"`)}
	}
	if _, ok := _c.mutation.NetAmount(); !ok {
		return &ValidationError{Name: "net_amount", err: errors.New(`ent: missing required field "Order.net_amount"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Order.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := order.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Order.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NotifyURL(); !ok {
		return &ValidationError{Name: "notify_url", err: errors.New(`ent: missing required field "Order.notify_url"`)}
	}
	if v, ok := _c.mutation.NotifyURL(); ok {
		if err := order.NotifyURLValidator(v); err != nil {
			return &ValidationError{Name: "notify_url", err: fmt.Errorf(`ent: validator failed for field "Order.notify_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RefundMoney(); !ok {
		return &ValidationError{Name: "refund_money", err: errors.New(`ent: missing required field "Order.refund_money"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Order.version"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Order.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Order.updated_at"`)}
	}
	if len(_c.mutation.ProductIDs()) == 0 {
		return &ValidationError{Name: "product", err: errors.New(`ent: missing required edge "Order.product"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Order.user"`)}
	}
	return nil
}

func (_c *OrderCreate) sqlSave(ctx context.Context) (*Order, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OrderCreate) createSpec() (*Order, *sqlgraph.CreateSpec) {
	var (
		_node = &Order{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(order.Table, sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.OrderNo(); ok {
		_spec.SetField(order.FieldOrderNo, field.TypeString, value)
		_node.OrderNo = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(order.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(order.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.FeeOfficial(); ok {
		_spec.SetField(order.FieldFeeOfficial, field.TypeFloat64, value)
		_node.FeeOfficial = value
	}
	if value, ok := _c.mutation.FeePlatform(); ok {
		_spec.SetField(order.FieldFeePlatform, field.TypeFloat64, value)
		_node.FeePlatform = value
	}
	if value, ok := _c.mutation.NetAmount(); ok {
		_spec.SetField(order.FieldNetAmount, field.TypeFloat64, value)
		_node.NetAmount = value
	}
	if value, ok := _c.mutation.TradeNo(); ok {
		_spec.SetField(order.FieldTradeNo, field.TypeString, value)
		_node.TradeNo = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.NotifyURL(); ok {
		_spec.SetField(order.FieldNotifyURL, field.TypeString, value)
		_node.NotifyURL = value
	}
	if value, ok := _c.mutation.ProviderSnapshot(); ok {
		_spec.SetField(order.FieldProviderSnapshot, field.TypeString, value)
		_node.ProviderSnapshot = value
	}
	if value, ok := _c.mutation.PaidAt(); ok {
		_spec.SetField(order.FieldPaidAt, field.TypeTime, value)
		_node.PaidAt = &value
	}
	if value, ok := _c.mutation.APITradeNo(); ok {
		_spec.SetField(order.FieldAPITradeNo, field.TypeString, value)
		_node.APITradeNo = value
	}
	if value, ok := _c.mutation.Buyer(); ok {
		_spec.SetField(order.FieldBuyer, field.TypeString, value)
		_node.Buyer = value
	}
	if value, ok := _c.mutation.Param(); ok {
		_spec.SetField(order.FieldParam, field.TypeString, value)
		_node.Param = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(order.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Clientip(); ok {
		_spec.SetField(order.FieldClientip, field.TypeString, value)
		_node.Clientip = value
	}
	if value, ok := _c.mutation.ReturnURL(); ok {
		_spec.SetField(order.FieldReturnURL, field.TypeString, value)
		_node.ReturnURL = value
	}
	if value, ok := _c.mutation.Device(); ok {
		_spec.SetField(order.FieldDevice, field.TypeString, value)
		_node.Device = value
	}
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(order.FieldMethod, field.TypeString, value)
		_node.Method = value
	}
	if value, ok := _c.mutation.SubOpenid(); ok {
		_spec.SetField(order.FieldSubOpenid, field.TypeString, value)
		_node.SubOpenid = value
	}
	if value, ok := _c.mutation.SubAppid(); ok {
		_spec.SetField(order.FieldSubAppid, field.TypeString, value)
		_node.SubAppid = value
	}
	if value, ok := _c.mutation.AuthCode(); ok {
		_spec.SetField(order.FieldAuthCode, field.TypeString, value)
		_node.AuthCode = value
	}
	if value, ok := _c.mutation.RefundMoney(); ok {
		_spec.SetField(order.FieldRefundMoney, field.TypeFloat64, value)
		_node.RefundMoney = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(order.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(order.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.ProductTable,
			Columns: []string{order.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProductID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OrderCreateBulk is the builder for creating many Order entities in bulk.
type OrderCreateBulk struct {
	config
	err      error
	builders []*OrderCreate
}

// Save creates the Order entities in the database.
func (_c *OrderCreateBulk) Save(ctx context.Context) ([]*Order, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Order, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrderCreateBulk) SaveX(ctx context.Context) []*Order {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
