// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"epay/ent/order"
	"epay/ent/predicate"
	"epay/ent/product"
	"epay/ent/user"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// OrderUpdate is the builder for updating Order entities.
type OrderUpdate struct {
	config
	hooks    []Hook
	mutation *OrderMutation
}

// Where appends a list predicates to the OrderUpdate builder.
func (_u *OrderUpdate) Where(ps ...predicate.Order) *OrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrderNo sets the "order_no" field.
func (_u *OrderUpdate) SetOrderNo(v string) *OrderUpdate {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableOrderNo(v *string) *OrderUpdate {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *OrderUpdate) SetProductID(v uuid.UUID) *OrderUpdate {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableProductID(v *uuid.UUID) *OrderUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OrderUpdate) SetUserID(v uuid.UUID) *OrderUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableUserID(v *uuid.UUID) *OrderUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *OrderUpdate) SetType(v order.Type) *OrderUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableType(v *order.Type) *OrderUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *OrderUpdate) SetAmount(v float64) *OrderUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableAmount(v *float64) *OrderUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *OrderUpdate) AddAmount(v float64) *OrderUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetFeeOfficial sets the "fee_official" field.
func (_u *OrderUpdate) SetFeeOfficial(v float64) *OrderUpdate {
	_u.mutation.ResetFeeOfficial()
	_u.mutation.SetFeeOfficial(v)
	return _u
}

// SetNillableFeeOfficial sets the "fee_official" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableFeeOfficial(v *float64) *OrderUpdate {
	if v != nil {
		_u.SetFeeOfficial(*v)
	}
	return _u
}

// AddFeeOfficial adds value to the "fee_official" field.
func (_u *OrderUpdate) AddFeeOfficial(v float64) *OrderUpdate {
	_u.mutation.AddFeeOfficial(v)
	return _u
}

// SetFeePlatform sets the "fee_platform" field.
func (_u *OrderUpdate) SetFeePlatform(v float64) *OrderUpdate {
	_u.mutation.ResetFeePlatform()
	_u.mutation.SetFeePlatform(v)
	return _u
}

// SetNillableFeePlatform sets the "fee_platform" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableFeePlatform(v *float64) *OrderUpdate {
	if v != nil {
		_u.SetFeePlatform(*v)
	}
	return _u
}

// AddFeePlatform adds value to the "fee_platform" field.
func (_u *OrderUpdate) AddFeePlatform(v float64) *OrderUpdate {
	_u.mutation.AddFeePlatform(v)
	return _u
}

// SetNetAmount sets the "net_amount" field.
func (_u *OrderUpdate) SetNetAmount(v float64) *OrderUpdate {
	_u.mutation.ResetNetAmount()
	_u.mutation.SetNetAmount(v)
	return _u
}

// SetNillableNetAmount sets the "net_amount" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableNetAmount(v *float64) *OrderUpdate {
	if v != nil {
		_u.SetNetAmount(*v)
	}
	return _u
}

// AddNetAmount adds value to the "net_amount" field.
func (_u *OrderUpdate) AddNetAmount(v float64) *OrderUpdate {
	_u.mutation.AddNetAmount(v)
	return _u
}

// SetTradeNo sets the "trade_no" field.
func (_u *OrderUpdate) SetTradeNo(v string) *OrderUpdate {
	_u.mutation.SetTradeNo(v)
	return _u
}

// SetNillableTradeNo sets the "trade_no" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableTradeNo(v *string) *OrderUpdate {
	if v != nil {
		_u.SetTradeNo(*v)
	}
	return _u
}

// ClearTradeNo clears the value of the "trade_no" field.
func (_u *OrderUpdate) ClearTradeNo() *OrderUpdate {
	_u.mutation.ClearTradeNo()
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrderUpdate) SetStatus(v order.Status) *OrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableStatus(v *order.Status) *OrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNotifyURL sets the "notify_url" field.
func (_u *OrderUpdate) SetNotifyURL(v string) *OrderUpdate {
	_u.mutation.SetNotifyURL(v)
	return _u
}

// SetNillableNotifyURL sets the "notify_url" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableNotifyURL(v *string) *OrderUpdate {
	if v != nil {
		_u.SetNotifyURL(*v)
	}
	return _u
}

// SetProviderSnapshot sets the "provider_snapshot" field.
func (_u *OrderUpdate) SetProviderSnapshot(v string) *OrderUpdate {
	_u.mutation.SetProviderSnapshot(v)
	return _u
}

// SetNillableProviderSnapshot sets the "provider_snapshot" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableProviderSnapshot(v *string) *OrderUpdate {
	if v != nil {
		_u.SetProviderSnapshot(*v)
	}
	return _u
}

// ClearProviderSnapshot clears the value of the "provider_snapshot" field.
func (_u *OrderUpdate) ClearProviderSnapshot() *OrderUpdate {
	_u.mutation.ClearProviderSnapshot()
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *OrderUpdate) SetPaidAt(v time.Time) *OrderUpdate {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *OrderUpdate) SetNillablePaidAt(v *time.Time) *OrderUpdate {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *OrderUpdate) ClearPaidAt() *OrderUpdate {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetAPITradeNo sets the "api_trade_no" field.
func (_u *OrderUpdate) SetAPITradeNo(v string) *OrderUpdate {
	_u.mutation.SetAPITradeNo(v)
	return _u
}

// SetNillableAPITradeNo sets the "api_trade_no" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableAPITradeNo(v *string) *OrderUpdate {
	if v != nil {
		_u.SetAPITradeNo(*v)
	}
	return _u
}

// ClearAPITradeNo clears the value of the "api_trade_no" field.
func (_u *OrderUpdate) ClearAPITradeNo() *OrderUpdate {
	_u.mutation.ClearAPITradeNo()
	return _u
}

// SetBuyer sets the "buyer" field.
func (_u *OrderUpdate) SetBuyer(v string) *OrderUpdate {
	_u.mutation.SetBuyer(v)
	return _u
}

// SetNillableBuyer sets the "buyer" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableBuyer(v *string) *OrderUpdate {
	if v != nil {
		_u.SetBuyer(*v)
	}
	return _u
}

// ClearBuyer clears the value of the "buyer" field.
func (_u *OrderUpdate) ClearBuyer() *OrderUpdate {
	_u.mutation.ClearBuyer()
	return _u
}

// SetParam sets the "param" field.
func (_u *OrderUpdate) SetParam(v string) *OrderUpdate {
	_u.mutation.SetParam(v)
	return _u
}

// SetNillableParam sets the "param" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableParam(v *string) *OrderUpdate {
	if v != nil {
		_u.SetParam(*v)
	}
	return _u
}

// ClearParam clears the value of the "param" field.
func (_u *OrderUpdate) ClearParam() *OrderUpdate {
	_u.mutation.ClearParam()
	return _u
}

// SetName sets the "name" field.
func (_u *OrderUpdate) SetName(v string) *OrderUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableName(v *string) *OrderUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *OrderUpdate) ClearName() *OrderUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetClientip sets the "clientip" field.
func (_u *OrderUpdate) SetClientip(v string) *OrderUpdate {
	_u.mutation.SetClientip(v)
	return _u
}

// SetNillableClientip sets the "clientip" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableClientip(v *string) *OrderUpdate {
	if v != nil {
		_u.SetClientip(*v)
	}
	return _u
}

// ClearClientip clears the value of the "clientip" field.
func (_u *OrderUpdate) ClearClientip() *OrderUpdate {
	_u.mutation.ClearClientip()
	return _u
}

// SetReturnURL sets the "return_url" field.
func (_u *OrderUpdate) SetReturnURL(v string) *OrderUpdate {
	_u.mutation.SetReturnURL(v)
	return _u
}

// SetNillableReturnURL sets the "return_url" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableReturnURL(v *string) *OrderUpdate {
	if v != nil {
		_u.SetReturnURL(*v)
	}
	return _u
}

// ClearReturnURL clears the value of the "return_url" field.
func (_u *OrderUpdate) ClearReturnURL() *OrderUpdate {
	_u.mutation.ClearReturnURL()
	return _u
}

// SetDevice sets the "device" field.
func (_u *OrderUpdate) SetDevice(v string) *OrderUpdate {
	_u.mutation.SetDevice(v)
	return _u
}

// SetNillableDevice sets the "device" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableDevice(v *string) *OrderUpdate {
	if v != nil {
		_u.SetDevice(*v)
	}
	return _u
}

// ClearDevice clears the value of the "device" field.
func (_u *OrderUpdate) ClearDevice() *OrderUpdate {
	_u.mutation.ClearDevice()
	return _u
}

// SetMethod sets the "method" field.
func (_u *OrderUpdate) SetMethod(v string) *OrderUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableMethod(v *string) *OrderUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// ClearMethod clears the value of the "method" field.
func (_u *OrderUpdate) ClearMethod() *OrderUpdate {
	_u.mutation.ClearMethod()
	return _u
}

// SetSubOpenid sets the "sub_openid" field.
func (_u *OrderUpdate) SetSubOpenid(v string) *OrderUpdate {
	_u.mutation.SetSubOpenid(v)
	return _u
}

// SetNillableSubOpenid sets the "sub_openid" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableSubOpenid(v *string) *OrderUpdate {
	if v != nil {
		_u.SetSubOpenid(*v)
	}
	return _u
}

// ClearSubOpenid clears the value of the "sub_openid" field.
func (_u *OrderUpdate) ClearSubOpenid() *OrderUpdate {
	_u.mutation.ClearSubOpenid()
	return _u
}

// SetSubAppid sets the "sub_appid" field.
func (_u *OrderUpdate) SetSubAppid(v string) *OrderUpdate {
	_u.mutation.SetSubAppid(v)
	return _u
}

// SetNillableSubAppid sets the "sub_appid" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableSubAppid(v *string) *OrderUpdate {
	if v != nil {
		_u.SetSubAppid(*v)
	}
	return _u
}

// ClearSubAppid clears the value of the "sub_appid" field.
func (_u *OrderUpdate) ClearSubAppid() *OrderUpdate {
	_u.mutation.ClearSubAppid()
	return _u
}

// SetAuthCode sets the "auth_code" field.
func (_u *OrderUpdate) SetAuthCode(v string) *OrderUpdate {
	_u.mutation.SetAuthCode(v)
	return _u
}

// SetNillableAuthCode sets the "auth_code" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableAuthCode(v *string) *OrderUpdate {
	if v != nil {
		_u.SetAuthCode(*v)
	}
	return _u
}

// ClearAuthCode clears the value of the "auth_code" field.
func (_u *OrderUpdate) ClearAuthCode() *OrderUpdate {
	_u.mutation.ClearAuthCode()
	return _u
}

// SetRefundMoney sets the "refund_money" field.
func (_u *OrderUpdate) SetRefundMoney(v float64) *OrderUpdate {
	_u.mutation.ResetRefundMoney()
	_u.mutation.SetRefundMoney(v)
	return _u
}

// SetNillableRefundMoney sets the "refund_money" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableRefundMoney(v *float64) *OrderUpdate {
	if v != nil {
		_u.SetRefundMoney(*v)
	}
	return _u
}

// AddRefundMoney adds value to the "refund_money" field.
func (_u *OrderUpdate) AddRefundMoney(v float64) *OrderUpdate {
	_u.mutation.AddRefundMoney(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *OrderUpdate) SetVersion(v int) *OrderUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableVersion(v *int) *OrderUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *OrderUpdate) AddVersion(v int) *OrderUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrderUpdate) SetUpdatedAt(v time.Time) *OrderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProduct sets the "product" edge to the Product entity.
func (_u *OrderUpdate) SetProduct(v *Product) *OrderUpdate {
	return _u.SetProductID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *OrderUpdate) SetUser(v *User) *OrderUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the OrderMutation object of the builder.
func (_u *OrderUpdate) Mutation() *OrderMutation {
	return _u.mutation
}

// ClearProduct clears the "product" edge to the Product entity.
func (_u *OrderUpdate) ClearProduct() *OrderUpdate {
	_u.mutation.ClearProduct()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *OrderUpdate) ClearUser() *OrderUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := order.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderUpdate) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := order.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "Order.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := order.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Order.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := order.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Order.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NotifyURL(); ok {
		if err := order.NotifyURLValidator(v); err != nil {
			return &ValidationError{Name: "notify_url", err: fmt.Errorf(`ent: validator failed for field "Order.notify_url": %w`, err)}
		}
	}
	if _u.mutation.ProductCleared() && len(_u.mutation.ProductIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Order.product"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Order.user"`)
	}
	return nil
}

func (_u *OrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(order.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(order.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(order.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(order.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FeeOfficial(); ok {
		_spec.SetField(order.FieldFeeOfficial, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFeeOfficial(); ok {
		_spec.AddField(order.FieldFeeOfficial, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FeePlatform(); ok {
		_spec.SetField(order.FieldFeePlatform, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFeePlatform(); ok {
		_spec.AddField(order.FieldFeePlatform, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.NetAmount(); ok {
		_spec.SetField(order.FieldNetAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedNetAmount(); ok {
		_spec.AddField(order.FieldNetAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TradeNo(); ok {
		_spec.SetField(order.FieldTradeNo, field.TypeString, value)
	}
	if _u.mutation.TradeNoCleared() {
		_spec.ClearField(order.FieldTradeNo, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.NotifyURL(); ok {
		_spec.SetField(order.FieldNotifyURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderSnapshot(); ok {
		_spec.SetField(order.FieldProviderSnapshot, field.TypeString, value)
	}
	if _u.mutation.ProviderSnapshotCleared() {
		_spec.ClearField(order.FieldProviderSnapshot, field.TypeString)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(order.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(order.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.APITradeNo(); ok {
		_spec.SetField(order.FieldAPITradeNo, field.TypeString, value)
	}
	if _u.mutation.APITradeNoCleared() {
		_spec.ClearField(order.FieldAPITradeNo, field.TypeString)
	}
	if value, ok := _u.mutation.Buyer(); ok {
		_spec.SetField(order.FieldBuyer, field.TypeString, value)
	}
	if _u.mutation.BuyerCleared() {
		_spec.ClearField(order.FieldBuyer, field.TypeString)
	}
	if value, ok := _u.mutation.Param(); ok {
		_spec.SetField(order.FieldParam, field.TypeString, value)
	}
	if _u.mutation.ParamCleared() {
		_spec.ClearField(order.FieldParam, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(order.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(order.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Clientip(); ok {
		_spec.SetField(order.FieldClientip, field.TypeString, value)
	}
	if _u.mutation.ClientipCleared() {
		_spec.ClearField(order.FieldClientip, field.TypeString)
	}
	if value, ok := _u.mutation.ReturnURL(); ok {
		_spec.SetField(order.FieldReturnURL, field.TypeString, value)
	}
	if _u.mutation.ReturnURLCleared() {
		_spec.ClearField(order.FieldReturnURL, field.TypeString)
	}
	if value, ok := _u.mutation.Device(); ok {
		_spec.SetField(order.FieldDevice, field.TypeString, value)
	}
	if _u.mutation.DeviceCleared() {
		_spec.ClearField(order.FieldDevice, field.TypeString)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(order.FieldMethod, field.TypeString, value)
	}
	if _u.mutation.MethodCleared() {
		_spec.ClearField(order.FieldMethod, field.TypeString)
	}
	if value, ok := _u.mutation.SubOpenid(); ok {
		_spec.SetField(order.FieldSubOpenid, field.TypeString, value)
	}
	if _u.mutation.SubOpenidCleared() {
		_spec.ClearField(order.FieldSubOpenid, field.TypeString)
	}
	if value, ok := _u.mutation.SubAppid(); ok {
		_spec.SetField(order.FieldSubAppid, field.TypeString, value)
	}
	if _u.mutation.SubAppidCleared() {
		_spec.ClearField(order.FieldSubAppid, field.TypeString)
	}
	if value, ok := _u.mutation.AuthCode(); ok {
		_spec.SetField(order.FieldAuthCode, field.TypeString, value)
	}
	if _u.mutation.AuthCodeCleared() {
		_spec.ClearField(order.FieldAuthCode, field.TypeString)
	}
	if value, ok := _u.mutation.RefundMoney(); ok {
		_spec.SetField(order.FieldRefundMoney, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRefundMoney(); ok {
		_spec.AddField(order.FieldRefundMoney, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(order.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(order.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.ProductTable,
			Columns: []string{order.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.ProductTable,
			Columns: []string{order.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrderUpdateOne is the builder for updating a single Order entity.
type OrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderMutation
}

// SetOrderNo sets the "order_no" field.
func (_u *OrderUpdateOne) SetOrderNo(v string) *OrderUpdateOne {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableOrderNo(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *OrderUpdateOne) SetProductID(v uuid.UUID) *OrderUpdateOne {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableProductID(v *uuid.UUID) *OrderUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OrderUpdateOne) SetUserID(v uuid.UUID) *OrderUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableUserID(v *uuid.UUID) *OrderUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *OrderUpdateOne) SetType(v order.Type) *OrderUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableType(v *order.Type) *OrderUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *OrderUpdateOne) SetAmount(v float64) *OrderUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableAmount(v *float64) *OrderUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *OrderUpdateOne) AddAmount(v float64) *OrderUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetFeeOfficial sets the "fee_official" field.
func (_u *OrderUpdateOne) SetFeeOfficial(v float64) *OrderUpdateOne {
	_u.mutation.ResetFeeOfficial()
	_u.mutation.SetFeeOfficial(v)
	return _u
}

// SetNillableFeeOfficial sets the "fee_official" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableFeeOfficial(v *float64) *OrderUpdateOne {
	if v != nil {
		_u.SetFeeOfficial(*v)
	}
	return _u
}

// AddFeeOfficial adds value to the "fee_official" field.
func (_u *OrderUpdateOne) AddFeeOfficial(v float64) *OrderUpdateOne {
	_u.mutation.AddFeeOfficial(v)
	return _u
}

// SetFeePlatform sets the "fee_platform" field.
func (_u *OrderUpdateOne) SetFeePlatform(v float64) *OrderUpdateOne {
	_u.mutation.ResetFeePlatform()
	_u.mutation.SetFeePlatform(v)
	return _u
}

// SetNillableFeePlatform sets the "fee_platform" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableFeePlatform(v *float64) *OrderUpdateOne {
	if v != nil {
		_u.SetFeePlatform(*v)
	}
	return _u
}

// AddFeePlatform adds value to the "fee_platform" field.
func (_u *OrderUpdateOne) AddFeePlatform(v float64) *OrderUpdateOne {
	_u.mutation.AddFeePlatform(v)
	return _u
}

// SetNetAmount sets the "net_amount" field.
func (_u *OrderUpdateOne) SetNetAmount(v float64) *OrderUpdateOne {
	_u.mutation.ResetNetAmount()
	_u.mutation.SetNetAmount(v)
	return _u
}

// SetNillableNetAmount sets the "net_amount" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableNetAmount(v *float64) *OrderUpdateOne {
	if v != nil {
		_u.SetNetAmount(*v)
	}
	return _u
}

// AddNetAmount adds value to the "net_amount" field.
func (_u *OrderUpdateOne) AddNetAmount(v float64) *OrderUpdateOne {
	_u.mutation.AddNetAmount(v)
	return _u
}

// SetTradeNo sets the "trade_no" field.
func (_u *OrderUpdateOne) SetTradeNo(v string) *OrderUpdateOne {
	_u.mutation.SetTradeNo(v)
	return _u
}

// SetNillableTradeNo sets the "trade_no" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableTradeNo(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetTradeNo(*v)
	}
	return _u
}

// ClearTradeNo clears the value of the "trade_no" field.
func (_u *OrderUpdateOne) ClearTradeNo() *OrderUpdateOne {
	_u.mutation.ClearTradeNo()
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrderUpdateOne) SetStatus(v order.Status) *OrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableStatus(v *order.Status) *OrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNotifyURL sets the "notify_url" field.
func (_u *OrderUpdateOne) SetNotifyURL(v string) *OrderUpdateOne {
	_u.mutation.SetNotifyURL(v)
	return _u
}

// SetNillableNotifyURL sets the "notify_url" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableNotifyURL(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetNotifyURL(*v)
	}
	return _u
}

// SetProviderSnapshot sets the "provider_snapshot" field.
func (_u *OrderUpdateOne) SetProviderSnapshot(v string) *OrderUpdateOne {
	_u.mutation.SetProviderSnapshot(v)
	return _u
}

// SetNillableProviderSnapshot sets the "provider_snapshot" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableProviderSnapshot(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetProviderSnapshot(*v)
	}
	return _u
}

// ClearProviderSnapshot clears the value of the "provider_snapshot" field.
func (_u *OrderUpdateOne) ClearProviderSnapshot() *OrderUpdateOne {
	_u.mutation.ClearProviderSnapshot()
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *OrderUpdateOne) SetPaidAt(v time.Time) *OrderUpdateOne {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillablePaidAt(v *time.Time) *OrderUpdateOne {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *OrderUpdateOne) ClearPaidAt() *OrderUpdateOne {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetAPITradeNo sets the "api_trade_no" field.
func (_u *OrderUpdateOne) SetAPITradeNo(v string) *OrderUpdateOne {
	_u.mutation.SetAPITradeNo(v)
	return _u
}

// SetNillableAPITradeNo sets the "api_trade_no" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableAPITradeNo(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetAPITradeNo(*v)
	}
	return _u
}

// ClearAPITradeNo clears the value of the "api_trade_no" field.
func (_u *OrderUpdateOne) ClearAPITradeNo() *OrderUpdateOne {
	_u.mutation.ClearAPITradeNo()
	return _u
}

// SetBuyer sets the "buyer" field.
func (_u *OrderUpdateOne) SetBuyer(v string) *OrderUpdateOne {
	_u.mutation.SetBuyer(v)
	return _u
}

// SetNillableBuyer sets the "buyer" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableBuyer(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetBuyer(*v)
	}
	return _u
}

// ClearBuyer clears the value of the "buyer" field.
func (_u *OrderUpdateOne) ClearBuyer() *OrderUpdateOne {
	_u.mutation.ClearBuyer()
	return _u
}

// SetParam sets the "param" field.
func (_u *OrderUpdateOne) SetParam(v string) *OrderUpdateOne {
	_u.mutation.SetParam(v)
	return _u
}

// SetNillableParam sets the "param" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableParam(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetParam(*v)
	}
	return _u
}

// ClearParam clears the value of the "param" field.
func (_u *OrderUpdateOne) ClearParam() *OrderUpdateOne {
	_u.mutation.ClearParam()
	return _u
}

// SetName sets the "name" field.
func (_u *OrderUpdateOne) SetName(v string) *OrderUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableName(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *OrderUpdateOne) ClearName() *OrderUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetClientip sets the "clientip" field.
func (_u *OrderUpdateOne) SetClientip(v string) *OrderUpdateOne {
	_u.mutation.SetClientip(v)
	return _u
}

// SetNillableClientip sets the "clientip" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableClientip(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetClientip(*v)
	}
	return _u
}

// ClearClientip clears the value of the "clientip" field.
func (_u *OrderUpdateOne) ClearClientip() *OrderUpdateOne {
	_u.mutation.ClearClientip()
	return _u
}

// SetReturnURL sets the "return_url" field.
func (_u *OrderUpdateOne) SetReturnURL(v string) *OrderUpdateOne {
	_u.mutation.SetReturnURL(v)
	return _u
}

// SetNillableReturnURL sets the "return_url" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableReturnURL(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetReturnURL(*v)
	}
	return _u
}

// ClearReturnURL clears the value of the "return_url" field.
func (_u *OrderUpdateOne) ClearReturnURL() *OrderUpdateOne {
	_u.mutation.ClearReturnURL()
	return _u
}

// SetDevice sets the "device" field.
func (_u *OrderUpdateOne) SetDevice(v string) *OrderUpdateOne {
	_u.mutation.SetDevice(v)
	return _u
}

// SetNillableDevice sets the "device" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableDevice(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetDevice(*v)
	}
	return _u
}

// ClearDevice clears the value of the "device" field.
func (_u *OrderUpdateOne) ClearDevice() *OrderUpdateOne {
	_u.mutation.ClearDevice()
	return _u
}

// SetMethod sets the "method" field.
func (_u *OrderUpdateOne) SetMethod(v string) *OrderUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableMethod(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// ClearMethod clears the value of the "method" field.
func (_u *OrderUpdateOne) ClearMethod() *OrderUpdateOne {
	_u.mutation.ClearMethod()
	return _u
}

// SetSubOpenid sets the "sub_openid" field.
func (_u *OrderUpdateOne) SetSubOpenid(v string) *OrderUpdateOne {
	_u.mutation.SetSubOpenid(v)
	return _u
}

// SetNillableSubOpenid sets the "sub_openid" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableSubOpenid(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetSubOpenid(*v)
	}
	return _u
}

// ClearSubOpenid clears the value of the "sub_openid" field.
func (_u *OrderUpdateOne) ClearSubOpenid() *OrderUpdateOne {
	_u.mutation.ClearSubOpenid()
	return _u
}

// SetSubAppid sets the "sub_appid" field.
func (_u *OrderUpdateOne) SetSubAppid(v string) *OrderUpdateOne {
	_u.mutation.SetSubAppid(v)
	return _u
}

// SetNillableSubAppid sets the "sub_appid" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableSubAppid(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetSubAppid(*v)
	}
	return _u
}

// ClearSubAppid clears the value of the "sub_appid" field.
func (_u *OrderUpdateOne) ClearSubAppid() *OrderUpdateOne {
	_u.mutation.ClearSubAppid()
	return _u
}

// SetAuthCode sets the "auth_code" field.
func (_u *OrderUpdateOne) SetAuthCode(v string) *OrderUpdateOne {
	_u.mutation.SetAuthCode(v)
	return _u
}

// SetNillableAuthCode sets the "auth_code" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableAuthCode(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetAuthCode(*v)
	}
	return _u
}

// ClearAuthCode clears the value of the "auth_code" field.
func (_u *OrderUpdateOne) ClearAuthCode() *OrderUpdateOne {
	_u.mutation.ClearAuthCode()
	return _u
}

// SetRefundMoney sets the "refund_money" field.
func (_u *OrderUpdateOne) SetRefundMoney(v float64) *OrderUpdateOne {
	_u.mutation.ResetRefundMoney()
	_u.mutation.SetRefundMoney(v)
	return _u
}

// SetNillableRefundMoney sets the "refund_money" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableRefundMoney(v *float64) *OrderUpdateOne {
	if v != nil {
		_u.SetRefundMoney(*v)
	}
	return _u
}

// AddRefundMoney adds value to the "refund_money" field.
func (_u *OrderUpdateOne) AddRefundMoney(v float64) *OrderUpdateOne {
	_u.mutation.AddRefundMoney(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *OrderUpdateOne) SetVersion(v int) *OrderUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableVersion(v *int) *OrderUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *OrderUpdateOne) AddVersion(v int) *OrderUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrderUpdateOne) SetUpdatedAt(v time.Time) *OrderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProduct sets the "product" edge to the Product entity.
func (_u *OrderUpdateOne) SetProduct(v *Product) *OrderUpdateOne {
	return _u.SetProductID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *OrderUpdateOne) SetUser(v *User) *OrderUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the OrderMutation object of the builder.
func (_u *OrderUpdateOne) Mutation() *OrderMutation {
	return _u.mutation
}

// ClearProduct clears the "product" edge to the Product entity.
func (_u *OrderUpdateOne) ClearProduct() *OrderUpdateOne {
	_u.mutation.ClearProduct()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *OrderUpdateOne) ClearUser() *OrderUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the OrderUpdate builder.
func (_u *OrderUpdateOne) Where(ps ...predicate.Order) *OrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrderUpdateOne) Select(field string, fields ...string) *OrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Order entity.
func (_u *OrderUpdateOne) Save(ctx context.Context) (*Order, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderUpdateOne) SaveX(ctx context.Context) *Order {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := order.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderUpdateOne) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := order.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "Order.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := order.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Order.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := order.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Order.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NotifyURL(); ok {
		if err := order.NotifyURLValidator(v); err != nil {
			return &ValidationError{Name: "notify_url", err: fmt.Errorf(`ent: validator failed for field "Order.notify_url": %w`, err)}
		}
	}
	if _u.mutation.ProductCleared() && len(_u.mutation.ProductIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Order.product"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Order.user"`)
	}
	return nil
}

func (_u *OrderUpdateOne) sqlSave(ctx context.Context) (_node *Order, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Order.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, order.FieldID)
		for _, f := range fields {
			if !order.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != order.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(order.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(order.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(order.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(order.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FeeOfficial(); ok {
		_spec.SetField(order.FieldFeeOfficial, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFeeOfficial(); ok {
		_spec.AddField(order.FieldFeeOfficial, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FeePlatform(); ok {
		_spec.SetField(order.FieldFeePlatform, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFeePlatform(); ok {
		_spec.AddField(order.FieldFeePlatform, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.NetAmount(); ok {
		_spec.SetField(order.FieldNetAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedNetAmount(); ok {
		_spec.AddField(order.FieldNetAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TradeNo(); ok {
		_spec.SetField(order.FieldTradeNo, field.TypeString, value)
	}
	if _u.mutation.TradeNoCleared() {
		_spec.ClearField(order.FieldTradeNo, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.NotifyURL(); ok {
		_spec.SetField(order.FieldNotifyURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderSnapshot(); ok {
		_spec.SetField(order.FieldProviderSnapshot, field.TypeString, value)
	}
	if _u.mutation.ProviderSnapshotCleared() {
		_spec.ClearField(order.FieldProviderSnapshot, field.TypeString)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(order.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(order.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.APITradeNo(); ok {
		_spec.SetField(order.FieldAPITradeNo, field.TypeString, value)
	}
	if _u.mutation.APITradeNoCleared() {
		_spec.ClearField(order.FieldAPITradeNo, field.TypeString)
	}
	if value, ok := _u.mutation.Buyer(); ok {
		_spec.SetField(order.FieldBuyer, field.TypeString, value)
	}
	if _u.mutation.BuyerCleared() {
		_spec.ClearField(order.FieldBuyer, field.TypeString)
	}
	if value, ok := _u.mutation.Param(); ok {
		_spec.SetField(order.FieldParam, field.TypeString, value)
	}
	if _u.mutation.ParamCleared() {
		_spec.ClearField(order.FieldParam, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(order.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(order.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Clientip(); ok {
		_spec.SetField(order.FieldClientip, field.TypeString, value)
	}
	if _u.mutation.ClientipCleared() {
		_spec.ClearField(order.FieldClientip, field.TypeString)
	}
	if value, ok := _u.mutation.ReturnURL(); ok {
		_spec.SetField(order.FieldReturnURL, field.TypeString, value)
	}
	if _u.mutation.ReturnURLCleared() {
		_spec.ClearField(order.FieldReturnURL, field.TypeString)
	}
	if value, ok := _u.mutation.Device(); ok {
		_spec.SetField(order.FieldDevice, field.TypeString, value)
	}
	if _u.mutation.DeviceCleared() {
		_spec.ClearField(order.FieldDevice, field.TypeString)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(order.FieldMethod, field.TypeString, value)
	}
	if _u.mutation.MethodCleared() {
		_spec.ClearField(order.FieldMethod, field.TypeString)
	}
	if value, ok := _u.mutation.SubOpenid(); ok {
		_spec.SetField(order.FieldSubOpenid, field.TypeString, value)
	}
	if _u.mutation.SubOpenidCleared() {
		_spec.ClearField(order.FieldSubOpenid, field.TypeString)
	}
	if value, ok := _u.mutation.SubAppid(); ok {
		_spec.SetField(order.FieldSubAppid, field.TypeString, value)
	}
	if _u.mutation.SubAppidCleared() {
		_spec.ClearField(order.FieldSubAppid, field.TypeString)
	}
	if value, ok := _u.mutation.AuthCode(); ok {
		_spec.SetField(order.FieldAuthCode, field.TypeString, value)
	}
	if _u.mutation.AuthCodeCleared() {
		_spec.ClearField(order.FieldAuthCode, field.TypeString)
	}
	if value, ok := _u.mutation.RefundMoney(); ok {
		_spec.SetField(order.FieldRefundMoney, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRefundMoney(); ok {
		_spec.AddField(order.FieldRefundMoney, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(order.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(order.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.ProductTable,
			Columns: []string{order.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.ProductTable,
			Columns: []string{order.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Order{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
