// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"epay/ent/platformconfig"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PlatformConfigCreate is the builder for creating a PlatformConfig entity.
type PlatformConfigCreate struct {
	config
	mutation *PlatformConfigMutation
	hooks    []Hook
}

// SetKey sets the "key" field.
func (_c *PlatformConfigCreate) SetKey(v string) *PlatformConfigCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *PlatformConfigCreate) SetValue(v string) *PlatformConfigCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_c *PlatformConfigCreate) SetNillableValue(v *string) *PlatformConfigCreate {
	if v != nil {
		_c.SetValue(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *PlatformConfigCreate) SetDescription(v string) *PlatformConfigCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *PlatformConfigCreate) SetNillableDescription(v *string) *PlatformConfigCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PlatformConfigCreate) SetCreatedAt(v time.Time) *PlatformConfigCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PlatformConfigCreate) SetNillableCreatedAt(v *time.Time) *PlatformConfigCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PlatformConfigCreate) SetUpdatedAt(v time.Time) *PlatformConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PlatformConfigCreate) SetNillableUpdatedAt(v *time.Time) *PlatformConfigCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PlatformConfigCreate) SetID(v uuid.UUID) *PlatformConfigCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PlatformConfigCreate) SetNillableID(v *uuid.UUID) *PlatformConfigCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the PlatformConfigMutation object of the builder.
func (_c *PlatformConfigCreate) Mutation() *PlatformConfigMutation {
	return _c.mutation
}

// Save creates the PlatformConfig in the database.
func (_c *PlatformConfigCreate) Save(ctx context.Context) (*PlatformConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PlatformConfigCreate) SaveX(ctx context.Context) *PlatformConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlatformConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlatformConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PlatformConfigCreate) defaults() {
	if _, ok := _c.mutation.Value(); !ok {
		v := platformconfig.DefaultValue
		_c.mutation.SetValue(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := platformconfig.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := platformconfig.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := platformconfig.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := platformconfig.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PlatformConfigCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "PlatformConfig.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := platformconfig.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "PlatformConfig.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PlatformConfig.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PlatformConfig.updated_at"`)}
	}
	return nil
}

func (_c *PlatformConfigCreate) sqlSave(ctx context.Context) (*PlatformConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PlatformConfigCreate) createSpec() (*PlatformConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &PlatformConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(platformconfig.Table, sqlgraph.NewFieldSpec(platformconfig.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(platformconfig.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(platformconfig.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(platformconfig.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(platformconfig.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(platformconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// PlatformConfigCreateBulk is the builder for creating many PlatformConfig entities in bulk.
type PlatformConfigCreateBulk struct {
	config
	err      error
	builders []*PlatformConfigCreate
}

// Save creates the PlatformConfig entities in the database.
func (_c *PlatformConfigCreateBulk) Save(ctx context.Context) ([]*PlatformConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PlatformConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlatformConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PlatformConfigCreateBulk) SaveX(ctx context.Context) []*PlatformConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlatformConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlatformConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
