// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"epay/ent/platformconfig"
	"epay/ent/predicate"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PlatformConfigUpdate is the builder for updating PlatformConfig entities.
type PlatformConfigUpdate struct {
	config
	hooks    []Hook
	mutation *PlatformConfigMutation
}

// Where appends a list predicates to the PlatformConfigUpdate builder.
func (_u *PlatformConfigUpdate) Where(ps ...predicate.PlatformConfig) *PlatformConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKey sets the "key" field.
func (_u *PlatformConfigUpdate) SetKey(v string) *PlatformConfigUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *PlatformConfigUpdate) SetNillableKey(v *string) *PlatformConfigUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *PlatformConfigUpdate) SetValue(v string) *PlatformConfigUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *PlatformConfigUpdate) SetNillableValue(v *string) *PlatformConfigUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// ClearValue clears the value of the "value" field.
func (_u *PlatformConfigUpdate) ClearValue() *PlatformConfigUpdate {
	_u.mutation.ClearValue()
	return _u
}

// SetDescription sets the "description" field.
func (_u *PlatformConfigUpdate) SetDescription(v string) *PlatformConfigUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PlatformConfigUpdate) SetNillableDescription(v *string) *PlatformConfigUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PlatformConfigUpdate) ClearDescription() *PlatformConfigUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PlatformConfigUpdate) SetUpdatedAt(v time.Time) *PlatformConfigUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PlatformConfigMutation object of the builder.
func (_u *PlatformConfigUpdate) Mutation() *PlatformConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PlatformConfigUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlatformConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PlatformConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlatformConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PlatformConfigUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := platformconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlatformConfigUpdate) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := platformconfig.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "PlatformConfig.key": %w`, err)}
		}
	}
	return nil
}

func (_u *PlatformConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(platformconfig.Table, platformconfig.Columns, sqlgraph.NewFieldSpec(platformconfig.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(platformconfig.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(platformconfig.FieldValue, field.TypeString, value)
	}
	if _u.mutation.ValueCleared() {
		_spec.ClearField(platformconfig.FieldValue, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(platformconfig.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(platformconfig.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(platformconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{platformconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PlatformConfigUpdateOne is the builder for updating a single PlatformConfig entity.
type PlatformConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlatformConfigMutation
}

// SetKey sets the "key" field.
func (_u *PlatformConfigUpdateOne) SetKey(v string) *PlatformConfigUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *PlatformConfigUpdateOne) SetNillableKey(v *string) *PlatformConfigUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *PlatformConfigUpdateOne) SetValue(v string) *PlatformConfigUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *PlatformConfigUpdateOne) SetNillableValue(v *string) *PlatformConfigUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// ClearValue clears the value of the "value" field.
func (_u *PlatformConfigUpdateOne) ClearValue() *PlatformConfigUpdateOne {
	_u.mutation.ClearValue()
	return _u
}

// SetDescription sets the "description" field.
func (_u *PlatformConfigUpdateOne) SetDescription(v string) *PlatformConfigUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PlatformConfigUpdateOne) SetNillableDescription(v *string) *PlatformConfigUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PlatformConfigUpdateOne) ClearDescription() *PlatformConfigUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PlatformConfigUpdateOne) SetUpdatedAt(v time.Time) *PlatformConfigUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PlatformConfigMutation object of the builder.
func (_u *PlatformConfigUpdateOne) Mutation() *PlatformConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the PlatformConfigUpdate builder.
func (_u *PlatformConfigUpdateOne) Where(ps ...predicate.PlatformConfig) *PlatformConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PlatformConfigUpdateOne) Select(field string, fields ...string) *PlatformConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PlatformConfig entity.
func (_u *PlatformConfigUpdateOne) Save(ctx context.Context) (*PlatformConfig, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlatformConfigUpdateOne) SaveX(ctx context.Context) *PlatformConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PlatformConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlatformConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PlatformConfigUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := platformconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlatformConfigUpdateOne) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := platformconfig.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "PlatformConfig.key": %w`, err)}
		}
	}
	return nil
}

func (_u *PlatformConfigUpdateOne) sqlSave(ctx context.Context) (_node *PlatformConfig, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(platformconfig.Table, platformconfig.Columns, sqlgraph.NewFieldSpec(platformconfig.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PlatformConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, platformconfig.FieldID)
		for _, f := range fields {
			if !platformconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != platformconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(platformconfig.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(platformconfig.FieldValue, field.TypeString, value)
	}
	if _u.mutation.ValueCleared() {
		_spec.ClearField(platformconfig.FieldValue, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(platformconfig.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(platformconfig.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(platformconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &PlatformConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{platformconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
