// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"epay/ent/order"
	"epay/ent/product"
	"epay/ent/user"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ProductCreate is the builder for creating a Product entity.
type ProductCreate struct {
	config
	mutation *ProductMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *ProductCreate) SetUserID(v uuid.UUID) *ProductCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPid sets the "pid" field.
func (_c *ProductCreate) SetPid(v int) *ProductCreate {
	_c.mutation.SetPid(v)
	return _c
}

// SetPkey sets the "pkey" field.
func (_c *ProductCreate) SetPkey(v string) *ProductCreate {
	_c.mutation.SetPkey(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ProductCreate) SetName(v string) *ProductCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ProductCreate) SetDescription(v string) *ProductCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ProductCreate) SetNillableDescription(v *string) *ProductCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetNotifyURL sets the "notify_url" field.
func (_c *ProductCreate) SetNotifyURL(v string) *ProductCreate {
	_c.mutation.SetNotifyURL(v)
	return _c
}

// SetNillableNotifyURL sets the "notify_url" field if the given value is not nil.
func (_c *ProductCreate) SetNillableNotifyURL(v *string) *ProductCreate {
	if v != nil {
		_c.SetNotifyURL(*v)
	}
	return _c
}

// SetReturnURL sets the "return_url" field.
func (_c *ProductCreate) SetReturnURL(v string) *ProductCreate {
	_c.mutation.SetReturnURL(v)
	return _c
}

// SetNillableReturnURL sets the "return_url" field if the given value is not nil.
func (_c *ProductCreate) SetNillableReturnURL(v *string) *ProductCreate {
	if v != nil {
		_c.SetReturnURL(*v)
	}
	return _c
}

// SetFeeRate sets the "fee_rate" field.
func (_c *ProductCreate) SetFeeRate(v float64) *ProductCreate {
	_c.mutation.SetFeeRate(v)
	return _c
}

// SetNillableFeeRate sets the "fee_rate" field if the given value is not nil.
func (_c *ProductCreate) SetNillableFeeRate(v *float64) *ProductCreate {
	if v != nil {
		_c.SetFeeRate(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ProductCreate) SetStatus(v product.Status) *ProductCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ProductCreate) SetNillableStatus(v *product.Status) *ProductCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetKeytype sets the "keytype" field.
func (_c *ProductCreate) SetKeytype(v int) *ProductCreate {
	_c.mutation.SetKeytype(v)
	return _c
}

// SetNillableKeytype sets the "keytype" field if the given value is not nil.
func (_c *ProductCreate) SetNillableKeytype(v *int) *ProductCreate {
	if v != nil {
		_c.SetKeytype(*v)
	}
	return _c
}

// SetPublicKey sets the "public_key" field.
func (_c *ProductCreate) SetPublicKey(v string) *ProductCreate {
	_c.mutation.SetPublicKey(v)
	return _c
}

// SetNillablePublicKey sets the "public_key" field if the given value is not nil.
func (_c *ProductCreate) SetNillablePublicKey(v *string) *ProductCreate {
	if v != nil {
		_c.SetPublicKey(*v)
	}
	return _c
}

// SetRefundEnabled sets the "refund_enabled" field.
func (_c *ProductCreate) SetRefundEnabled(v bool) *ProductCreate {
	_c.mutation.SetRefundEnabled(v)
	return _c
}

// SetNillableRefundEnabled sets the "refund_enabled" field if the given value is not nil.
func (_c *ProductCreate) SetNillableRefundEnabled(v *bool) *ProductCreate {
	if v != nil {
		_c.SetRefundEnabled(*v)
	}
	return _c
}

// SetTransferEnabled sets the "transfer_enabled" field.
func (_c *ProductCreate) SetTransferEnabled(v bool) *ProductCreate {
	_c.mutation.SetTransferEnabled(v)
	return _c
}

// SetNillableTransferEnabled sets the "transfer_enabled" field if the given value is not nil.
func (_c *ProductCreate) SetNillableTransferEnabled(v *bool) *ProductCreate {
	if v != nil {
		_c.SetTransferEnabled(*v)
	}
	return _c
}

// SetMode sets the "mode" field.
func (_c *ProductCreate) SetMode(v int) *ProductCreate {
	_c.mutation.SetMode(v)
	return _c
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_c *ProductCreate) SetNillableMode(v *int) *ProductCreate {
	if v != nil {
		_c.SetMode(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProductCreate) SetCreatedAt(v time.Time) *ProductCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProductCreate) SetNillableCreatedAt(v *time.Time) *ProductCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProductCreate) SetUpdatedAt(v time.Time) *ProductCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProductCreate) SetNillableUpdatedAt(v *time.Time) *ProductCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProductCreate) SetID(v uuid.UUID) *ProductCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ProductCreate) SetNillableID(v *uuid.UUID) *ProductCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ProductCreate) SetUser(v *User) *ProductCreate {
	return _c.SetUserID(v.ID)
}

// AddOrderIDs adds the "orders" edge to the Order entity by IDs.
func (_c *ProductCreate) AddOrderIDs(ids ...uuid.UUID) *ProductCreate {
	_c.mutation.AddOrderIDs(ids...)
	return _c
}

// AddOrders adds the "orders" edges to the Order entity.
func (_c *ProductCreate) AddOrders(v ...*Order) *ProductCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOrderIDs(ids...)
}

// Mutation returns the ProductMutation object of the builder.
func (_c *ProductCreate) Mutation() *ProductMutation {
	return _c.mutation
}

// Save creates the Product in the database.
func (_c *ProductCreate) Save(ctx context.Context) (*Product, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProductCreate) SaveX(ctx context.Context) *Product {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProductCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProductCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProductCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := product.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.NotifyURL(); !ok {
		v := product.DefaultNotifyURL
		_c.mutation.SetNotifyURL(v)
	}
	if _, ok := _c.mutation.ReturnURL(); !ok {
		v := product.DefaultReturnURL
		_c.mutation.SetReturnURL(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := product.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Keytype(); !ok {
		v := product.DefaultKeytype
		_c.mutation.SetKeytype(v)
	}
	if _, ok := _c.mutation.PublicKey(); !ok {
		v := product.DefaultPublicKey
		_c.mutation.SetPublicKey(v)
	}
	if _, ok := _c.mutation.RefundEnabled(); !ok {
		v := product.DefaultRefundEnabled
		_c.mutation.SetRefundEnabled(v)
	}
	if _, ok := _c.mutation.TransferEnabled(); !ok {
		v := product.DefaultTransferEnabled
		_c.mutation.SetTransferEnabled(v)
	}
	if _, ok := _c.mutation.Mode(); !ok {
		v := product.DefaultMode
		_c.mutation.SetMode(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := product.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := product.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := product.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProductCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Product.user_id"`)}
	}
	if _, ok := _c.mutation.Pid(); !ok {
		return &ValidationError{Name: "pid", err: errors.New(`ent: missing required field "Product.pid"`)}
	}
	if _, ok := _c.mutation.Pkey(); !ok {
		return &ValidationError{Name: "pkey", err: errors.New(`ent: missing required field "Product.pkey"`)}
	}
	if v, ok := _c.mutation.Pkey(); ok {
		if err := product.PkeyValidator(v); err != nil {
			return &ValidationError{Name: "pkey", err: fmt.Errorf(`ent: validator failed for field "Product.pkey": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Product.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := product.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Product.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Product.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := product.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Product.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Keytype(); !ok {
		return &ValidationError{Name: "keytype", err: errors.New(`ent: missing required field "Product.keytype"`)}
	}
	if _, ok := _c.mutation.RefundEnabled(); !ok {
		return &ValidationError{Name: "refund_enabled", err: errors.New(`ent: missing required field "Product.refund_enabled"`)}
	}
	if _, ok := _c.mutation.TransferEnabled(); !ok {
		return &ValidationError{Name: "transfer_enabled", err: errors.New(`ent: missing required field "Product.transfer_enabled"`)}
	}
	if _, ok := _c.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "Product.mode"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Product.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Product.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Product.user"`)}
	}
	return nil
}

func (_c *ProductCreate) sqlSave(ctx context.Context) (*Product, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProductCreate) createSpec() (*Product, *sqlgraph.CreateSpec) {
	var (
		_node = &Product{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(product.Table, sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Pid(); ok {
		_spec.SetField(product.FieldPid, field.TypeInt, value)
		_node.Pid = value
	}
	if value, ok := _c.mutation.Pkey(); ok {
		_spec.SetField(product.FieldPkey, field.TypeString, value)
		_node.Pkey = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(product.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(product.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.NotifyURL(); ok {
		_spec.SetField(product.FieldNotifyURL, field.TypeString, value)
		_node.NotifyURL = value
	}
	if value, ok := _c.mutation.ReturnURL(); ok {
		_spec.SetField(product.FieldReturnURL, field.TypeString, value)
		_node.ReturnURL = value
	}
	if value, ok := _c.mutation.FeeRate(); ok {
		_spec.SetField(product.FieldFeeRate, field.TypeFloat64, value)
		_node.FeeRate = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(product.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Keytype(); ok {
		_spec.SetField(product.FieldKeytype, field.TypeInt, value)
		_node.Keytype = value
	}
	if value, ok := _c.mutation.PublicKey(); ok {
		_spec.SetField(product.FieldPublicKey, field.TypeString, value)
		_node.PublicKey = value
	}
	if value, ok := _c.mutation.RefundEnabled(); ok {
		_spec.SetField(product.FieldRefundEnabled, field.TypeBool, value)
		_node.RefundEnabled = value
	}
	if value, ok := _c.mutation.TransferEnabled(); ok {
		_spec.SetField(product.FieldTransferEnabled, field.TypeBool, value)
		_node.TransferEnabled = value
	}
	if value, ok := _c.mutation.Mode(); ok {
		_spec.SetField(product.FieldMode, field.TypeInt, value)
		_node.Mode = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(product.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(product.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   product.UserTable,
			Columns: []string{product.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   product.OrdersTable,
			Columns: []string{product.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProductCreateBulk is the builder for creating many Product entities in bulk.
type ProductCreateBulk struct {
	config
	err      error
	builders []*ProductCreate
}

// Save creates the Product entities in the database.
func (_c *ProductCreateBulk) Save(ctx context.Context) ([]*Product, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Product, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProductMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProductCreateBulk) SaveX(ctx context.Context) []*Product {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProductCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProductCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
