// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"epay/ent/merchant"
	"epay/ent/refund"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// RefundCreate is the builder for creating a Refund entity.
type RefundCreate struct {
	config
	mutation *RefundMutation
	hooks    []Hook
}

// SetRefundNo sets the "refund_no" field.
func (_c *RefundCreate) SetRefundNo(v string) *RefundCreate {
	_c.mutation.SetRefundNo(v)
	return _c
}

// SetOutRefundNo sets the "out_refund_no" field.
func (_c *RefundCreate) SetOutRefundNo(v string) *RefundCreate {
	_c.mutation.SetOutRefundNo(v)
	return _c
}

// SetNillableOutRefundNo sets the "out_refund_no" field if the given value is not nil.
func (_c *RefundCreate) SetNillableOutRefundNo(v *string) *RefundCreate {
	if v != nil {
		_c.SetOutRefundNo(*v)
	}
	return _c
}

// SetTradeNo sets the "trade_no" field.
func (_c *RefundCreate) SetTradeNo(v string) *RefundCreate {
	_c.mutation.SetTradeNo(v)
	return _c
}

// SetMerchantID sets the "merchant_id" field.
func (_c *RefundCreate) SetMerchantID(v uuid.UUID) *RefundCreate {
	_c.mutation.SetMerchantID(v)
	return _c
}

// SetMoney sets the "money" field.
func (_c *RefundCreate) SetMoney(v float64) *RefundCreate {
	_c.mutation.SetMoney(v)
	return _c
}

// SetReduceMoney sets the "reduce_money" field.
func (_c *RefundCreate) SetReduceMoney(v float64) *RefundCreate {
	_c.mutation.SetReduceMoney(v)
	return _c
}

// SetNillableReduceMoney sets the "reduce_money" field if the given value is not nil.
func (_c *RefundCreate) SetNillableReduceMoney(v *float64) *RefundCreate {
	if v != nil {
		_c.SetReduceMoney(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *RefundCreate) SetStatus(v refund.Status) *RefundCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *RefundCreate) SetNillableStatus(v *refund.Status) *RefundCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetMessage sets the "message" field.
func (_c *RefundCreate) SetMessage(v string) *RefundCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_c *RefundCreate) SetNillableMessage(v *string) *RefundCreate {
	if v != nil {
		_c.SetMessage(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RefundCreate) SetCreatedAt(v time.Time) *RefundCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RefundCreate) SetNillableCreatedAt(v *time.Time) *RefundCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RefundCreate) SetUpdatedAt(v time.Time) *RefundCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RefundCreate) SetNillableUpdatedAt(v *time.Time) *RefundCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *RefundCreate) SetFinishedAt(v time.Time) *RefundCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *RefundCreate) SetNillableFinishedAt(v *time.Time) *RefundCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RefundCreate) SetID(v uuid.UUID) *RefundCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RefundCreate) SetNillableID(v *uuid.UUID) *RefundCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetMerchant sets the "merchant" edge to the Merchant entity.
func (_c *RefundCreate) SetMerchant(v *Merchant) *RefundCreate {
	return _c.SetMerchantID(v.ID)
}

// Mutation returns the RefundMutation object of the builder.
func (_c *RefundCreate) Mutation() *RefundMutation {
	return _c.mutation
}

// Save creates the Refund in the database.
func (_c *RefundCreate) Save(ctx context.Context) (*Refund, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RefundCreate) SaveX(ctx context.Context) *Refund {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RefundCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RefundCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RefundCreate) defaults() {
	if _, ok := _c.mutation.OutRefundNo(); !ok {
		v := refund.DefaultOutRefundNo
		_c.mutation.SetOutRefundNo(v)
	}
	if _, ok := _c.mutation.ReduceMoney(); !ok {
		v := refund.DefaultReduceMoney
		_c.mutation.SetReduceMoney(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := refund.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Message(); !ok {
		v := refund.DefaultMessage
		_c.mutation.SetMessage(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := refund.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := refund.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := refund.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RefundCreate) check() error {
	if _, ok := _c.mutation.RefundNo(); !ok {
		return &ValidationError{Name: "refund_no", err: errors.New(`ent: missing required field "Refund.refund_no"`)}
	}
	if v, ok := _c.mutation.RefundNo(); ok {
		if err := refund.RefundNoValidator(v); err != nil {
			return &ValidationError{Name: "refund_no", err: fmt.Errorf(`ent: validator failed for field "Refund.refund_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TradeNo(); !ok {
		return &ValidationError{Name: "trade_no", err: errors.New(`ent: missing required field "Refund.trade_no"`)}
	}
	if v, ok := _c.mutation.TradeNo(); ok {
		if err := refund.TradeNoValidator(v); err != nil {
			return &ValidationError{Name: "trade_no", err: fmt.Errorf(`ent: validator failed for field "Refund.trade_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MerchantID(); !ok {
		return &ValidationError{Name: "merchant_id", err: errors.New(`ent: missing required field "Refund.merchant_id"`)}
	}
	if _, ok := _c.mutation.Money(); !ok {
		return &ValidationError{Name: "money", err: errors.New(`ent: missing required field "Refund.money"`)}
	}
	if _, ok := _c.mutation.ReduceMoney(); !ok {
		return &ValidationError{Name: "reduce_money", err: errors.New(`ent: missing required field "Refund.reduce_money"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Refund.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := refund.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Refund.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Refund.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Refund.updated_at"`)}
	}
	if len(_c.mutation.MerchantIDs()) == 0 {
		return &ValidationError{Name: "merchant", err: errors.New(`ent: missing required edge "Refund.merchant"`)}
	}
	return nil
}

func (_c *RefundCreate) sqlSave(ctx context.Context) (*Refund, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RefundCreate) createSpec() (*Refund, *sqlgraph.CreateSpec) {
	var (
		_node = &Refund{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(refund.Table, sqlgraph.NewFieldSpec(refund.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.RefundNo(); ok {
		_spec.SetField(refund.FieldRefundNo, field.TypeString, value)
		_node.RefundNo = value
	}
	if value, ok := _c.mutation.OutRefundNo(); ok {
		_spec.SetField(refund.FieldOutRefundNo, field.TypeString, value)
		_node.OutRefundNo = value
	}
	if value, ok := _c.mutation.TradeNo(); ok {
		_spec.SetField(refund.FieldTradeNo, field.TypeString, value)
		_node.TradeNo = value
	}
	if value, ok := _c.mutation.Money(); ok {
		_spec.SetField(refund.FieldMoney, field.TypeFloat64, value)
		_node.Money = value
	}
	if value, ok := _c.mutation.ReduceMoney(); ok {
		_spec.SetField(refund.FieldReduceMoney, field.TypeFloat64, value)
		_node.ReduceMoney = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(refund.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(refund.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(refund.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(refund.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(refund.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	if nodes := _c.mutation.MerchantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   refund.MerchantTable,
			Columns: []string{refund.MerchantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(merchant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MerchantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RefundCreateBulk is the builder for creating many Refund entities in bulk.
type RefundCreateBulk struct {
	config
	err      error
	builders []*RefundCreate
}

// Save creates the Refund entities in the database.
func (_c *RefundCreateBulk) Save(ctx context.Context) ([]*Refund, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Refund, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RefundMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RefundCreateBulk) SaveX(ctx context.Context) []*Refund {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RefundCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RefundCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
