// Code generated by ent, DO NOT EDIT.

package ent

import (
	"epay/ent/admin"
	"epay/ent/order"
	"epay/ent/platformconfig"
	"epay/ent/product"
	"epay/ent/refund"
	"epay/ent/schema"
	"epay/ent/settlement"
	"epay/ent/user"
	"epay/ent/withdraw"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	adminFields := schema.Admin{}.Fields()
	_ = adminFields
	// adminDescUsername is the schema descriptor for username field.
	adminDescUsername := adminFields[1].Descriptor()
	// admin.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	admin.UsernameValidator = adminDescUsername.Validators[0].(func(string) error)
	// adminDescPasswordHash is the schema descriptor for password_hash field.
	adminDescPasswordHash := adminFields[2].Descriptor()
	// admin.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	admin.PasswordHashValidator = adminDescPasswordHash.Validators[0].(func(string) error)
	// adminDescCreatedAt is the schema descriptor for created_at field.
	adminDescCreatedAt := adminFields[3].Descriptor()
	// admin.DefaultCreatedAt holds the default value on creation for the created_at field.
	admin.DefaultCreatedAt = adminDescCreatedAt.Default.(func() time.Time)
	// adminDescUpdatedAt is the schema descriptor for updated_at field.
	adminDescUpdatedAt := adminFields[4].Descriptor()
	// admin.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	admin.DefaultUpdatedAt = adminDescUpdatedAt.Default.(func() time.Time)
	// admin.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	admin.UpdateDefaultUpdatedAt = adminDescUpdatedAt.UpdateDefault.(func() time.Time)
	// adminDescID is the schema descriptor for id field.
	adminDescID := adminFields[0].Descriptor()
	// admin.DefaultID holds the default value on creation for the id field.
	admin.DefaultID = adminDescID.Default.(func() uuid.UUID)
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescOrderNo is the schema descriptor for order_no field.
	orderDescOrderNo := orderFields[1].Descriptor()
	// order.OrderNoValidator is a validator for the "order_no" field. It is called by the builders before save.
	order.OrderNoValidator = orderDescOrderNo.Validators[0].(func(string) error)
	// orderDescFeeOfficial is the schema descriptor for fee_official field.
	orderDescFeeOfficial := orderFields[6].Descriptor()
	// order.DefaultFeeOfficial holds the default value on creation for the fee_official field.
	order.DefaultFeeOfficial = orderDescFeeOfficial.Default.(float64)
	// orderDescFeePlatform is the schema descriptor for fee_platform field.
	orderDescFeePlatform := orderFields[7].Descriptor()
	// order.DefaultFeePlatform holds the default value on creation for the fee_platform field.
	order.DefaultFeePlatform = orderDescFeePlatform.Default.(float64)
	// orderDescNetAmount is the schema descriptor for net_amount field.
	orderDescNetAmount := orderFields[8].Descriptor()
	// order.DefaultNetAmount holds the default value on creation for the net_amount field.
	order.DefaultNetAmount = orderDescNetAmount.Default.(float64)
	// orderDescTradeNo is the schema descriptor for trade_no field.
	orderDescTradeNo := orderFields[9].Descriptor()
	// order.DefaultTradeNo holds the default value on creation for the trade_no field.
	order.DefaultTradeNo = orderDescTradeNo.Default.(string)
	// orderDescNotifyURL is the schema descriptor for notify_url field.
	orderDescNotifyURL := orderFields[11].Descriptor()
	// order.NotifyURLValidator is a validator for the "notify_url" field. It is called by the builders before save.
	order.NotifyURLValidator = orderDescNotifyURL.Validators[0].(func(string) error)
	// orderDescProviderSnapshot is the schema descriptor for provider_snapshot field.
	orderDescProviderSnapshot := orderFields[12].Descriptor()
	// order.DefaultProviderSnapshot holds the default value on creation for the provider_snapshot field.
	order.DefaultProviderSnapshot = orderDescProviderSnapshot.Default.(string)
	// orderDescAPITradeNo is the schema descriptor for api_trade_no field.
	orderDescAPITradeNo := orderFields[14].Descriptor()
	// order.DefaultAPITradeNo holds the default value on creation for the api_trade_no field.
	order.DefaultAPITradeNo = orderDescAPITradeNo.Default.(string)
	// orderDescBuyer is the schema descriptor for buyer field.
	orderDescBuyer := orderFields[15].Descriptor()
	// order.DefaultBuyer holds the default value on creation for the buyer field.
	order.DefaultBuyer = orderDescBuyer.Default.(string)
	// orderDescParam is the schema descriptor for param field.
	orderDescParam := orderFields[16].Descriptor()
	// order.DefaultParam holds the default value on creation for the param field.
	order.DefaultParam = orderDescParam.Default.(string)
	// orderDescName is the schema descriptor for name field.
	orderDescName := orderFields[17].Descriptor()
	// order.DefaultName holds the default value on creation for the name field.
	order.DefaultName = orderDescName.Default.(string)
	// orderDescClientip is the schema descriptor for clientip field.
	orderDescClientip := orderFields[18].Descriptor()
	// order.DefaultClientip holds the default value on creation for the clientip field.
	order.DefaultClientip = orderDescClientip.Default.(string)
	// orderDescReturnURL is the schema descriptor for return_url field.
	orderDescReturnURL := orderFields[19].Descriptor()
	// order.DefaultReturnURL holds the default value on creation for the return_url field.
	order.DefaultReturnURL = orderDescReturnURL.Default.(string)
	// orderDescDevice is the schema descriptor for device field.
	orderDescDevice := orderFields[20].Descriptor()
	// order.DefaultDevice holds the default value on creation for the device field.
	order.DefaultDevice = orderDescDevice.Default.(string)
	// orderDescMethod is the schema descriptor for method field.
	orderDescMethod := orderFields[21].Descriptor()
	// order.DefaultMethod holds the default value on creation for the method field.
	order.DefaultMethod = orderDescMethod.Default.(string)
	// orderDescSubOpenid is the schema descriptor for sub_openid field.
	orderDescSubOpenid := orderFields[22].Descriptor()
	// order.DefaultSubOpenid holds the default value on creation for the sub_openid field.
	order.DefaultSubOpenid = orderDescSubOpenid.Default.(string)
	// orderDescSubAppid is the schema descriptor for sub_appid field.
	orderDescSubAppid := orderFields[23].Descriptor()
	// order.DefaultSubAppid holds the default value on creation for the sub_appid field.
	order.DefaultSubAppid = orderDescSubAppid.Default.(string)
	// orderDescAuthCode is the schema descriptor for auth_code field.
	orderDescAuthCode := orderFields[24].Descriptor()
	// order.DefaultAuthCode holds the default value on creation for the auth_code field.
	order.DefaultAuthCode = orderDescAuthCode.Default.(string)
	// orderDescRefundMoney is the schema descriptor for refund_money field.
	orderDescRefundMoney := orderFields[25].Descriptor()
	// order.DefaultRefundMoney holds the default value on creation for the refund_money field.
	order.DefaultRefundMoney = orderDescRefundMoney.Default.(float64)
	// orderDescVersion is the schema descriptor for version field.
	orderDescVersion := orderFields[26].Descriptor()
	// order.DefaultVersion holds the default value on creation for the version field.
	order.DefaultVersion = orderDescVersion.Default.(int)
	// orderDescCreatedAt is the schema descriptor for created_at field.
	orderDescCreatedAt := orderFields[27].Descriptor()
	// order.DefaultCreatedAt holds the default value on creation for the created_at field.
	order.DefaultCreatedAt = orderDescCreatedAt.Default.(func() time.Time)
	// orderDescUpdatedAt is the schema descriptor for updated_at field.
	orderDescUpdatedAt := orderFields[28].Descriptor()
	// order.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	order.DefaultUpdatedAt = orderDescUpdatedAt.Default.(func() time.Time)
	// order.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	order.UpdateDefaultUpdatedAt = orderDescUpdatedAt.UpdateDefault.(func() time.Time)
	// orderDescID is the schema descriptor for id field.
	orderDescID := orderFields[0].Descriptor()
	// order.DefaultID holds the default value on creation for the id field.
	order.DefaultID = orderDescID.Default.(func() uuid.UUID)
	platformconfigFields := schema.PlatformConfig{}.Fields()
	_ = platformconfigFields
	// platformconfigDescKey is the schema descriptor for key field.
	platformconfigDescKey := platformconfigFields[1].Descriptor()
	// platformconfig.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	platformconfig.KeyValidator = platformconfigDescKey.Validators[0].(func(string) error)
	// platformconfigDescValue is the schema descriptor for value field.
	platformconfigDescValue := platformconfigFields[2].Descriptor()
	// platformconfig.DefaultValue holds the default value on creation for the value field.
	platformconfig.DefaultValue = platformconfigDescValue.Default.(string)
	// platformconfigDescDescription is the schema descriptor for description field.
	platformconfigDescDescription := platformconfigFields[3].Descriptor()
	// platformconfig.DefaultDescription holds the default value on creation for the description field.
	platformconfig.DefaultDescription = platformconfigDescDescription.Default.(string)
	// platformconfigDescCreatedAt is the schema descriptor for created_at field.
	platformconfigDescCreatedAt := platformconfigFields[4].Descriptor()
	// platformconfig.DefaultCreatedAt holds the default value on creation for the created_at field.
	platformconfig.DefaultCreatedAt = platformconfigDescCreatedAt.Default.(func() time.Time)
	// platformconfigDescUpdatedAt is the schema descriptor for updated_at field.
	platformconfigDescUpdatedAt := platformconfigFields[5].Descriptor()
	// platformconfig.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	platformconfig.DefaultUpdatedAt = platformconfigDescUpdatedAt.Default.(func() time.Time)
	// platformconfig.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	platformconfig.UpdateDefaultUpdatedAt = platformconfigDescUpdatedAt.UpdateDefault.(func() time.Time)
	// platformconfigDescID is the schema descriptor for id field.
	platformconfigDescID := platformconfigFields[0].Descriptor()
	// platformconfig.DefaultID holds the default value on creation for the id field.
	platformconfig.DefaultID = platformconfigDescID.Default.(func() uuid.UUID)
	productFields := schema.Product{}.Fields()
	_ = productFields
	// productDescPkey is the schema descriptor for pkey field.
	productDescPkey := productFields[3].Descriptor()
	// product.PkeyValidator is a validator for the "pkey" field. It is called by the builders before save.
	product.PkeyValidator = productDescPkey.Validators[0].(func(string) error)
	// productDescName is the schema descriptor for name field.
	productDescName := productFields[4].Descriptor()
	// product.NameValidator is a validator for the "name" field. It is called by the builders before save.
	product.NameValidator = productDescName.Validators[0].(func(string) error)
	// productDescDescription is the schema descriptor for description field.
	productDescDescription := productFields[5].Descriptor()
	// product.DefaultDescription holds the default value on creation for the description field.
	product.DefaultDescription = productDescDescription.Default.(string)
	// productDescNotifyURL is the schema descriptor for notify_url field.
	productDescNotifyURL := productFields[6].Descriptor()
	// product.DefaultNotifyURL holds the default value on creation for the notify_url field.
	product.DefaultNotifyURL = productDescNotifyURL.Default.(string)
	// productDescReturnURL is the schema descriptor for return_url field.
	productDescReturnURL := productFields[7].Descriptor()
	// product.DefaultReturnURL holds the default value on creation for the return_url field.
	product.DefaultReturnURL = productDescReturnURL.Default.(string)
	// productDescKeytype is the schema descriptor for keytype field.
	productDescKeytype := productFields[10].Descriptor()
	// product.DefaultKeytype holds the default value on creation for the keytype field.
	product.DefaultKeytype = productDescKeytype.Default.(int)
	// productDescPublicKey is the schema descriptor for public_key field.
	productDescPublicKey := productFields[11].Descriptor()
	// product.DefaultPublicKey holds the default value on creation for the public_key field.
	product.DefaultPublicKey = productDescPublicKey.Default.(string)
	// productDescRefundEnabled is the schema descriptor for refund_enabled field.
	productDescRefundEnabled := productFields[12].Descriptor()
	// product.DefaultRefundEnabled holds the default value on creation for the refund_enabled field.
	product.DefaultRefundEnabled = productDescRefundEnabled.Default.(bool)
	// productDescTransferEnabled is the schema descriptor for transfer_enabled field.
	productDescTransferEnabled := productFields[13].Descriptor()
	// product.DefaultTransferEnabled holds the default value on creation for the transfer_enabled field.
	product.DefaultTransferEnabled = productDescTransferEnabled.Default.(bool)
	// productDescMode is the schema descriptor for mode field.
	productDescMode := productFields[14].Descriptor()
	// product.DefaultMode holds the default value on creation for the mode field.
	product.DefaultMode = productDescMode.Default.(int)
	// productDescCreatedAt is the schema descriptor for created_at field.
	productDescCreatedAt := productFields[15].Descriptor()
	// product.DefaultCreatedAt holds the default value on creation for the created_at field.
	product.DefaultCreatedAt = productDescCreatedAt.Default.(func() time.Time)
	// productDescUpdatedAt is the schema descriptor for updated_at field.
	productDescUpdatedAt := productFields[16].Descriptor()
	// product.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	product.DefaultUpdatedAt = productDescUpdatedAt.Default.(func() time.Time)
	// product.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	product.UpdateDefaultUpdatedAt = productDescUpdatedAt.UpdateDefault.(func() time.Time)
	// productDescID is the schema descriptor for id field.
	productDescID := productFields[0].Descriptor()
	// product.DefaultID holds the default value on creation for the id field.
	product.DefaultID = productDescID.Default.(func() uuid.UUID)
	refundFields := schema.Refund{}.Fields()
	_ = refundFields
	// refundDescRefundNo is the schema descriptor for refund_no field.
	refundDescRefundNo := refundFields[1].Descriptor()
	// refund.RefundNoValidator is a validator for the "refund_no" field. It is called by the builders before save.
	refund.RefundNoValidator = refundDescRefundNo.Validators[0].(func(string) error)
	// refundDescOutRefundNo is the schema descriptor for out_refund_no field.
	refundDescOutRefundNo := refundFields[2].Descriptor()
	// refund.DefaultOutRefundNo holds the default value on creation for the out_refund_no field.
	refund.DefaultOutRefundNo = refundDescOutRefundNo.Default.(string)
	// refundDescTradeNo is the schema descriptor for trade_no field.
	refundDescTradeNo := refundFields[3].Descriptor()
	// refund.TradeNoValidator is a validator for the "trade_no" field. It is called by the builders before save.
	refund.TradeNoValidator = refundDescTradeNo.Validators[0].(func(string) error)
	// refundDescReduceMoney is the schema descriptor for reduce_money field.
	refundDescReduceMoney := refundFields[6].Descriptor()
	// refund.DefaultReduceMoney holds the default value on creation for the reduce_money field.
	refund.DefaultReduceMoney = refundDescReduceMoney.Default.(float64)
	// refundDescMessage is the schema descriptor for message field.
	refundDescMessage := refundFields[8].Descriptor()
	// refund.DefaultMessage holds the default value on creation for the message field.
	refund.DefaultMessage = refundDescMessage.Default.(string)
	// refundDescCreatedAt is the schema descriptor for created_at field.
	refundDescCreatedAt := refundFields[9].Descriptor()
	// refund.DefaultCreatedAt holds the default value on creation for the created_at field.
	refund.DefaultCreatedAt = refundDescCreatedAt.Default.(func() time.Time)
	// refundDescUpdatedAt is the schema descriptor for updated_at field.
	refundDescUpdatedAt := refundFields[10].Descriptor()
	// refund.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	refund.DefaultUpdatedAt = refundDescUpdatedAt.Default.(func() time.Time)
	// refund.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	refund.UpdateDefaultUpdatedAt = refundDescUpdatedAt.UpdateDefault.(func() time.Time)
	// refundDescID is the schema descriptor for id field.
	refundDescID := refundFields[0].Descriptor()
	// refund.DefaultID holds the default value on creation for the id field.
	refund.DefaultID = refundDescID.Default.(func() uuid.UUID)
	settlementFields := schema.Settlement{}.Fields()
	_ = settlementFields
	// settlementDescBalance is the schema descriptor for balance field.
	settlementDescBalance := settlementFields[2].Descriptor()
	// settlement.DefaultBalance holds the default value on creation for the balance field.
	settlement.DefaultBalance = settlementDescBalance.Default.(float64)
	// settlementDescFrozen is the schema descriptor for frozen field.
	settlementDescFrozen := settlementFields[3].Descriptor()
	// settlement.DefaultFrozen holds the default value on creation for the frozen field.
	settlement.DefaultFrozen = settlementDescFrozen.Default.(float64)
	// settlementDescTotalIncome is the schema descriptor for total_income field.
	settlementDescTotalIncome := settlementFields[4].Descriptor()
	// settlement.DefaultTotalIncome holds the default value on creation for the total_income field.
	settlement.DefaultTotalIncome = settlementDescTotalIncome.Default.(float64)
	// settlementDescTotalWithdrawn is the schema descriptor for total_withdrawn field.
	settlementDescTotalWithdrawn := settlementFields[5].Descriptor()
	// settlement.DefaultTotalWithdrawn holds the default value on creation for the total_withdrawn field.
	settlement.DefaultTotalWithdrawn = settlementDescTotalWithdrawn.Default.(float64)
	// settlementDescCreatedAt is the schema descriptor for created_at field.
	settlementDescCreatedAt := settlementFields[6].Descriptor()
	// settlement.DefaultCreatedAt holds the default value on creation for the created_at field.
	settlement.DefaultCreatedAt = settlementDescCreatedAt.Default.(func() time.Time)
	// settlementDescUpdatedAt is the schema descriptor for updated_at field.
	settlementDescUpdatedAt := settlementFields[7].Descriptor()
	// settlement.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	settlement.DefaultUpdatedAt = settlementDescUpdatedAt.Default.(func() time.Time)
	// settlement.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	settlement.UpdateDefaultUpdatedAt = settlementDescUpdatedAt.UpdateDefault.(func() time.Time)
	// settlementDescID is the schema descriptor for id field.
	settlementDescID := settlementFields[0].Descriptor()
	// settlement.DefaultID holds the default value on creation for the id field.
	settlement.DefaultID = settlementDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[2].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[3].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescFeeRate is the schema descriptor for fee_rate field.
	userDescFeeRate := userFields[4].Descriptor()
	// user.DefaultFeeRate holds the default value on creation for the fee_rate field.
	user.DefaultFeeRate = userDescFeeRate.Default.(float64)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[6].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[7].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	withdrawFields := schema.Withdraw{}.Fields()
	_ = withdrawFields
	// withdrawDescAccountInfo is the schema descriptor for account_info field.
	withdrawDescAccountInfo := withdrawFields[3].Descriptor()
	// withdraw.AccountInfoValidator is a validator for the "account_info" field. It is called by the builders before save.
	withdraw.AccountInfoValidator = withdrawDescAccountInfo.Validators[0].(func(string) error)
	// withdrawDescRemark is the schema descriptor for remark field.
	withdrawDescRemark := withdrawFields[5].Descriptor()
	// withdraw.DefaultRemark holds the default value on creation for the remark field.
	withdraw.DefaultRemark = withdrawDescRemark.Default.(string)
	// withdrawDescCreatedAt is the schema descriptor for created_at field.
	withdrawDescCreatedAt := withdrawFields[6].Descriptor()
	// withdraw.DefaultCreatedAt holds the default value on creation for the created_at field.
	withdraw.DefaultCreatedAt = withdrawDescCreatedAt.Default.(func() time.Time)
	// withdrawDescUpdatedAt is the schema descriptor for updated_at field.
	withdrawDescUpdatedAt := withdrawFields[7].Descriptor()
	// withdraw.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	withdraw.DefaultUpdatedAt = withdrawDescUpdatedAt.Default.(func() time.Time)
	// withdraw.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	withdraw.UpdateDefaultUpdatedAt = withdrawDescUpdatedAt.UpdateDefault.(func() time.Time)
	// withdrawDescID is the schema descriptor for id field.
	withdrawDescID := withdrawFields[0].Descriptor()
	// withdraw.DefaultID holds the default value on creation for the id field.
	withdraw.DefaultID = withdrawDescID.Default.(func() uuid.UUID)
}
