// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"epay/ent/merchant"
	"epay/ent/predicate"
	"epay/ent/settlement"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SettlementUpdate is the builder for updating Settlement entities.
type SettlementUpdate struct {
	config
	hooks    []Hook
	mutation *SettlementMutation
}

// Where appends a list predicates to the SettlementUpdate builder.
func (_u *SettlementUpdate) Where(ps ...predicate.Settlement) *SettlementUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMerchantID sets the "merchant_id" field.
func (_u *SettlementUpdate) SetMerchantID(v uuid.UUID) *SettlementUpdate {
	_u.mutation.SetMerchantID(v)
	return _u
}

// SetNillableMerchantID sets the "merchant_id" field if the given value is not nil.
func (_u *SettlementUpdate) SetNillableMerchantID(v *uuid.UUID) *SettlementUpdate {
	if v != nil {
		_u.SetMerchantID(*v)
	}
	return _u
}

// SetBalance sets the "balance" field.
func (_u *SettlementUpdate) SetBalance(v float64) *SettlementUpdate {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *SettlementUpdate) SetNillableBalance(v *float64) *SettlementUpdate {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *SettlementUpdate) AddBalance(v float64) *SettlementUpdate {
	_u.mutation.AddBalance(v)
	return _u
}

// SetFrozen sets the "frozen" field.
func (_u *SettlementUpdate) SetFrozen(v float64) *SettlementUpdate {
	_u.mutation.ResetFrozen()
	_u.mutation.SetFrozen(v)
	return _u
}

// SetNillableFrozen sets the "frozen" field if the given value is not nil.
func (_u *SettlementUpdate) SetNillableFrozen(v *float64) *SettlementUpdate {
	if v != nil {
		_u.SetFrozen(*v)
	}
	return _u
}

// AddFrozen adds value to the "frozen" field.
func (_u *SettlementUpdate) AddFrozen(v float64) *SettlementUpdate {
	_u.mutation.AddFrozen(v)
	return _u
}

// SetTotalIncome sets the "total_income" field.
func (_u *SettlementUpdate) SetTotalIncome(v float64) *SettlementUpdate {
	_u.mutation.ResetTotalIncome()
	_u.mutation.SetTotalIncome(v)
	return _u
}

// SetNillableTotalIncome sets the "total_income" field if the given value is not nil.
func (_u *SettlementUpdate) SetNillableTotalIncome(v *float64) *SettlementUpdate {
	if v != nil {
		_u.SetTotalIncome(*v)
	}
	return _u
}

// AddTotalIncome adds value to the "total_income" field.
func (_u *SettlementUpdate) AddTotalIncome(v float64) *SettlementUpdate {
	_u.mutation.AddTotalIncome(v)
	return _u
}

// SetTotalWithdrawn sets the "total_withdrawn" field.
func (_u *SettlementUpdate) SetTotalWithdrawn(v float64) *SettlementUpdate {
	_u.mutation.ResetTotalWithdrawn()
	_u.mutation.SetTotalWithdrawn(v)
	return _u
}

// SetNillableTotalWithdrawn sets the "total_withdrawn" field if the given value is not nil.
func (_u *SettlementUpdate) SetNillableTotalWithdrawn(v *float64) *SettlementUpdate {
	if v != nil {
		_u.SetTotalWithdrawn(*v)
	}
	return _u
}

// AddTotalWithdrawn adds value to the "total_withdrawn" field.
func (_u *SettlementUpdate) AddTotalWithdrawn(v float64) *SettlementUpdate {
	_u.mutation.AddTotalWithdrawn(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SettlementUpdate) SetUpdatedAt(v time.Time) *SettlementUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMerchant sets the "merchant" edge to the Merchant entity.
func (_u *SettlementUpdate) SetMerchant(v *Merchant) *SettlementUpdate {
	return _u.SetMerchantID(v.ID)
}

// Mutation returns the SettlementMutation object of the builder.
func (_u *SettlementUpdate) Mutation() *SettlementMutation {
	return _u.mutation
}

// ClearMerchant clears the "merchant" edge to the Merchant entity.
func (_u *SettlementUpdate) ClearMerchant() *SettlementUpdate {
	_u.mutation.ClearMerchant()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SettlementUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SettlementUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SettlementUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SettlementUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SettlementUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := settlement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SettlementUpdate) check() error {
	if _u.mutation.MerchantCleared() && len(_u.mutation.MerchantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Settlement.merchant"`)
	}
	return nil
}

func (_u *SettlementUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(settlement.Table, settlement.Columns, sqlgraph.NewFieldSpec(settlement.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(settlement.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(settlement.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Frozen(); ok {
		_spec.SetField(settlement.FieldFrozen, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFrozen(); ok {
		_spec.AddField(settlement.FieldFrozen, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalIncome(); ok {
		_spec.SetField(settlement.FieldTotalIncome, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalIncome(); ok {
		_spec.AddField(settlement.FieldTotalIncome, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalWithdrawn(); ok {
		_spec.SetField(settlement.FieldTotalWithdrawn, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalWithdrawn(); ok {
		_spec.AddField(settlement.FieldTotalWithdrawn, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(settlement.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MerchantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   settlement.MerchantTable,
			Columns: []string{settlement.MerchantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(merchant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MerchantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   settlement.MerchantTable,
			Columns: []string{settlement.MerchantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(merchant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{settlement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SettlementUpdateOne is the builder for updating a single Settlement entity.
type SettlementUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SettlementMutation
}

// SetMerchantID sets the "merchant_id" field.
func (_u *SettlementUpdateOne) SetMerchantID(v uuid.UUID) *SettlementUpdateOne {
	_u.mutation.SetMerchantID(v)
	return _u
}

// SetNillableMerchantID sets the "merchant_id" field if the given value is not nil.
func (_u *SettlementUpdateOne) SetNillableMerchantID(v *uuid.UUID) *SettlementUpdateOne {
	if v != nil {
		_u.SetMerchantID(*v)
	}
	return _u
}

// SetBalance sets the "balance" field.
func (_u *SettlementUpdateOne) SetBalance(v float64) *SettlementUpdateOne {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *SettlementUpdateOne) SetNillableBalance(v *float64) *SettlementUpdateOne {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *SettlementUpdateOne) AddBalance(v float64) *SettlementUpdateOne {
	_u.mutation.AddBalance(v)
	return _u
}

// SetFrozen sets the "frozen" field.
func (_u *SettlementUpdateOne) SetFrozen(v float64) *SettlementUpdateOne {
	_u.mutation.ResetFrozen()
	_u.mutation.SetFrozen(v)
	return _u
}

// SetNillableFrozen sets the "frozen" field if the given value is not nil.
func (_u *SettlementUpdateOne) SetNillableFrozen(v *float64) *SettlementUpdateOne {
	if v != nil {
		_u.SetFrozen(*v)
	}
	return _u
}

// AddFrozen adds value to the "frozen" field.
func (_u *SettlementUpdateOne) AddFrozen(v float64) *SettlementUpdateOne {
	_u.mutation.AddFrozen(v)
	return _u
}

// SetTotalIncome sets the "total_income" field.
func (_u *SettlementUpdateOne) SetTotalIncome(v float64) *SettlementUpdateOne {
	_u.mutation.ResetTotalIncome()
	_u.mutation.SetTotalIncome(v)
	return _u
}

// SetNillableTotalIncome sets the "total_income" field if the given value is not nil.
func (_u *SettlementUpdateOne) SetNillableTotalIncome(v *float64) *SettlementUpdateOne {
	if v != nil {
		_u.SetTotalIncome(*v)
	}
	return _u
}

// AddTotalIncome adds value to the "total_income" field.
func (_u *SettlementUpdateOne) AddTotalIncome(v float64) *SettlementUpdateOne {
	_u.mutation.AddTotalIncome(v)
	return _u
}

// SetTotalWithdrawn sets the "total_withdrawn" field.
func (_u *SettlementUpdateOne) SetTotalWithdrawn(v float64) *SettlementUpdateOne {
	_u.mutation.ResetTotalWithdrawn()
	_u.mutation.SetTotalWithdrawn(v)
	return _u
}

// SetNillableTotalWithdrawn sets the "total_withdrawn" field if the given value is not nil.
func (_u *SettlementUpdateOne) SetNillableTotalWithdrawn(v *float64) *SettlementUpdateOne {
	if v != nil {
		_u.SetTotalWithdrawn(*v)
	}
	return _u
}

// AddTotalWithdrawn adds value to the "total_withdrawn" field.
func (_u *SettlementUpdateOne) AddTotalWithdrawn(v float64) *SettlementUpdateOne {
	_u.mutation.AddTotalWithdrawn(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SettlementUpdateOne) SetUpdatedAt(v time.Time) *SettlementUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMerchant sets the "merchant" edge to the Merchant entity.
func (_u *SettlementUpdateOne) SetMerchant(v *Merchant) *SettlementUpdateOne {
	return _u.SetMerchantID(v.ID)
}

// Mutation returns the SettlementMutation object of the builder.
func (_u *SettlementUpdateOne) Mutation() *SettlementMutation {
	return _u.mutation
}

// ClearMerchant clears the "merchant" edge to the Merchant entity.
func (_u *SettlementUpdateOne) ClearMerchant() *SettlementUpdateOne {
	_u.mutation.ClearMerchant()
	return _u
}

// Where appends a list predicates to the SettlementUpdate builder.
func (_u *SettlementUpdateOne) Where(ps ...predicate.Settlement) *SettlementUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SettlementUpdateOne) Select(field string, fields ...string) *SettlementUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Settlement entity.
func (_u *SettlementUpdateOne) Save(ctx context.Context) (*Settlement, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SettlementUpdateOne) SaveX(ctx context.Context) *Settlement {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SettlementUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SettlementUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SettlementUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := settlement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SettlementUpdateOne) check() error {
	if _u.mutation.MerchantCleared() && len(_u.mutation.MerchantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Settlement.merchant"`)
	}
	return nil
}

func (_u *SettlementUpdateOne) sqlSave(ctx context.Context) (_node *Settlement, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(settlement.Table, settlement.Columns, sqlgraph.NewFieldSpec(settlement.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Settlement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, settlement.FieldID)
		for _, f := range fields {
			if !settlement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != settlement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(settlement.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(settlement.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Frozen(); ok {
		_spec.SetField(settlement.FieldFrozen, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFrozen(); ok {
		_spec.AddField(settlement.FieldFrozen, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalIncome(); ok {
		_spec.SetField(settlement.FieldTotalIncome, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalIncome(); ok {
		_spec.AddField(settlement.FieldTotalIncome, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalWithdrawn(); ok {
		_spec.SetField(settlement.FieldTotalWithdrawn, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalWithdrawn(); ok {
		_spec.AddField(settlement.FieldTotalWithdrawn, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(settlement.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MerchantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   settlement.MerchantTable,
			Columns: []string{settlement.MerchantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(merchant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MerchantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   settlement.MerchantTable,
			Columns: []string{settlement.MerchantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(merchant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Settlement{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{settlement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
