// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"epay/ent/settlement"
	"epay/ent/user"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SettlementCreate is the builder for creating a Settlement entity.
type SettlementCreate struct {
	config
	mutation *SettlementMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *SettlementCreate) SetUserID(v uuid.UUID) *SettlementCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetBalance sets the "balance" field.
func (_c *SettlementCreate) SetBalance(v float64) *SettlementCreate {
	_c.mutation.SetBalance(v)
	return _c
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_c *SettlementCreate) SetNillableBalance(v *float64) *SettlementCreate {
	if v != nil {
		_c.SetBalance(*v)
	}
	return _c
}

// SetFrozen sets the "frozen" field.
func (_c *SettlementCreate) SetFrozen(v float64) *SettlementCreate {
	_c.mutation.SetFrozen(v)
	return _c
}

// SetNillableFrozen sets the "frozen" field if the given value is not nil.
func (_c *SettlementCreate) SetNillableFrozen(v *float64) *SettlementCreate {
	if v != nil {
		_c.SetFrozen(*v)
	}
	return _c
}

// SetTotalIncome sets the "total_income" field.
func (_c *SettlementCreate) SetTotalIncome(v float64) *SettlementCreate {
	_c.mutation.SetTotalIncome(v)
	return _c
}

// SetNillableTotalIncome sets the "total_income" field if the given value is not nil.
func (_c *SettlementCreate) SetNillableTotalIncome(v *float64) *SettlementCreate {
	if v != nil {
		_c.SetTotalIncome(*v)
	}
	return _c
}

// SetTotalWithdrawn sets the "total_withdrawn" field.
func (_c *SettlementCreate) SetTotalWithdrawn(v float64) *SettlementCreate {
	_c.mutation.SetTotalWithdrawn(v)
	return _c
}

// SetNillableTotalWithdrawn sets the "total_withdrawn" field if the given value is not nil.
func (_c *SettlementCreate) SetNillableTotalWithdrawn(v *float64) *SettlementCreate {
	if v != nil {
		_c.SetTotalWithdrawn(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SettlementCreate) SetCreatedAt(v time.Time) *SettlementCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SettlementCreate) SetNillableCreatedAt(v *time.Time) *SettlementCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SettlementCreate) SetUpdatedAt(v time.Time) *SettlementCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SettlementCreate) SetNillableUpdatedAt(v *time.Time) *SettlementCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SettlementCreate) SetID(v uuid.UUID) *SettlementCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SettlementCreate) SetNillableID(v *uuid.UUID) *SettlementCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *SettlementCreate) SetUser(v *User) *SettlementCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the SettlementMutation object of the builder.
func (_c *SettlementCreate) Mutation() *SettlementMutation {
	return _c.mutation
}

// Save creates the Settlement in the database.
func (_c *SettlementCreate) Save(ctx context.Context) (*Settlement, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SettlementCreate) SaveX(ctx context.Context) *Settlement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SettlementCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SettlementCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SettlementCreate) defaults() {
	if _, ok := _c.mutation.Balance(); !ok {
		v := settlement.DefaultBalance
		_c.mutation.SetBalance(v)
	}
	if _, ok := _c.mutation.Frozen(); !ok {
		v := settlement.DefaultFrozen
		_c.mutation.SetFrozen(v)
	}
	if _, ok := _c.mutation.TotalIncome(); !ok {
		v := settlement.DefaultTotalIncome
		_c.mutation.SetTotalIncome(v)
	}
	if _, ok := _c.mutation.TotalWithdrawn(); !ok {
		v := settlement.DefaultTotalWithdrawn
		_c.mutation.SetTotalWithdrawn(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := settlement.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := settlement.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := settlement.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SettlementCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Settlement.user_id"`)}
	}
	if _, ok := _c.mutation.Balance(); !ok {
		return &ValidationError{Name: "balance", err: errors.New(`ent: missing required field "Settlement.balance"`)}
	}
	if _, ok := _c.mutation.Frozen(); !ok {
		return &ValidationError{Name: "frozen", err: errors.New(`ent: missing required field "Settlement.frozen"`)}
	}
	if _, ok := _c.mutation.TotalIncome(); !ok {
		return &ValidationError{Name: "total_income", err: errors.New(`ent: missing required field "Settlement.total_income"`)}
	}
	if _, ok := _c.mutation.TotalWithdrawn(); !ok {
		return &ValidationError{Name: "total_withdrawn", err: errors.New(`ent: missing required field "Settlement.total_withdrawn"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Settlement.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Settlement.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Settlement.user"`)}
	}
	return nil
}

func (_c *SettlementCreate) sqlSave(ctx context.Context) (*Settlement, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SettlementCreate) createSpec() (*Settlement, *sqlgraph.CreateSpec) {
	var (
		_node = &Settlement{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(settlement.Table, sqlgraph.NewFieldSpec(settlement.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Balance(); ok {
		_spec.SetField(settlement.FieldBalance, field.TypeFloat64, value)
		_node.Balance = value
	}
	if value, ok := _c.mutation.Frozen(); ok {
		_spec.SetField(settlement.FieldFrozen, field.TypeFloat64, value)
		_node.Frozen = value
	}
	if value, ok := _c.mutation.TotalIncome(); ok {
		_spec.SetField(settlement.FieldTotalIncome, field.TypeFloat64, value)
		_node.TotalIncome = value
	}
	if value, ok := _c.mutation.TotalWithdrawn(); ok {
		_spec.SetField(settlement.FieldTotalWithdrawn, field.TypeFloat64, value)
		_node.TotalWithdrawn = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(settlement.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(settlement.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   settlement.UserTable,
			Columns: []string{settlement.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SettlementCreateBulk is the builder for creating many Settlement entities in bulk.
type SettlementCreateBulk struct {
	config
	err      error
	builders []*SettlementCreate
}

// Save creates the Settlement entities in the database.
func (_c *SettlementCreateBulk) Save(ctx context.Context) ([]*Settlement, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Settlement, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SettlementMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SettlementCreateBulk) SaveX(ctx context.Context) []*Settlement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SettlementCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SettlementCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
