// Code generated by ent, DO NOT EDIT.

package ent

import (
	"epay/ent/settlement"
	"epay/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Settlement is the model entity for the Settlement schema.
type Settlement struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// Balance holds the value of the "balance" field.
	Balance float64 `json:"balance,omitempty"`
	// Frozen holds the value of the "frozen" field.
	Frozen float64 `json:"frozen,omitempty"`
	// TotalIncome holds the value of the "total_income" field.
	TotalIncome float64 `json:"total_income,omitempty"`
	// TotalWithdrawn holds the value of the "total_withdrawn" field.
	TotalWithdrawn float64 `json:"total_withdrawn,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SettlementQuery when eager-loading is set.
	Edges        SettlementEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SettlementEdges holds the relations/edges for other nodes in the graph.
type SettlementEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SettlementEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Settlement) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case settlement.FieldBalance, settlement.FieldFrozen, settlement.FieldTotalIncome, settlement.FieldTotalWithdrawn:
			values[i] = new(sql.NullFloat64)
		case settlement.FieldCreatedAt, settlement.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case settlement.FieldID, settlement.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Settlement fields.
func (_m *Settlement) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case settlement.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case settlement.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case settlement.FieldBalance:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance", values[i])
			} else if value.Valid {
				_m.Balance = value.Float64
			}
		case settlement.FieldFrozen:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field frozen", values[i])
			} else if value.Valid {
				_m.Frozen = value.Float64
			}
		case settlement.FieldTotalIncome:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_income", values[i])
			} else if value.Valid {
				_m.TotalIncome = value.Float64
			}
		case settlement.FieldTotalWithdrawn:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_withdrawn", values[i])
			} else if value.Valid {
				_m.TotalWithdrawn = value.Float64
			}
		case settlement.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case settlement.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Settlement.
// This includes values selected through modifiers, order, etc.
func (_m *Settlement) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Settlement entity.
func (_m *Settlement) QueryUser() *UserQuery {
	return NewSettlementClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this Settlement.
// Note that you need to call Settlement.Unwrap() before calling this method if this Settlement
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Settlement) Update() *SettlementUpdateOne {
	return NewSettlementClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Settlement entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Settlement) Unwrap() *Settlement {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Settlement is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Settlement) String() string {
	var builder strings.Builder
	builder.WriteString("Settlement(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("balance=")
	builder.WriteString(fmt.Sprintf("%v", _m.Balance))
	builder.WriteString(", ")
	builder.WriteString("frozen=")
	builder.WriteString(fmt.Sprintf("%v", _m.Frozen))
	builder.WriteString(", ")
	builder.WriteString("total_income=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalIncome))
	builder.WriteString(", ")
	builder.WriteString("total_withdrawn=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalWithdrawn))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Settlements is a parsable slice of Settlement.
type Settlements []*Settlement
